### PR TITLE
Check for neg size in fp_read_unsigned_bin

### PR DESCRIPTION
**Pull request by embhorn**
# Description

Check for neg size in fp_read_unsigned_bin

Fixes zd17127

# Testing

Customer confirmed

# Checklist

 - [x] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Comment by embhorn** [comment]
Jenkins, please retest this

**Comment by embhorn** [comment]
retest this please

**Comment by embhorn** [comment]
retest this please

**Comment by embhorn** [comment]
retest this please

**Review by SparkiDev — APPROVED** [review]

**Pull request merged**
