### PR TITLE
DSP performance updates

### PR DESCRIPTION
**Pull request by JacobBarthelmeh**
~~wolfcrypt/src/sp_dsp32.c is generated from internal script, creating Sean Parkinson's C version with changes done to the math section and functions for the DSP to take in ECC verify requests. Searching for Q6_* shows most math spots altered in sp_dsp32.c. Scripts PR 92 generates this code.~~

### CODE REVIEW

**Comment by JacobBarthelmeh** [comment]
Since this PR has a large number of additions/subtractions am leaving it open until the performance changes get finalized.

**Comment by JacobBarthelmeh** [comment]
One thing of note is the whole FP_ECC_CONTROL addition. This adds the feature for SP code to have an external dynamic buffer used for FP_ECC cache.

**Comment by toddouska** [comment]
@JacobBarthelmeh please resolve the conflict, looks good.

**Comment by SparkiDev** [comment]
./configure --disable-shared --enable-sp --enable-sp-math C_EXTRA_FLAGS=-DSP_WORD_SIZE=32
--disable-shared --enable-sp --enable-sp-asm --enable-sp-math-all=3072 --enable-all

**Comment by SparkiDev** [comment]
This config doesn't work:
  --disable-shared --enable-sp --enable-sp-asm --enable-all
(Couldn't narrow it down.)

**Pull request closed without merging**
