### PR TITLE
removed backslash

### PR DESCRIPTION
**Pull request by SKlimaRA**
# Description

Please describe the scope of the fix or feature addition.

Fixes zd#15072

# Testing

How did you test?

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Comment by embhorn** [comment]
Jenkins please test this

**Review by embhorn — APPROVED** [review]

**Comment by embhorn** [comment]
Retest this

**Comment by dgarske** [comment]
OK to test

**Comment by embhorn** [comment]
OK to test

**Review by JacobBarthelmeh — APPROVED** [review]

**Pull request merged**
