### PR TITLE
Refactor of Visual Studio projects to centralize preprocessors into IDE/WIN/user_settings.h

### PR DESCRIPTION
**Pull request by dgarske**
Added signature.c to Visual Studio project files.

Added new "IDE/WIN/user_settings.h" which contains all the defines for the various Windows Visual Studio projects. Moved the settings into this new file and added the WOLFSSL_USER_SETTINGS and CYASSL_USER_SETTINGS macros and include path to IDE/WIN to all project files. This allows the settings to be adjusted in a single place.

### CODE REVIEW

**Comment by kaleb-himes** [comment]
- Waiting to review ChangeToWolfRoot before checking these...

**Comment by kaleb-himes** [comment]
Still a few kinks to be worked out with pre-processor macros in IDE/WIN/wolfssl-fips.sln

**Comment by dgarske** [comment]
Hey Kaleb, I found a few issues with the FIPS windows build that have been fixed. Thanks!

**Comment by kaleb-himes** [comment]
Looks Good.

**Pull request merged**
