### PR TITLE
Expose DTLS in Ada wrapper and update examples

### PR DESCRIPTION
**Pull request by dalybrown**
# Description

The Ada wrapper was updated to expose DTLS v1.2 and v1.3. In addition, the example was updated to optionally use DTLS.

I tried to make as little changes as possible in this pull request and to use the style as the original author. It ended up being a bit messy though. However, there are a bunch of changes I would like to propose to this library in a different pull request. Mainly, as it stands, this is more of an example of how to use Ada with WolfSSL rather than a real wrapper usable by clients in their own production applications. I would like to refactor this in another pull request to make it usable as a library in other Ada projects. I would also like to make it an Alire project so that it can be used by the Ada package manager. Again, this will all be done in a subsequent pull request since it will result in quite a bit of churn.

# Testing

I built and ran the examples using TLS and DTLS. No new tests were added.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [x] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Comment by dalybrown** [comment]
I obviously missed this pull request: https://github.com/wolfSSL/wolfssl/pull/7303. That is starting to address the things I mentioned in the description about making this a usable library. The changes I made still stand here and I'm glad to help out that other pull request!

**Comment by joakim-strandberg** [comment]
Very nice with DTLS examples! Great work!

SPARK warns about "DTLS   : Boolean := False;", initialization has no effect in both the tls_client.adb and tls_server.adb files. SPARK also warns on a number of places that the pre-condition might fail on "SPARK_Sockets.Close_Socket (C);" in the tls_server.adb file. I am using SPARK in the GNAT Community Edition 2021 on Linux. It should be possible to silence the warnings by introducing appropriate if-statements and removing the unnecessary assignments. Daly would you like to double-check?

**Comment by dalybrown** [comment]
> Very nice with DTLS examples! Great work!
> 
> SPARK warns about "DTLS : Boolean := False;", initialization has no effect in both the tls_client.adb and tls_server.adb files. SPARK also warns on a number of places that the pre-condition might fail on "SPARK_Sockets.Close_Socket (C);" in the tls_server.adb file. I am using SPARK in the GNAT Community Edition 2021 on Linux. It should be possible to silence the warnings by introducing appropriate if-statements and removing the unnecessary assignments. Daly would you like to double-check?

I'll address all this!

**Comment by dalybrown** [comment]
> Very nice with DTLS examples! Great work!
> 
> SPARK warns about "DTLS : Boolean := False;", initialization has no effect in both the tls_client.adb and tls_server.adb files. SPARK also warns on a number of places that the pre-condition might fail on "SPARK_Sockets.Close_Socket (C);" in the tls_server.adb file. I am using SPARK in the GNAT Community Edition 2021 on Linux. It should be possible to silence the warnings by introducing appropriate if-statements and removing the unnecessary assignments. Daly would you like to double-check?

Done! Let me know if you think anything else needs updating.

**Comment by joakim-strandberg** [comment]
Thanks for addressing! Now there is only one SPARK warning left in the tls_client.adb file.

**Comment by dalybrown** [comment]
> Thanks for addressing! Now there is only one SPARK warning left in the tls_client.adb file.

Is this the existing IO warning? I ran `gnatprove` using silver and level 2. What settings do you use?

**Comment by joakim-strandberg** [comment]
Thank you for your patience Daly. It's the "SPARK warns about "DTLS : Boolean := False;", initialization has no effect in the tls_client.adb file". You fixed it in the tls_server.adb but the same warning was in both tls_client.adb and tls_server.adb files. Have you committed the version of tls_client.adb that you have locally?

**Comment by Irvise** [comment]
Thank you for your work @dalybrown!

As far as I saw in your changes, your PR adds content to the binding and it does not conflict with #7303. I would prefer if you merged your changes first and then I would restructure the files in the way you proposed in your comment over at #7303. Do you agree?

**Comment by joakim-strandberg** [comment]
@Irvise I agree with you.

**Comment by dalybrown** [comment]
> Thank you for your patience Daly. It's the "SPARK warns about "DTLS : Boolean := False;", initialization has no effect in the tls_client.adb file". You fixed it in the tls_server.adb but the same warning was in both tls_client.adb and tls_server.adb files. Have you committed the version of tls_client.adb that you have locally? (I also use level 2)

Ah right. There were a few other issues actually in the client that were flagged with my version of `gnatprove`. I'm using the `fsf-13` version.

Anyways I've updated them now.

**Comment by dalybrown** [comment]
> Thank you for your work @dalybrown!
> 
> As far as I saw in your changes, your PR adds content to the binding and it does not conflict with #7303. I would prefer if you merged your changes first and then I would restructure the files in the way you proposed in your comment over at #7303. Do you agree?

Sounds good to me! Let me know if I can help.

**Comment by Irvise** [comment]
> > Thank you for your work @dalybrown!
> > As far as I saw in your changes, your PR adds content to the binding and it does not conflict with #7303. I would prefer if you merged your changes first and then I would restructure the files in the way you proposed in your comment over at #7303. Do you agree?
> 
> Sounds good to me! Let me know if I can help.

Looks good to me, but I am no SPARK expert x) I would give you the go ahead for the merge, but lets see what Joakim has to say :)

**Comment by joakim-strandberg** [comment]
I say all systems go! Great work!

**Comment by dalybrown** [comment]
> I say all systems go! Great work!

Awesome! I guess I'll wait for a maintainer to approve and merge! I sent my contribution agreement yesterday.

**Comment by dgarske** [comment]
Okay to test.

**Comment by embhorn** [comment]
@dalybrown has been approved as a wolfSSL contributor

**Review by dgarske — APPROVED** [review]
Thank you @dalybrown for this wonderful work. Approved and over to @wolfSSL-Bot  (PR Captain) to finalize.

**Comment by dgarske** [comment]
Retest this please

**Comment by JacobBarthelmeh** [comment]
Building `wolfssl\wrapper\Ada\tls_client_main.adb` on Windows using the GNAT IDE I see :

```
   [C]            ssl.c
In file included from d:\work\wolfssl/wolfssl/ssl.h:164,
                 from d:\work\wolfssl/wolfssl/internal.h:28,
                 from D:\work\wolfssl\src\ssl.c:37:
D:\work\wolfssl\src\ssl.c: In function 'wolfSSL_dtls_create_peer':
d:\work\wolfssl/wolfssl/wolfio.h:767:41: warning: implicit declaration of function 'InetPton'; did you mean 'inet_ntoa'? [-Wimplicit-function-declaration]
             #define XINET_PTON(a,b,c)   InetPton((a),(b),(c))
                                         ^~~~~~~~
D:\work\wolfssl\src\ssl.c:2084:9: note: in expansion of macro 'XINET_PTON'
     if (XINET_PTON(AF_INET, ip, &addr->sin_addr) < 1) {
         ^~~~~~~~~~
d:\work\wolfssl/wolfssl/wolfio.h:767:41: warning: nested extern declaration of 'InetPton' [-Wnested-externs]
             #define XINET_PTON(a,b,c)   InetPton((a),(b),(c))
                                         ^~~~~~~~
D:\work\wolfssl\src\ssl.c:2084:9: note: in expansion of macro 'XINET_PTON'
     if (XINET_PTON(AF_INET, ip, &addr->sin_addr) < 1) {
         ^~~~~~~~~~
   [C]            sniffer.c
   [C]            quic.c
   ```
   
   Could you take a look at this? Maybe I'm missing a define needed? Had tested on the same setup that the client Ada project built and ran before the changes.

**Comment by dalybrown** [comment]
> @dalybrown
> 
> Building `wolfssl\wrapper\Ada\tls_client_main.adb` on Windows using the GNAT IDE I see :
> 
> ```
>    [C]            ssl.c
> In file included from d:\work\wolfssl/wolfssl/ssl.h:164,
>                  from d:\work\wolfssl/wolfssl/internal.h:28,
>                  from D:\work\wolfssl\src\ssl.c:37:
> D:\work\wolfssl\src\ssl.c: In function 'wolfSSL_dtls_create_peer':
> d:\work\wolfssl/wolfssl/wolfio.h:767:41: warning: implicit declaration of function 'InetPton'; did you mean 'inet_ntoa'? [-Wimplicit-function-declaration]
>              #define XINET_PTON(a,b,c)   InetPton((a),(b),(c))
>                                          ^~~~~~~~
> D:\work\wolfssl\src\ssl.c:2084:9: note: in expansion of macro 'XINET_PTON'
>      if (XINET_PTON(AF_INET, ip, &addr->sin_addr) < 1) {
>          ^~~~~~~~~~
> d:\work\wolfssl/wolfssl/wolfio.h:767:41: warning: nested extern declaration of 'InetPton' [-Wnested-externs]
>              #define XINET_PTON(a,b,c)   InetPton((a),(b),(c))
>                                          ^~~~~~~~
> D:\work\wolfssl\src\ssl.c:2084:9: note: in expansion of macro 'XINET_PTON'
>      if (XINET_PTON(AF_INET, ip, &addr->sin_addr) < 1) {
>          ^~~~~~~~~~
>    [C]            sniffer.c
>    [C]            quic.c
> ```
> 
> Could you take a look at this? Maybe I'm missing a define needed? Had tested on the same setup that the client Ada project built and ran before the changes.

Can you provide a bit more information about your environment? For example, what version of `gnat` and `gcc` are you using? I don't see this issue (and I assume @joakim-strandberg and @Irvise didn't either).

The output you show here seems to indicate your problem is not with my code changes but with the underlying code is calls (in this case, `wolfSSL_dtls_create_peer`). As an exercise, using your same setup, are you able to build and run the dtls examples already provided (here)[https://github.com/wolfSSL/wolfssl-examples/blob/master/dtls/client-dtls13.c]?

**Comment by JacobBarthelmeh** [comment]
Windows 11 OS with`GNAT Studio Community 2021 (20210423) hosted on x86_64-w64-mingw32` , `GNAT Community 2021 (20210519-103) targeting x86_64-w64-mingw32`. It's possible something in my environment is not setup right with GNAT or the mingw32 compiler. I did a fresh clone of wolfSSL + this PR in case of any build debris left over with retesting.

Adding DTLS support expanded the code to use InetPton which exposed the build issue am running into. I also tried now adding -lws2_32 to the default.gpr file next to -lcrypt32 in case that was needed but without success. I might switch over to Linux for testing.

One question I do have is, is it possible to easily toggle on / off the DTLS support?

**Comment by Irvise** [comment]
Hi all,

GNAT 2021 Community Edition is fairly old... I have not tested WolfSSL on a Windows system. I could try using MinGW to cross-compile a binary from Linux to Windows, as the results should be basically the same. I am using GNAT 13 for my compilation tests.

However, adding to what Daly said, the error seems to be taking place over at the C files that compose WolfSSL during their compilation into objects. The only change in this PR which could be the cause for that warning/error is
```
#define WOLFSSL_DTLS
// #define WOLFSSL_MULTICAST
#define WOLFSSL_DTLS13
```
as it tells WolfSSL to build that functionality. Maybe an extra "flag" is needed for the correct function definitions to be enabled. If I have time, later today, I will try compiling this branch and report back.

Best regards,
Fer

**Comment by Irvise** [comment]
Hi,

I did some testing on Daly's branch. I used Debian (through `distrobox`) to run its MinGW toolchain in order to cross-compiler from Linux to Windows. I installed `gnat-mingw-w64` which includes the 32 and 64-bit compiler versions. I used the 64-bit version `gnat-mingw-w64-x86-64`. This is GNAT/GCC v12. Then with `gprbuild` I selected the Windows target and compiled the wrapper/binding: `gprbuild -f -P client.gpr --target=x86_64-windows -XOS_Kind=Windows -j0`. The `-f` flag is to for the recompilation of everything, just to make sure that there are no cached files. The `--target=x86_64-windows ` flag selects the `/usr/bin/x86_64-w64-mingw32-gcc` compiler. Funnily, the `-XOS_Kind=Windows` flag did not seem necessary, but I added it for good measure.

With this setup, no warnings or issues take place. A `tls_client_main.exe` is generated without issue. The same story applies with `default.gpr` creating a `tls_server_main.exe`.

I ran both executables using the `wine` translator and the programs ran as expected:

```
fernando@localhost:~/Dirt/Daly/wolfssl/wrapper/Ada/obj> wine tls_server_main.exe
Waiting for a connection...
Client connected successfully.
hello
Shutdown complete.
Waiting for a connection...
```

```
fernando@localhost:~/Dirt/Daly/wolfssl/wrapper/Ada/obj> wine tls_client_main.exe 127.0.0.1
Message for server: hello
Server: I hear ya fa shizzle!
fernando@localhost:~/Dirt/Daly/wolfssl/wrapper/Ada/obj> 
```

Therefore @JacobBarthelmeh , my conclusion would be to try and use a more up-to-date Ada compiler if possible :)

**Comment by dalybrown** [comment]
> Hi,
> 
> I did some testing on Daly's branch. I used Debian (through `distrobox`) to run its MinGW toolchain in order to cross-compiler from Linux to Windows. I installed `gnat-mingw-w64` which includes the 32 and 64-bit compiler versions. I used the 64-bit version `gnat-mingw-w64-x86-64`. This is GNAT/GCC v12. Then with `gprbuild` I selected the Windows target and compiled the wrapper/binding: `gprbuild -f -P client.gpr --target=x86_64-windows -XOS_Kind=Windows -j0`. The `-f` flag is to for the recompilation of everything, just to make sure that there are no cached files. The `--target=x86_64-windows ` flag selects the `/usr/bin/x86_64-w64-mingw32-gcc` compiler. Funnily, the `-XOS_Kind=Windows` flag did not seem necessary, but I added it for good measure.
> 
> With this setup, no warnings or issues take place. A `tls_client_main.exe` is generated without issue. The same story applies with `default.gpr` creating a `tls_server_main.exe`.
> 
> I ran both executables using the `wine` translator and the programs ran as expected:
> 
> ```
> fernando@localhost:~/Dirt/Daly/wolfssl/wrapper/Ada/obj> wine tls_server_main.exe
> Waiting for a connection...
> Client connected successfully.
> hello
> Shutdown complete.
> Waiting for a connection...
> ```
> 
> ```
> fernando@localhost:~/Dirt/Daly/wolfssl/wrapper/Ada/obj> wine tls_client_main.exe 127.0.0.1
> Message for server: hello
> Server: I hear ya fa shizzle!
> fernando@localhost:~/Dirt/Daly/wolfssl/wrapper/Ada/obj> 
> ```
> 
> Therefore @JacobBarthelmeh , my conclusion would be to try and use a more up-to-date Ada compiler if possible :)

Thanks for this test and helping out!

I would suggest the same ... I think it's probably safe to merge. I'm curious if @JacobBarthelmeh can build the C examples I linked to.

**Comment by JacobBarthelmeh** [comment]
Re-ran with updated tools

`GNAT Studio 24.0w (20230501) hosted on x86_64-w64-mingw32
GNAT 13.2.0 targeting x86_64-w64-mingw32`
gprbuild : `gprbuild-x86_64-windows64-24.0.0-1`
gnat :  `gnat-x86_64-windows64-13.2.0-2`

Unfortunately ran into the same build issue when using GNAT Studio on Windows 11.

My biggest issue with it, is that before this PR the project builds cleanly. After adding the changes from the PR it hits this :

```
gprbuild -PD:\work\wolfssl\wrapper\Ada\default.gpr -XOS=Windows -d -s -f
...
...
D:\work\wolfssl\src\ssl.c: In function 'wolfSSL_dtls_create_peer':
d:\work\wolfssl/wolfssl/wolfio.h:763:33: warning: implicit declaration of function 'inet_pton'; did you mean 'inet_ntoa'? [-Wimplicit-function-declaration]
     #define XINET_PTON(a,b,c)   inet_pton((a),(b),(c))
```

and it seems like there is not an easy way to turn off the DTLS support if others building on Windows were to hit the same build issue?

@dalybrown the wolfssl-examples/dtls examples depend on some Linux style header includes. To test out the toolchains though I compiled the example server bundled with wolfSSL which has DTLS 1.3 support by doing the following:

With Cygwin to build libwolfssl
```
./configure --enable-dtls --enable-dtls13 --enable-tls13 CC=/cygdrive/c/GNATSTUDIO/gnat-x86_64-windows64-13.2.0-2/bin/gcc.exe LD=/cygdrive/c/GNATSTUDIO/gnat-x86_64-windows64-13.2.0-2/bin/ld.exe LIBS=-lws2_32 --disable-sys-ca-certs && make src/libwolfssl.la
```

In Windows native powershell

```
 C:\GNATSTUDIO\gnat-x86_64-windows64-13.2.0-2\bin\gcc.exe -I D:\work\wolfssl .\examples\server\server.c -L D:\work\wolfssl\src\.libs -lwolfssl -lws2_32
 mv a.exe src/.libs/
 cd src/.libs
 
PS D:\work\wolfssl\src\.libs> .\a.exe -h
server 5.7.0 NOTE: All files relative to wolfSSL home dir
-? <num>    Help, print this usage
            0: English, 1: Japanese
--help      Help, in English
-p <num>    Port to listen on, not 0, default 11111
-v <num>    SSL version [0-4], SSLv3(0) - TLS1.3(4)), default 3
-l <str>    Cipher suite list (: delimited)
-c <file>   Certificate file,           default ./certs/server-cert.pem
-k <file>   Key file,                   default ./certs/server-key.pem
-A <file>   Certificate Authority file, default ./certs/client-cert.pem
-R <file>   Create Ready file for external monitor default none
-D <file>   Diffie-Hellman Params file, default ./certs/dh2048.pem
-Z <num>    Minimum DH key bits,        default 1024
-d          Disable client cert check
-b          Bind to any interface instead of localhost only
-s          Use pre Shared keys
-u          Use UDP DTLS, add -v 2 for DTLSv1, -v 3 for DTLSv1.2 (default), -v 4 for DTLSv1.3
...
...
```

Testing the run time connection:

```
PS D:\work\wolfssl\src\.libs> .\a.exe -u -v 4 -d -b
SSL version is DTLSv1.3
SSL cipher suite is TLS_AES_128_GCM_SHA256
SSL curve name is SECP256R1
Client message: hello wolfssl!
```

My suspicion is that expanding the build with DTLS adds a dependency for some Windows library to link with for InetPton that needs accounted for.

**Review by JacobBarthelmeh — APPROVED** [review]
Accepting "as is", leaving the Windows build as a TODO. We can come back to the Windows build in a later update if needed. Thanks for all the hard work you've done with this and the extra testing!

**Comment by dalybrown** [comment]
Awesome - I have some ideas for refactoring of the library anyways that can be implemented as part of https://github.com/wolfSSL/wolfssl/pull/7303 that would address the Windows build issues (running configure as part of the pre-build actions, splitting the ada sources into multiple files based on capability, etc.).

**Pull request merged**
