### PR TITLE
AES for ARM32 without using crypto hardware instructions

### PR DESCRIPTION
**Pull request by SparkiDev**
# Description

AES-ECB, AES-CBC, AES-CTR, AES-GCM, AES-CCM
(ARM32, No NEON)

# Testing

Tested with QEMU and on Linaro board.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Comment by haydenroche5** [comment]
I get this error when building with `--enable-armasm` on my Raspberry Pi:

```
make -j5  all-recursive
make[1]: warning: -j5 forced in submake: resetting jobserver mode.
make[1]: Entering directory '/home/pi/wolfssl'
make[2]: Entering directory '/home/pi/wolfssl'
make[2]: warning: -j5 forced in submake: resetting jobserver mode.
  CPPAS    wolfcrypt/src/port/arm/src_libwolfssl_la-armv8-32-sha256-asm.lo
  CPPAS    wolfcrypt/src/port/arm/src_libwolfssl_la-armv8-32-sha512-asm.lo
  CC       wolfcrypt/benchmark/benchmark.o
  CC       wolfcrypt/src/src_libwolfssl_la-hmac.lo
  CC       wolfcrypt/src/src_libwolfssl_la-hash.lo
  CC       wolfcrypt/src/src_libwolfssl_la-cpuid.lo
  CC       wolfcrypt/src/src_libwolfssl_la-kdf.lo
  CC       wolfcrypt/src/src_libwolfssl_la-random.lo
  CC       wolfcrypt/src/src_libwolfssl_la-sha256.lo
  CC       wolfcrypt/src/port/arm/src_libwolfssl_la-armv8-sha256.lo
  CC       wolfcrypt/src/src_libwolfssl_la-rsa.lo
  CC       wolfcrypt/src/src_libwolfssl_la-sp_int.lo
  CC       wolfcrypt/src/src_libwolfssl_la-aes.lo
  CC       wolfcrypt/src/port/arm/src_libwolfssl_la-armv8-aes.lo
  CC       wolfcrypt/src/src_libwolfssl_la-sha.lo
  CC       wolfcrypt/src/port/arm/src_libwolfssl_la-armv8-sha512.lo
  CPPAS    wolfcrypt/src/port/arm/src_libwolfssl_la-armv8-sha512-asm.lo
  CC       wolfcrypt/src/src_libwolfssl_la-logging.lo
  CC       wolfcrypt/src/src_libwolfssl_la-wc_port.lo
  CC       wolfcrypt/src/src_libwolfssl_la-error.lo
  CC       wolfcrypt/src/src_libwolfssl_la-wc_encrypt.lo
  CC       wolfcrypt/src/src_libwolfssl_la-signature.lo
  CC       wolfcrypt/src/src_libwolfssl_la-wolfmath.lo
  CC       wolfcrypt/src/src_libwolfssl_la-memory.lo
  CC       wolfcrypt/src/src_libwolfssl_la-dh.lo
  CC       wolfcrypt/src/src_libwolfssl_la-asn.lo
  CC       wolfcrypt/src/src_libwolfssl_la-coding.lo
  CC       wolfcrypt/src/port/arm/src_libwolfssl_la-armv8-poly1305.lo
  CC       wolfcrypt/src/src_libwolfssl_la-poly1305.lo
  CC       wolfcrypt/src/src_libwolfssl_la-md5.lo
  CC       wolfcrypt/src/src_libwolfssl_la-pwdbased.lo
  CC       wolfcrypt/src/src_libwolfssl_la-pkcs12.lo
  CC       wolfcrypt/src/port/arm/src_libwolfssl_la-armv8-chacha.lo
  CC       wolfcrypt/src/src_libwolfssl_la-chacha20_poly1305.lo
  CC       wolfcrypt/src/src_libwolfssl_la-ecc.lo
/tmp/cc1tgIXA.s: Assembler messages:
/tmp/cc1tgIXA.s:241: Error: first transfer register must be even -- `ldrd r11,r10,[r14,#4*14]'
make[2]: *** [Makefile:6216: wolfcrypt/src/port/arm/src_libwolfssl_la-armv8-chacha.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/pi/wolfssl'
make[1]: *** [Makefile:7150: all-recursive] Error 1
make[1]: Leaving directory '/home/pi/wolfssl'
make: *** [Makefile:4222: all] Error 2
```

CPU specs:

```
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               3
Model name:          Cortex-A72
Stepping:            r0p3
CPU max MHz:         1500.0000
CPU min MHz:         600.0000
BogoMIPS:            108.00
Flags:               half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
```

**Comment by SparkiDev** [comment]
Fixed ldrd and strd usage.

**Comment by haydenroche5** [comment]
Getting the exact same error with the latest commit.

**Comment by SparkiDev** [comment]
I've fixed the actual report now.

Thanks,
Sean

**Comment by haydenroche5** [comment]
wolfcrypt/benchmark/benchmark shows an illegal instruction on my Raspberry Pi:

```
pi@raspberrypi:~/wolfssl $ libtool --mode=execute gdb wolfcrypt/benchmark/benchmark
GNU gdb (Raspbian 8.2.1-2) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/pi/wolfssl/wolfcrypt/benchmark/.libs/benchmark...done.
(gdb) r
Starting program: /home/pi/wolfssl/wolfcrypt/benchmark/.libs/benchmark 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
------------------------------------------------------------------------------
 wolfSSL version 5.5.1
------------------------------------------------------------------------------
wolfCrypt Benchmark (block bytes 1048576, min 1.0 sec each)

Program received signal SIGILL, Illegal instruction.
0xb6f4b674 in Sha256Final (hash=0xbeffee78 "|\227\377\266", sha256=0xbeffeea0) at wolfcrypt/src/port/arm/armv8-sha256.c:1140
1140        __asm__ volatile (
(gdb) where
#0  0xb6f4b674 in Sha256Final (hash=0xbeffee78 "|\227\377\266", sha256=0xbeffeea0) at wolfcrypt/src/port/arm/armv8-sha256.c:1140
#1  wc_Sha256Final (sha256=sha256@entry=0xbeffeea0, hash=hash@entry=0xbeffee78 "|\227\377\266") at wolfcrypt/src/port/arm/armv8-sha256.c:1481
#2  0xb6f4a2f8 in Hash_df (drbg=drbg@entry=0xbeffef70, out=out@entry=0xbeffef78 "", type=<optimized out>, type@entry=4 '\004', 
    inA=inA@entry=0xb6f9bc24 <seedB_data> "\246Z\320\363E\333N\016\377\350uâ\347\037B\307\022\235b\017\365\301\031\251\357U\360Q\205\340\373\205\201\371\061u\027'n\006\351`}\333\313\314.\323\341`\303[\231\363@\262b\202d\321u\020`\340\004]\243\203\377W\245}s\246sҸ\330\r\252\366\246\303Z\221\273Ey\327?\320\310\376\321\021\260\071\023\006\202\212\337\355R\217\001\201!\263\376\275\303C痸}\273c\333\023\063\336\331\321\354\341wϦ\267\037\350\253\035\244f$\355d\025\345\034\315\342\307ʆ⃙\016\352\353\221\022\004\025R\213\"\225\221\002\201\260-\324\061\364\311\367\004'\337\346+\212\216\350\361A\266\230\005f\343\277\343\300I\003\332Ԭ,ߟ\""..., inASz=inASz@entry=48, inB=0x0, inBSz=inBSz@entry=0, outSz=55) at wolfcrypt/src/random.c:418
#3  0xb6f4a3f4 in Hash_DRBG_Instantiate (drbg=drbg@entry=0xbeffef70, 
    seed=seed@entry=0xb6f9bc24 <seedB_data> "\246Z\320\363E\333N\016\377\350uâ\347\037B\307\022\235b\017\365\301\031\251\357U\360Q\205\340\373\205\201\371\061u\027'n\006\351`}\333\313\314.\323\341`\303[\231\363@\262b\202d\321u\020`\340\004]\243\203\377W\245}s\246sҸ\330\r\252\366\246\303Z\221\273Ey\327?\320\310\376\321\021\260\071\023\006\202\212\337\355R\217\001\201!\263\376\275\303C痸}\273c\333\023\063\336\331\321\354\341wϦ\267\037\350\253\035\244f$\355d\025\345\034\315\342\307ʆ⃙\016\352\353\221\022\004\025R\213\"\225\221\002\201\260-\324\061\364\311\367\004'\337\346+\212\216\350\361A\266\230\005f\343\277\343\300I\003\332Ԭ,ߟ\""..., seedSz=48, seedSz@entry=0, nonce=nonce@entry=0x0, nonceSz=nonceSz@entry=0, heap=0x0, heap@entry=0xbefff058, 
    devId=128) at wolfcrypt/src/random.c:744
#4  0xb6f4ab58 in wc_RNG_HealthTest_ex (reseed=reseed@entry=0, nonce=nonce@entry=0x0, nonceSz=nonceSz@entry=0, 
    seedA=seedA@entry=0xb6f9bc24 <seedB_data> "\246Z\320\363E\333N\016\377\350uâ\347\037B\307\022\235b\017\365\301\031\251\357U\360Q\205\340\373\205\201\371\061u\027'n\006\351`}\333\313\314.\323\341`\303[\231\363@\262b\202d\321u\020`\340\004]\243\203\377W\245}s\246sҸ\330\r\252\366\246\303Z\221\273Ey\327?\320\310\376\321\021\260\071\023\006\202\212\337\355R\217\001\201!\263\376\275\303C痸}\273c\333\023\063\336\331\321\354\341wϦ\267\037\350\253\035\244f$\355d\025\345\034\315\342\307ʆ⃙\016\352\353\221\022\004\025R\213\"\225\221\002\201\260-\324\061\364\311\367\004'\337\346+\212\216\350\361A\266\230\005f\343\277\343\300I\003\332Ԭ,ߟ\""..., seedASz=seedASz@entry=48, seedB=seedB@entry=0x0, seedBSz=seedBSz@entry=0, 
    output=output@entry=0xbefff058 "4\373\377\266", outputSz=128, outputSz@entry=0, heap=heap@entry=0x0, devId=devId@entry=-2) at wolfcrypt/src/random.c:1227
#5  0xb6f4ac54 in wc_RNG_HealthTest (reseed=reseed@entry=0, 
    seedA=seedA@entry=0xb6f9bc24 <seedB_data> "\246Z\320\363E\333N\016\377\350uâ\347\037B\307\022\235b\017\365\301\031\251\357U\360Q\205\340\373\205\201\371\061u\027'n\006\351`}\333\313\314.\323\341`\303[\231\363@\262b\202d\321u\020`\340\004]\243\203\377W\245}s\246sҸ\330\r\252\366\246\303Z\221\273Ey\327?\320\310\376\321\021\260\071\023\006\202\212\337\355R\217\001\201!\263\376\275\303C痸}\273c\333\023\063\336\331\321\354\341wϦ\267\037\350\253\035\244f$\355d\025\345\034\315\342\307ʆ⃙\016\352\353\221\022\004\025R\213\"\225\221\002\201\260-\324\061\364\311\367\004'\337\346+\212\216\350\361A\266\230\005f\343\277\343\300I\003\332Ԭ,ߟ\""..., seedASz=seedASz@entry=48, seedB=seedB@entry=0x0, seedBSz=seedBSz@entry=0, 
    output=output@entry=0xbefff058 "4\373\377\266", outputSz=outputSz@entry=128) at wolfcrypt/src/random.c:1186
#6  0xb6f4ad78 in wc_RNG_HealthTestLocal (reseed=0) at wolfcrypt/src/random.c:1395
#7  wc_RNG_HealthTestLocal (reseed=0) at wolfcrypt/src/random.c:1319
#8  _InitRng (rng=0xb6d434e8, nonce=nonce@entry=0x0, nonceSz=nonceSz@entry=0, heap=heap@entry=0x0, devId=-2) at wolfcrypt/src/random.c:874
#9  0xb6f4afb0 in wc_InitRng_ex (rng=<optimized out>, heap=heap@entry=0x0, devId=devId@entry=-2) at wolfcrypt/src/random.c:1008
#10 0x00014944 in benchmarks_do (args=0x0) at wolfcrypt/benchmark/benchmark.c:1860
#11 0x00014f60 in benchmark_test (args=0x0) at wolfcrypt/benchmark/benchmark.c:2782
#12 benchmark_test (args=0x0) at wolfcrypt/benchmark/benchmark.c:2722
#13 wolfcrypt_benchmark_main (argc=1, argv=<optimized out>) at wolfcrypt/benchmark/benchmark.c:8662
#14 0xb6dde718 in __libc_start_main (main=0xbefff294, argc=-1225715712, argv=0xb6dde718 <__libc_start_main+268>, init=<optimized out>, fini=0x156a0 <__libc_csu_fini>, 
    rtld_fini=0xb6fde4c4 <_dl_fini>, stack_end=0xbefff294) at libc-start.c:308
#15 0x00011830 in _start () at wolfcrypt/benchmark/benchmark.c:8446
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)
```

Config is `./configure CFLAGS="-g3" --enable-armasm`.

**Comment by SparkiDev** [comment]
I can't see the sha2 extensions included in the CPU specs flags.
--host=armv7a will disable hardware crypto

**Comment by haydenroche5** [comment]
No illegal instruction fault after adding `--host=armv7a` to configure. It seems like I shouldn't have to add that for it to work, though, right? Shouldn't configure.ac be "smart enough" to set things up properly? I'm not cross-compiling, if that's relevant. All building done on the Raspberry Pi itself.

**Comment by SparkiDev** [comment]
The default configuration assumes hardware crypto.
configure.ac can't tell what is supported by a CPU.
To check programmatically requires privileged instructions so we can't test at runtime.
Having said that, OpenSSL does use getauxval() that uses kernel info or sets up a signal handler for an illegal instruction and tries to use it.
Not going to implement this kind of behaviour in this pull request.

**Comment by haydenroche5** [comment]
Seeing a nice speedup!

Before:

```
------------------------------------------------------------------------------
 wolfSSL version 5.5.1
------------------------------------------------------------------------------
wolfCrypt Benchmark (block bytes 1048576, min 1.0 sec each)
AES-128-GCM-enc             30 MiB took 1.042 seconds,   28.788 MiB/s
AES-128-GCM-dec             35 MiB took 1.159 seconds,   30.208 MiB/s
AES-192-GCM-enc             30 MiB took 1.100 seconds,   27.261 MiB/s
AES-192-GCM-dec             30 MiB took 1.099 seconds,   27.294 MiB/s
AES-256-GCM-enc             25 MiB took 1.011 seconds,   24.737 MiB/s
AES-256-GCM-dec             25 MiB took 1.010 seconds,   24.757 MiB/s
GMAC Table 4-bit            75 MiB took 1.006 seconds,   74.523 MiB/s
Benchmark complete
```

After:

```
------------------------------------------------------------------------------
 wolfSSL version 5.5.1
------------------------------------------------------------------------------
wolfCrypt Benchmark (block bytes 1048576, min 1.0 sec each)
AES-128-GCM-enc             45 MiB took 1.101 seconds,   40.886 MiB/s
AES-128-GCM-dec             45 MiB took 1.060 seconds,   42.470 MiB/s
AES-192-GCM-enc             40 MiB took 1.027 seconds,   38.958 MiB/s
AES-192-GCM-dec             40 MiB took 1.026 seconds,   38.991 MiB/s
AES-256-GCM-enc             40 MiB took 1.111 seconds,   36.018 MiB/s
AES-256-GCM-dec             40 MiB took 1.110 seconds,   36.023 MiB/s
GMAC Table 4-bit            82 MiB took 1.004 seconds,   81.690 MiB/s
Benchmark complete
```

**Review by haydenroche5 — APPROVED** [review]

**Pull request merged**
