### PR TITLE
wolfSSL ESP Registry component publishing files

### PR DESCRIPTION
**Pull request by gojimmypi**
# Description

These files are not part of wolfSSL library and are only needed to publish  wolfSSL to the [Espressif ESP Registry](https://components.espressif.com/):

https://components.espressif.com/components/wolfssl/wolfssl

The staging site is at:

https://components-staging.espressif.com/components/gojimmypi/mywolfssl

Note that for the staging site, I have implemented user-specific namespace support in the install script (in my case: `gojimmypi` and detected with the `$USER` variable). Additionally, on the staging site components are renamed with a `my` prefix, to distinguish from production libraries. This allows multiple publishers to publish their own test components individually before using the single production `wolfssl` namespace and component names. This also aids in support identification if a customer is using experimental staging components.

Only Linux bash script is implemented at this time for publishing.

See the `README.md` for details. See also https://github.com/wolfSSL/wolfssh/issues/588 and https://github.com/wolfSSL/wolfMQTT/issues/352

The recent updates here include support for the staging site and passing a parameter as to the source code to install:

```bash
./wolfssl_component_publish.sh /mnt/c/workspace/wolfssl-master
```

See the `INSTALL.md` for files to edit for published version specification and other details.

Fixes zd# n/a

# Testing

How did you test? n/a

This is only a tool to publish wolfSSL. See in particular the `wolfssl_component_publish.sh` script.

The script is successful when wolfSSL is published and available at [components/wolfssl/wolfssl](https://components.espressif.com/components/wolfssl/wolfssl).

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Comment by JacobBarthelmeh** [comment]
```
In ./IDE/Espressif/component-manager/wolfssl_component_publish.sh line 78:
if [ -z "IDF_COMPONENT_API_TOKEN" ]; then
         ^---------------------^ SC2157 (error): Argument to -z is always false due to literal strings.
```

**Comment by gojimmypi** [comment]
I'm working on this, as well as the [wolfMQTT](https://github.com/wolfSSL/wolfMQTT/issues/352) and [wolfSSH](https://github.com/wolfSSL/wolfssh/issues/588) components concurrently.

**Comment by gojimmypi** [comment]
Hi @JacobBarthelmeh  - the files in this PR can be excluded from wolfSSL repo, as they are only used to publish to the Espressif ESP Registry. I'm seeing this check failure:

```
AUTOCONF NEW FILE DETECTOR FAILED!
Your pull request adds new files, but does not add them to include.am!
...
Please add your new files to an include.am file so that they get
included in the wolfSSL distribution when 'make dist' is run, thanks!
Build step 'Execute shell' marked build as failure
```

Would you prefer that I update the `include.am` and include them anyhow?

**Comment by JacobBarthelmeh** [comment]
Hi @gojimmypi, my thoughts are that there should not really be github hosted only files other than the .git* and expected files related with a github repository. If it is something added to the wolfSSL repository it likely should go in the wolfSSL bundle and could be included with EXTRA_DIST in include.am. Like with most things, there probably are some rare exceptions (i.e autogen.sh).

**Comment by gojimmypi** [comment]
Hi @JacobBarthelmeh - these files are not really "_github hosted only files_", as the publishing is done by a person from a local computer, not published from GitHub (although the automated git publishing is a interesting idea!).

For the time being, I've added the files to the EXTRA_DIST in `include.am`. Thank you.

**Comment by gojimmypi** [comment]
Jenkins retest this please.

**Comment by gojimmypi** [comment]
I'm revising the publishing & moving everything to scripts.

**Pull request closed without merging**
