### PR TITLE
Fix for `set1_curves_list` ignoring last character

### PR DESCRIPTION
**Pull request by anhu**
Fixes issue with `SSL_CTX_set1_curves_list` and `SSL_set1_curves_list` not checking the last character of the names variable provided.

### CODE REVIEW

**Comment by anhu** [comment]
Super simple one liner.

**Review by dgarske — CHANGES_REQUESTED** [review]
Thanks, this fix is great. Also noticed we do not check `names` for NULL. Also there is not unit test. I wrote one up here for you to add:

api.c:33290 (above `test_wolfSSL_set1_sigalgs_list`)

```
static void test_wolfSSL_set1_curves_list(void)
{
#if defined(OPENSSL_EXTRA) && defined(HAVE_ECC)
    SSL*     ssl;
    SSL_CTX* ctx;

#ifndef NO_WOLFSSL_SERVER
    AssertNotNull(ctx = SSL_CTX_new(wolfSSLv23_server_method()));
#else
    AssertNotNull(ctx = SSL_CTX_new(wolfSSLv23_client_method()));
#endif
    AssertTrue(SSL_CTX_use_certificate_file(ctx, svrCertFile,
               SSL_FILETYPE_PEM));
    AssertTrue(SSL_CTX_use_PrivateKey_file(ctx, svrKeyFile, SSL_FILETYPE_PEM));
    AssertNotNull(ssl = SSL_new(ctx));

    AssertIntEQ(SSL_CTX_set1_curves_list(ctx, NULL), WOLFSSL_FAILURE);
    AssertIntEQ(SSL_CTX_set1_curves_list(ctx, "P-25X"), WOLFSSL_FAILURE);
    AssertIntEQ(SSL_CTX_set1_curves_list(ctx, "P-256"), WOLFSSL_SUCCESS);

    AssertIntEQ(SSL_set1_curves_list(ssl, NULL), WOLFSSL_FAILURE);
    AssertIntEQ(SSL_set1_curves_list(ssl, "P-25X"), WOLFSSL_FAILURE);
    AssertIntEQ(SSL_set1_curves_list(ssl, "P-256"), WOLFSSL_SUCCESS);

    SSL_free(ssl);
    SSL_CTX_free(ctx);

    printf(resultFmt, passed);
#endif
}
```

**Comment by anhu** [comment]
We don't check `ctx ` for `NULL` either! Will fix that.

**Review by dgarske — APPROVED** [review]

**Comment by anhu** [comment]
oh my...such a small change cause build errors....investigating.....

**Review by ejohnstown — APPROVED** [review]

**Pull request merged**
