### PR TITLE
TLSX fixes (PR #951 rebased)

### PR DESCRIPTION
**Pull request by moisesguimaraes**
Hi @dgarske, I rebased PR 951 to remove some conflicts.

### CODE REVIEW

**Comment by dgarske** [comment]
Hi @moisesguimaraes,

Reviewed and tested. Looks good to me, but I am worried about the rare case where this might break existing TLS client behavior.

Would you please add a list of extensions and the behavior before and after when connecting to a server that sends the extension when its not in the client_hello.

As we discussed it sounds like some of the extensions were just ignored previously, so this change could break compatibility with some TLS servers that are always sending a TLS extension even if its not in the client hello. Also please update the user manual with that information and the `WOLFSSL_SKIP_UNSUPPORTED_EXTENSION` define.

Thanks!

**Comment by moisesguimaraes** [comment]
Hi @dgarske,

Here are some clarifications:

**RFC 5246, Section 7.2.2, page 33**

unsupported_extension
      sent by clients that receive an extended server hello containing
      an extension that they did not put in the corresponding client
      hello.  This message is always fatal.

**RFC 5246, Section 7.4.1.4, page 44**

   An extension type MUST NOT appear in the ServerHello unless the same
   extension type appeared in the corresponding ClientHello.  If a
   client receives an extension type in ServerHello that it did not
   request in the associated ClientHello, it MUST abort the handshake
   with an unsupported_extension fatal alert.

   Nonetheless, "server-oriented" extensions may be provided in the
   future within this framework.  Such an extension (say, of type x)
   would require the client to first send an extension of type x in a
   ClientHello with empty extension_data to indicate that it supports
   the extension type.  In this case, the client is offering the
   capability to understand the extension type, and the server is taking
   the client up on its offer.

**Behavior changes:**

ALPN:
 - was returning BUFFER_ERROR
 - now returns UNSUPPORTED_EXTENSION
 
SNI:
 - was returning BUFFER_ERROR
 - now returns UNSUPPORTED_EXTENSION

MFL:
 - was decreasing the fragment length
 - now returns UNSUPPORTED_EXTENSION

THMAC:
 - was truncating the HMAC (increasing security rist)
 - now returns UNSUPPORTED_EXTENSION

CSR (ocsp stapling):
 - was returning BUFFER_ERROR
 - now returns UNSUPPORTED_EXTENSION

CSR2 (ocsp stapling 2):
 - was returning BUFFER_ERROR
 - now returns UNSUPPORTED_EXTENSION

WOLFSSL_SKIP_UNSUPPORTED_EXTENSION:
  This define is actually dangerous as it silents all responses to extensions not requested, we're going against the RFC recommendations and letting the connection proceed instead of terminating it. I don't like having this on the docs so the users can have a easy way out that might harm them in the future.

**Comment by dgarske** [comment]
@moisesguimaraes : Thanks for those details. It looks like max fragment and trunc-hmac are the only two that will behave differently now. The skip define sounds like a bad idea to use all-together. Is there a good reason to have it in the code? Maybe it would better to have an "old" behavior option for the two extensions that are different?
@toddouska : what are your thoughts about this? David

**Comment by dgarske** [comment]
@moisesguimaraes : I talked with Todd and we agree. Will you remove the `WOLFSSL_SKIP_UNSUPPORTED_EXTENSION` logic and add a new define like `WOLFSSL_OLD_UNSUPPORTED_EXTENSION` to enable the "old" behavior in case anyone needs it. 

The old behavior being just for max fragment and trunc-hmac so they do it anyways like they did before. The returning UNSUPPORTED_EXTENSION is fine for the others in either case. Thanks!

**Comment by moisesguimaraes** [comment]
@dgarske: That's great, I don't like deviating from the RFC and this approach is less error prone. Thanks!

**Pull request merged**
