### PR TITLE
Fix for PQC enabled handshake

### PR DESCRIPTION
**Pull request by Frauschi**
Hi all,

When PQC Kyber support is enabled, incoming KeyShare messages are tested regarding the named group is a PQC Kyber group (pure or hybrid). The boundaries of this test are far too loose (large gap between the pure ones and the hybrid ones). This could result in failing handshakes in case a client uses GREASE (Generate Random Extensions And Sustain Extensibility), as with that, group numbers in the large gap are used.

The fix is just to make sure that the PQC test uses the two small boundaries of the PQC named groups.

The lower bound for the hybrid groups has also been updated to reflect the current OQS definition.

### CODE REVIEW

**Comment by anhu** [comment]
Ah, yes, the boundaries were too wide because we use to support other hybrid KEMs.  This was a left over artifact of older code.

**Comment by dgarske** [comment]
Okay to test

**Review by anhu — APPROVED** [review]
Thank you for your contribution!

**Review by dgarske — APPROVED** [review]

**Comment by dgarske** [comment]
Retest this please

**Comment by dgarske** [comment]
Retest this please

**Pull request merged**
