### PR TITLE
ParseCrl fix, GetPrivateKeySigSize moved from client only section and Coverity fixes.

### PR DESCRIPTION
**Pull request by SKlimaRA**

### CODE REVIEW

**Comment by kaleb-himes** [comment]
Jenkins, SklimaRA is an approved contributor. This PR is OK to test.

**Comment by kaleb-himes** [comment]
@SKlimaRA,

The Jenkins report reads:

```
./configure C_FLAGS="-fdebug-types-section -g1" --enable-jobserver=4 --enable-pkcallbacks --disable-asn --disable-ecc --disable-rsa --enable-psk

src/internal.c: In function 'GetPrivateKeySigSize':

src/internal.c:24055:29: error: 'Buffers' has no member named 'keyType'
```

**Comment by kaleb-himes** [comment]
In code freeze for the release will launch tests once the code freeze is lifted or if J.S. indicates he wants these to get into the release.

**Comment by SKlimaRA** [comment]
Hi,
would it be possible to start testing these changes again?
Thanks,
SK

**Comment by kaleb-himes** [comment]
@SKlimaRA,

Yes of course, my sincerest apologies this got lost!

Jenkins can you re-test this please?

- KH

**Comment by DKubasekRA** [comment]
Could you please prioritize this?

**Pull request merged**
