### PR TITLE
Assembly optimization for AES-NI, and AVX1 and AVX2

### PR DESCRIPTION
**Pull request by SparkiDev**
Unroll the loop for 8.
Use new optimized maths.
Fix SHA-384 to use SHA-512 assembly code.
Only perform CPU id check in one place.

### CODE REVIEW

**Comment by toddouska** [comment]
AES and SHA-384 improvements look good.  For some reason SHA-512 is about 10% slower for me with these changes:

current
SHA-384    325 MB took 1.007 seconds,  322.868 MB/s Cycles per byte =   7.37
SHA-512    480 MB took 1.007 seconds,  476.506 MB/s Cycles per byte =   4.99

this PR
SHA-384        460 MB took 1.001 seconds,  459.410 MB/s Cycles per byte =   5.18
SHA-512        425 MB took 1.006 seconds,  422.385 MB/s Cycles per byte =   5.63

Can you look into that please?

**Comment by SparkiDev** [comment]
I believe I've fixed the problem.
Removed extra call to function outside of file that wasn't needed.

**Comment by toddouska** [comment]
I'm still getting a 10% slowdown on SHA-512 vs current MASTER:

SHA-384        470 MB took 1.010 seconds,  465.230 MB/s Cycles per byte =   5.11
SHA-512        430 MB took 1.002 seconds,  429.230 MB/s Cycles per byte =   5.54

FYI, this is with AVX but not AVX2:
cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 70
model name	: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
stepping	: 1
microcode	: 0xf
cpu MHz		: 2492.555
cache size	: 6144 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc aperfmperf pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm ida arat epb pln pts dtherm fsgsbase smep

**Comment by dgarske** [comment]
Hi Sean,

GCC 7.1 error:
```
wolfcrypt/src/sha256.c: In function 'Sha256_SetTransform':
wolfcrypt/src/sha256.c:225:9: error: this 'else' clause does not guard... [-Werror=misleading-indentation]
         else
         ^~~~
wolfcrypt/src/sha256.c:227:38: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'else'
             Transform_p = Transform; return;
                                      ^~~~~~
```

With speedups:
```
SHA-384        340 MB took 1.006 seconds,  338.029 MB/s Cycles per byte =   7.32
SHA-512        345 MB took 1.004 seconds,  343.670 MB/s Cycles per byte =   7.20
```

Without (stock master):
```
SHA-384    295 MB took 1.010 seconds,  292.006 MB/s Cycles per byte =   8.47
SHA-512    285 MB took 1.003 seconds,  284.130 MB/s Cycles per byte =   8.71
```

```
sysctl -n machdep.cpu.brand_string
Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
```

David

**Comment by SparkiDev** [comment]
Fixed. Thanks David.

**Comment by toddouska** [comment]
David,

Please do the comparison I did.  --enable-intelmasm on MASTER vs this PR with respect to SHA-512.  You say with speedups and without and your SHA-512 numbers are faster so it looks like this isn't apples to apples.

**Comment by dgarske** [comment]
@SparkiDev : This was with `--enable-intelasm` only. The results on my Mac with master compared to this PR are not good for SHA-512. Also still getting GCC 7.1 build error (attached possible fix).
screen shot 2017-07-24 at 3 20 47 pm


./configure --enable-intelasm

**Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (MacBook Pro Retina 2002)**

Master be61d7f:
```
SHA-384    290 MB took 1.016 seconds,  285.522 MB/s Cycles per byte =   8.66
SHA-512    325 MB took 1.014 seconds,  320.622 MB/s Cycles per byte =   7.72
```

This PR:
```
SHA-384        295 MB took 1.013 seconds,  291.128 MB/s Cycles per byte =   8.50
SHA-512        300 MB took 1.000 seconds,  299.988 MB/s Cycles per byte =   8.25
```


**Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (AVX and AVX2)**
Master be61d7f:
```
SHA-384    365 MB took 1.007 seconds,  362.348 MB/s Cycles per byte =   9.45
SHA-512    495 MB took 1.009 seconds,  490.811 MB/s Cycles per byte =   6.98
```
This PR:
```
SHA-384        490 MB took 1.009 seconds,  485.411 MB/s Cycles per byte =   7.06
SHA-512        490 MB took 1.010 seconds,  485.318 MB/s Cycles per byte =   7.06
```

**Pull request merged**
