### PR TITLE
Revert "Refactor HAVE_PTHREAD and _POSIX_THREADS"

### PR DESCRIPTION
**Pull request by dgarske**
Reverts wolfSSL/wolfssl#6536

### CODE REVIEW

**Comment by dgarske** [comment]
There are too many downstream issues with this refactor, so reverting it for now.

**Comment by dgarske** [comment]
Looks like the "Windows FIPS Create Package" won't work with the upstream branch. Please ignore that failure.

```
Cloning into 'wolfssl'...
fatal: couldn't find remote ref revert-6536-pthread_gate
```

**Comment by dgarske** [comment]
Closing in favor of #6549

**Comment by gojimmypi** [comment]
I believe https://github.com/wolfSSL/wolfssl/pull/6549 should fix the problem without doing this full revert.

**Pull request closed without merging**
