### PR TITLE
Add assembly code for ARM and 64-bit ARM

### PR DESCRIPTION
**Pull request by SparkiDev**
Split out different implementations into separate file.
Turn on SP asm by configuring with: --enable-sp-asm
Changed small ASM code for ECC on x86_64 to be smaller and slower.

### CODE REVIEW

**Comment by dgarske** [comment]
Sean: I tested this PR on my Raspberry Pi 3 and had some make check errors. Seems to be around the TLS side ConfirmSignature for RSA.

This is a Cortex-A53: ARMv7 Processor rev 4 (v7l):
Instructions: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32.

```
./configure --enable-sp --enable-sp-asm && make check

PASS: scripts/external.test
FAIL: scripts/resume.test
PASS: scripts/openssl.test
PASS: scripts/tls-cert-fail.test
PASS: scripts/google.test
FAIL: testsuite/testsuite.test
./build-aux/test-driver: line 107:  5272 Aborted                 "$@" > $log_file 2>&1
FAIL: tests/unit.test

wolfSSL Entering ConfirmSignature
RsaUnPad error, bad formatting
wolfSSL Leaving ConfirmSignature, return -155
```

This works fine:
```
./configure --enable-sp && make check
```

David

**Comment by SparkiDev** [comment]
Fixed the div_word function and the armv7 should work now.

**Comment by toddouska** [comment]
David, please test changes and review.

**Comment by dgarske** [comment]
FYI: Benchmarks on the Raspberry Pi 3 for asymmetric operations. Very impressive!

SP and SP ASM
```
./configure --enable-ecc --enable-sp --enable-sp-asm && make && ./wolfcrypt/benchmark/benchmark
RSA     2048 public       1200 ops took 1.026 sec, avg 0.855 ms, 1169.184 ops/sec
RSA     2048 private       100 ops took 3.035 sec, avg 30.351 ms, 32.948 ops/sec
DH      2048 key gen        68 ops took 1.011 sec, avg 14.864 ms, 67.278 ops/sec
DH      2048 agree         100 ops took 1.508 sec, avg 15.078 ms, 66.324 ops/sec
ECC      256 key gen      2118 ops took 1.000 sec, avg 0.472 ms, 2117.319 ops/sec
ECDHE    256 agree         600 ops took 1.190 sec, avg 1.983 ms, 504.347 ops/sec
ECDSA    256 sign         1300 ops took 1.034 sec, avg 0.795 ms, 1257.200 ops/sec
ECDSA    256 verify        500 ops took 1.241 sec, avg 2.482 ms, 402.850 ops/sec
```

SP only

```
./configure --enable-ecc --enable-sp && make && ./wolfcrypt/benchmark/benchmark
RSA     2048 public        500 ops took 1.198 sec, avg 2.396 ms, 417.281 ops/sec
RSA     2048 private       100 ops took 8.013 sec, avg 80.131 ms, 12.480 ops/sec
DH      2048 key gen        28 ops took 1.010 sec, avg 36.074 ms, 27.721 ops/sec
DH      2048 agree         100 ops took 3.629 sec, avg 36.287 ms, 27.558 ops/sec
ECC      256 key gen       671 ops took 1.001 sec, avg 1.491 ms, 670.524 ops/sec
ECDHE    256 agree         200 ops took 1.232 sec, avg 6.158 ms, 162.380 ops/sec
ECDSA    256 sign          500 ops took 1.033 sec, avg 2.066 ms, 484.127 ops/sec
ECDSA    256 verify        200 ops took 1.465 sec, avg 7.323 ms, 136.561 ops/sec
```

No SP
```
./configure --enable-ecc && make && ./wolfcrypt/benchmark/benchmark
RSA     2048 public        200 ops took 1.187 sec, avg 5.937 ms, 168.436 ops/sec
RSA     2048 private       100 ops took 7.820 sec, avg 78.199 ms, 12.788 ops/sec
DH      2048 key gen        48 ops took 1.010 sec, avg 21.032 ms, 47.547 ops/sec
DH      2048 agree         100 ops took 2.556 sec, avg 25.557 ms, 39.128 ops/sec
ECC      256 key gen        36 ops took 1.010 sec, avg 28.067 ms, 35.629 ops/sec
ECDHE    256 agree         100 ops took 2.795 sec, avg 27.947 ms, 35.782 ops/sec
ECDSA    256 sign          100 ops took 2.838 sec, avg 28.383 ms, 35.233 ops/sec
ECDSA    256 verify        100 ops took 5.605 sec, avg 56.053 ms, 17.840 ops/sec
```

**Pull request merged**
