### PR TITLE
wolfcrypt Python wrapper

### PR DESCRIPTION
**Pull request by moisesguimaraes**

### CODE REVIEW

**Comment by dgarske** [comment]
Can you include a link somewhere for the documentation you did? http://moisesguimaraes.github.io/wolfcrypt-py/

**Comment by toddouska** [comment]
The commands:
pip install -r requirements-testing.txt
python setup.py install
tox

required sudo for me.  If that's required, the docs should reflect that, if not, the permissions should be fixed.

tox gave me an error about loading libwolfssl:

platform linux2 -- Python 2.7.6, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /home/toddouska/wolfssl/wrapper/python, inifile: 
collected 0 items / 3 errors 

==================================== ERRORS ====================================
____________________ ERROR collecting test/test_ciphers.py _____________________
test/test_ciphers.py:21: in <module>
    from wolfcrypt.ciphers import *
.tox/py27/local/lib/python2.7/site-packages/wolfcrypt/ciphers.py:20: in <module>
    from wolfcrypt._ffi   import ffi as _ffi
E   ImportError: libwolfssl.so.3: cannot open shared object file: No such file or directory


wolfSSL was installed with sudo make install and LD_LIBRARY_PATH points to the install at /usr/local/lib

Can you investigate this please?

**Comment by moisesguimaraes** [comment]
Hi Todd,

Using **sudo** with **pip** and **setup.py install** will depend on the way you use python. The standard python on Mac will require sudo, but usually developers use a separate python install to hack and don't mess with the system's python. In my machine I was able to drop the **sudo** since I started using python from **homebrew**.

I had a similar problem on a virtual machine:
E ImportError: libwolfssl.so.3: cannot open shared object file: No such file or directory

I was fixed with a **sudo ldconfig**.

Either way, I have to add some extra info in the build & install process.
Thanks for the feedback.

**Comment by moisesguimaraes** [comment]
Hi Todd,

I have updated the docs.

**Comment by toddouska** [comment]
1) I don't believe the python files will be build into the distribution via "make dist" or "make distcheck".  Please alter include.am(s) to include these files if that's the case.

2) This needs to work on a clean linux box, can make sure it does?  I get errors from tox about loading libwolfslsl.

**Comment by moisesguimaraes** [comment]
**1) I don't believe the python files will be build into the distribution via "make dist" or "make distcheck". Please alter include.am(s) to include these files if that's the case.**
    DONE

**2) This needs to work on a clean linux box, can make sure it does? I get errors from tox about loading libwolfssl.**
    DONE: I added more instructions on the README.rst file, the docs website is also up to date. Tested on a clean ubuntu64 box.

**Comment by toddouska** [comment]
Looks like you're missing at least .gitignore from include.am.  Can you verify all the files are there?

I'm still having problems with your exact build steps on linux with tox.  Can you have a few other wolfSSL developers test this and see what their results are?  Thanks.

**Comment by ejohnstown** [comment]
1. wolfcrypt source installation: should be "cd wolfssl/wrapper/python".
2. installing "requirements-testing.txt" needs to be sudo or the tox install fails.
3. when I run tox, it sprays errors. It is failing on editing files that are not editable, probably because I ran the tox install as sudo. If I run "sudo tox" the tests pass.

**Comment by moisesguimaraes** [comment]
@toddouska ,

After some tweaks in the installation process, @ejohnstown and @JacobBarthelmeh had success building and testing wolfcrypt for python in a linux box.

**Comment by JacobBarthelmeh** [comment]
Ran "make dist" then scp over to a 64 bit Ubuntu 14.0.4 virtual machine and executed the following commands

```
tar xvf wolfssl-3.9.1.tar.gz
cd wolfssl-3.9.1/wrapper/python
sudo apt-get install python3-dev
sudo apt-get install python-dev
sudo apt-get install python-pip
sudo apt-get install libffi-dev
python setup.py install
sudo -H pip install -r requirements-testing.txt
tox
```

and got the summary results

> ___________________________________ summary ____________________________________
  py27: commands succeeded
  py34: commands succeeded
SKIPPED:  py35: InterpreterNotFound: python3.5
  congratulations :)

**Comment by ejohnstown** [comment]
In the directions, you are setting up the test and running the test without the test configuration file as you get that from cloning the git repo which happens after testing.

**Comment by moisesguimaraes** [comment]
@ejohnstown ,

I fixed the order of "test / install" again. Now it is "download / test / install".

The use of **sudo** is peculiar to the machine. Normally it will require sudo for both **sudo -H pip install ...** and **sudo python setup.py install**. Using mac's default python installation I will have to use **sudo**, but if I install another instance of python with **homebrew**, then I can drop the **sudo**.

**Comment by toddouska** [comment]
Exact instructions did not work on clean linux install.  Cannot accept until it works smoothly for  >= 95/100 of people who test it.  Right now it's closer to 50% at best.

**Comment by moisesguimaraes** [comment]
What linux distro are you using @toddouska ?

**Comment by toddouska** [comment]
What does the distro have to do with making the user do 2 git clones on the same package?  Please clean it up, make it simple, and test it on a clean distort (of your choice) following the exact clean instructions.  Ideally this is a one or two step process (did you see the script comment).  Have at least 2 people independently verify they can get it to work on the first try following your exact instructions with no changes from you.

**Comment by moisesguimaraes** [comment]
ok

**Comment by kojo1** [comment]
>> adds --enable-Sha512

Thanks. Rest of the part regarding with the installation seems to work well.

**Comment by JacobBarthelmeh** [comment]
Tried on a clean Ubuntu 32 bit VM with most recent wrapper/python/README having enable-sha512 worked as expected and as instructions for Ubuntu showed.

**Comment by moisesguimaraes** [comment]
Hi Todd,

Both Jacob and Kojo had success following the instructions by the book on a clean linux machine. Could you please check again?

**Comment by ejohnstown** [comment]
In the README, could you add a section for the TOX testing? You have more robust testing than just a hash, I'd like to run that, too.

**Pull request merged**
