### PR TITLE
20241121-fixes

### PR DESCRIPTION
**Pull request by douzzer**
`wolfssl/wolfcrypt/error-crypt.h`, `wolfcrypt/src/error.c`: add `WC_FAILURE` ("wolfCrypt generic failure") with value `-1`, for traceable error return of `-1` in wolfCrypt.

`configure.ac`: add `OPENSSL_EXTRA` to `--enable-wolfsentry`.

`linuxkm/linuxkm_wc_port.h`, `linuxkm/module_hooks.c`, `wolfssl/ssl.h`: accommodate backward dependencies for `wolfSSL_X509_NAME_add_entry_by_NID`, `wolfSSL_X509_NAME_free`, and `wolfSSL_X509_NAME_new_ex`.

`linuxkm/lkcapi_glue.c`: if `CONFIG_CRYPTO_MANAGER`, assert match of `CONFIG_CRYPTO_FIPS` and `HAVE_FIPS`.

`src/ssl_crypto.c`, `wolfcrypt/src/wc_lms.c`, `wolfcrypt/src/wc_lms_impl.c`, `wolfcrypt/src/wc_xmss.c`, `wolfcrypt/test/test.c`: add casts for `XMALLOC()`s.

`src/ssl_crypto.c`: in `wolfSSL_AES_decrypt()`, fix gate for `wc_AesDecryptDirect()` return type.

`wolfcrypt/test/test.c`: smallstack refactor in `test_dilithium_decode_level()`.

`tests/api.c`: fix uninited vars in `test_wc_dilithium_der()`.

tested with `FIPS_DEV_BRANCH=local:20241121-WC_FAILURE-and-HAVE_EMBEDDED_AGENT wolfssl-multi-test.sh ... super-quick-check fips-140-3-v6-optest-acvp-sp-asm fips-140-3-ready-optest-acvp-sp-asm fips-140-3-dev-optest-acvp-sp-asm fips-140-3-dev-optest-acvp-sp-asm-trace-errcodes fips-140-3-dev-optest-acvp-sp-noasm fips-140-3-dev-optest-acvp-sp-asm-gcc-latest fips-140-3-dev-optest-acvp-sp-asm-gcc-latest-no-sha-1 fips-140-2-optest fips-140-2-openssl-all fips-140-3-pilot-all fips-140-3-pilot-optest-acvp-sp-asm fips-140-3-all linuxkm-all-fips-140-3 linuxkm-all-fips-140-3-dev-dyn-hash linuxkm-fips-dev-static-hash-intelasm-LKCAPI-insmod-crypto-fuzzer linuxkm-mainline-intelasm-sp-asm-pie-gcc-latest-insmod wolfssl-with-wolfsentry quantum-safe-wolfssl-all-noasm-stack-sizes`

### CODE REVIEW

**Comment by douzzer** [comment]
retest this please (python port test "test_ssl failed")

**Comment by douzzer** [comment]
Note python test failure is unrelated to this PR.

**Review by bigbrett — APPROVED** [review]
nice @douzzer, you beat me to those dilithium fixes - had the same ones queued up in a PR, I was just investigating a valgrind issue.

**Comment by dgarske** [comment]
FYI Test failure in on Python test. The PR Aidan and I did in https://github.com/wolfSSL/osp/pull/211 clearly didn't work. I'll reproduce locally and get another patch put up.

**Comment by douzzer** [comment]
@bigbrett yeah I had the definite feeling I was drag racing with you on those :stuck_out_tongue_winking_eye:

**Pull request merged**
