### PR TITLE
add brainpool benchmark

### PR DESCRIPTION
**Pull request by JacobBarthelmeh**

### CODE REVIEW

**Comment by SparkiDev** [comment]
Please change bench_eccMakeKey() as well.
That is where key generation is benchmarked and gives information about the performance of the raw scalar multiplication of the base.

Thanks,
Sean

**Comment by JacobBarthelmeh** [comment]
Great suggestion Sean. Added it in.

**Comment by dgarske** [comment]
@JacobBarthelmeh : The `--enable-all` also turns on Brainpool so all ECC benchmarks will use BP curves. Would it make more sense to allow using a curve id as a parameter for the benchmark app?

**Comment by JacobBarthelmeh** [comment]
Adding a curve ID as an argument to the benchmark app would be a nice addition! Am not sure if I should make those changes to this PR though for parsing in the additional argument -- maybe just leaving it as a future item to do because it is a little more involved with parsing the argument than this quick addition for demonstrating use of ECC with other curve ID's.

**Comment by toddouska** [comment]
I'd rather see the P curves be used if built in.  If Brainpool is built in those benchmarks should be run as well instead of the P curves.

**Comment by JacobBarthelmeh** [comment]
The behavior now is:

- If brainpool is compiled in then try to show benchmark of SECP256 + brainpool by default
- If -ecc-all is passed to benchmark app, then go through all curve ID's and benchmark each one

**Review by toddouska — APPROVED** [review]

**Pull request merged**
