### PR TITLE
preprocessor option to omit BIO API

### PR DESCRIPTION
**Pull request by gstrauss**
preprocessor option to omit BIO API with -DNO_BIO

Note: this pull request builds on #3098 and provides two additional commits to wrap BIO API in `#ifndef NO_BIO`.
Please review #3098 first.

### CODE REVIEW

**Comment by kaleb-himes** [comment]
@gstrauss,

Thank you so much for these proposed contributions. If it is not too much trouble could I have you email our team at "support [at] wolfssl [dot] com" with a reference to both PRs: #3115 and #3098?

To accept these changes as a commercial organization that licenses this software we will need to work to get you setup as an approved contributor through our legal department!

Warm Regards,

KH

**Comment by kaleb-himes** [comment]
@gstrauss, there have been some upstream changes that caused a merge conflict, can I ask those get addressed quickly so we can go ahead and launch the CI tests?

**Comment by gstrauss** [comment]
rebased onto tip of wolfssl master branch plus #3098 
Please review #3098 before this PR.  Thank you.

**Comment by kaleb-himes** [comment]
@gstrauss is an approved contributor. It is OK to test this PR.

**Comment by dgarske** [comment]
@gstrauss , 

We are seeing this error: 

```
src/ssl.c:43039:7: error: no previous prototype for 'wolfSSL_X509_get_ex_data' [-Werror=missing-prototypes]
 void *wolfSSL_X509_get_ex_data(X509 *x509, int idx)
       ^
src/ssl.c:43053:5: error: no previous prototype for 'wolfSSL_X509_set_ex_data' [-Werror=missing-prototypes]
 int wolfSSL_X509_set_ex_data(X509 *x509, int idx, void *data)
     ^
```

Looks like the header ssl.h will need to be updated to match:

```
#if ((defined(OPENSSL_EXTRA) || defined(OPENSSL_EXTRA_X509_SMALL)) && defined(HAVE_EX_DATA)) || \
     defined(FORTRESS) || defined(WOLFSSL_WPAS_SMALL)
```

Also we'll have merge conflicts once #3098 gets merged.

Thanks,
David Garske, wolfSSL

**Comment by gstrauss** [comment]
I'll rebase and will update this once #3098 lands.  Thanks.

**Comment by dgarske** [comment]
Hi @gstrauss , I pushed a fix for `wolfSSL_CTX_check_private_key` to your branch. I don't think there is an OCSP failure. Sometimes our testing rig gets overwhelmed with randomized port conflict.

**Comment by douzzer** [comment]
Superseded by PR #3474, which includes all constituent commits.

**Pull request closed without merging**
