### PR TITLE
adds OCSP Responder extKeyUsage validation

### PR DESCRIPTION
**Pull request by moisesguimaraes**
Fixes Zendesk ticket #2622

### CODE REVIEW

**Comment by moisesguimaraes** [comment]
RFC 2560 - 4.2.2.2  Authorized Responders
   The key that signs a certificate’s status information need not be the
   same key that signed the certificate. It is necessary however to
   ensure that the entity signing this information is authorized to do
   so.  Therefore, a certificate’s issuer MUST either sign the OCSP
   responses itself or it MUST explicitly designate this authority to
   another entity.  OCSP signing delegation SHALL be designated by the
   inclusion of id-kp-OCSPSigning in an extendedKeyUsage certificate
   extension included in the OCSP response signer’s certificate.  This
   certificate MUST be issued directly by the CA that issued the
   certificate in question.
   id-kp-OCSPSigning OBJECT IDENTIFIER ::= {id-kp 9}
   Systems or applications that rely on OCSP responses MUST be capable
   of detecting and enforcing use of the id-ad-ocspSigning value as
   described above. They MAY provide a means of locally configuring one
   or more OCSP signing authorities, and specifying the set of CAs for
   which each signing authority is trusted. They MUST reject the
   response if the certificate required to validate the signature on the
   response fails to meet at least one of the following criteria:
   1. Matches a local configuration of OCSP signing authority for the
   certificate in question; or
   2. Is the certificate of the CA that issued the certificate in
   question; or
   3. Includes a value of id-ad-ocspSigning in an ExtendedKeyUsage
   extension and is issued by the CA that issued the certificate in
   question."

**Comment by kaleb-himes** [comment]
Per our discussion. Will merge when Jenkins has finished testing.

Thank you Moises for the time and effort spent on these changes!

**Comment by kaleb-himes** [comment]
Holding on request:

"hold merge please, I will add a check for the CA cert as well" -Moisés Guimarães

**Comment by kaleb-himes** [comment]
retest this please jenkins

**Comment by kaleb-himes** [comment]
Needs rebased with master

**Comment by dgarske** [comment]
@moisesguimaraes : I did a rebase and force push to resolve the conflicts. The customer is using this change and has validated it. Is this new `EXTKEYUSE_OCSP_SIGN` check good as-is or should it have an `#ifdef` around it so its not on by default? I'd like to help get this PR finished up, so let me know. Thanks.

**Comment by moisesguimaraes** [comment]
@dgarske, this one is good as it is. You can merge it.

**Comment by dgarske** [comment]
Passing to Todd for final review/merge.

**Comment by toddouska** [comment]
We need a way to disable this new error as we have no way of knowing whether this is 100% compatible with existing use cases.

**Comment by dgarske** [comment]
@toddouska : Added new `WOLFSSL_NO_OCSP_EXTKEYUSE_OCSP_SIGN` option to provide backwards compatibility option. Ticket 2622.

**Pull request merged**
