### PR TITLE
Fix linking against hostapd with LTO

### PR DESCRIPTION
**Pull request by hauke**
When running LTO on wolfssl the ecc_map() function is removed from the
binary by GCC 8.4.0. This function is used by multiple functions from
the crypto_wolfssl.c implementation of hostapd master.

Fixes: 780e8a4619b6 ("Fixes for building `--enable-wpas=small` with WPA Supplicant v2.7.")
Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>

### CODE REVIEW

**Comment by hauke** [comment]
@dgarske Could you please have a look at this change. Your commit 780e8a4 broke it for us.

**Comment by dgarske** [comment]
Hi @hauke,

Thanks for alerting us to the options that were missed in the `--enable-wpas=small` cleanups changes in https://github.com/wolfSSL/wolfssl/pull/3289

I don't see a contributor agreement on file for you. Please send an email to support@wolfssl.com referencing this PR and we can start the process.

Thanks,
David Garske, wolfSSL

**Comment by dgarske** [comment]
@hauke sorry for the delay on this. Thank you @lechner for bringing it to my attention. I understand a contributor agreement will not work, so I will treat this as bug report. We will implement a fix to revert a portion of these changes in a new PR. Closing in favor of in-house fix.

**Comment by dgarske** [comment]
https://github.com/wolfSSL/wolfssl/pull/3753

**Comment by hauke** [comment]
Hi @dgarske Sorry for answering so late.

I do not like Contributor license agreements much and I would appreciative if you consider this a bug report and create an own pull request with such a fix.

**Pull request closed without merging**
