### PR TITLE
Basic editor config to avoid some whitespace issues

### PR DESCRIPTION
**Pull request by mitchcapper**
to take care of those pesky people who use tabs as tab stops.

### CODE REVIEW

**Comment by dgarske** [comment]
Hi @mitchcapper , thank you for being an approved contributor. Can you tell use more about this (https://editorconfig.org) and how it can be used/tested? If we are going to include this in our repo we'll need some help understanding it.

Thanks,
David Garske, wolfSSL

**Comment by mitchcapper** [comment]
Well the website may do that best but editorconfig has been around for a good while.  Visual studio added support in VS 2017 and several other editors supported it long before that.  At this point virtually all editors support it ( https://editorconfig.org/#pre-installed )

It is a fairly standardized way of setting format specifications to be enforced by the code editor.  Generally the settings in editorconfig will override any user preferences in most editors.  This means if I use tabs for tab but open a project that has an editorconfig that uses spaces and 2 spaces per tab  it will override my preferences for that project.

Most editors allow you to setup pretty advanced editorconfig settings through custom prefixed extensions (almost all VS code settings can be set this way, you can even export them to an editorconfig from within VS). 

This however just sets some minimal standard preferences it seems this project has.  Editor config settings are hierarchical and can be specified per file type as well.  Using the root=true means editorconfig files above the project root are not searched. 

Helps fix some common formatting / linting issues users may cause without them having to do anything.  Many projects have editorconfig files ie:

- https://github.com/microsoft/terminal/blob/main/.editorconfig
- https://github.com/microsoft/vscode/blob/main/.editorconfig
- https://github.com/php/php-src/blob/master/.editorconfig
- https://github.com/git/git/blob/master/.editorconfig
- https://github.com/x64dbg/x64dbg/blob/development/.editorconfig
- https://github.com/twbs/bootstrap/blob/main/.editorconfig
- https://github.com/sandboxie-plus/Sandboxie/blob/master/.editorconfig
- https://github.com/postgres/postgres/blob/master/.editorconfig

As for testing set your settings to something different than what is in the file, open up a file that has that editorconfig in its directory or higher and its settings should override.

**Comment by dgarske** [comment]
Okay to test

**Review by dgarske — APPROVED** [review]
Thank you! I like it. Contributor agreement on file

**Pull request merged**
