### PR TITLE
testsuite time check on Windows system and fix dh_test if statement

### PR DESCRIPTION
**Pull request by JacobBarthelmeh**
Fix for running the testsuite on a Windows system and add brackets on if statement.

### CODE REVIEW

**Comment by JacobBarthelmeh** [comment]
retest this please Jenkins

**Comment by toddouska** [comment]
Retest this

**Comment by toddouska** [comment]
Retest this jenkins

**Comment by toddouska** [comment]
retest this Jenkins

**Comment by toddouska** [comment]
retest this please Jenkins

**Pull request merged**
