### PR TITLE
Disallow SHA-2 ciphersuites from TLS 1.0 and 1.1 handshakes

### PR DESCRIPTION
**Pull request by SparkiDev**

### CODE REVIEW

**Comment by SparkiDev** [comment]
Changed to allow TLS 1.2 cipher suites to be used with TLS 1.0 and TLS 1.1 with the define:
  WOLFSSL_OLDTLS_SHA2_CIPHERSUITES

**Comment by SparkiDev** [comment]
retest this please

**Comment by toddouska** [comment]
The new .conf files are not in an .am file for proper distribution.  This has to be checked, I suggest 2 or 3 times, because this can't be missed.

**Comment by SparkiDev** [comment]
Put conf files into tests/include.am and squashed commits.

**Pull request merged**
