### PR TITLE
option to use test.h without gettimeofday

### PR DESCRIPTION
**Pull request by JacobBarthelmeh**
add reset param and use same user current_time macro from benchmark

### CODE REVIEW

**Comment by toddouska** [comment]
It looks like this will work on TI-RTOS, was TI-RTOS tested?

**Comment by JacobBarthelmeh** [comment]
Build of wolfssl.aem4f library was tested but not a runtime test with an APP including wolfssl/test.h.

**Comment by JacobBarthelmeh** [comment]
Reverted having TIRTOS current_time take a parameter. TIRTOS use of wolfssl/test.h and compiling example server/client might require a separate pull request.

**Comment by toddouska** [comment]
Thanks!

**Pull request merged**
