### PR TITLE
Create workflow

### PR DESCRIPTION
**Pull request by j4qfrost**
Is this of interest?

### CODE REVIEW

**Comment by dgarske** [comment]
Hi @j4qfrost , 

Thank you for the contribution. Looks like this add Action -> Workflow testing for a few platforms? 
We already use Jenkins CI integration. I will discuss with the team and see if its something we would like to add support for. Feel free to send an email to support@wolfssl.com referencing this PR to tell us a bit more about your project and if you'd like to be setup as a contributor.

Thanks,
David Garske, wolfSSL

**Comment by dgarske** [comment]
Hi @j4qfrost , we've internally done this work by @ejohnstown and will opt to use those changes.

**Comment by j4qfrost** [comment]
Cool, is there also work done for wolfssh as well? I have that working my fork.

**Comment by ejohnstown** [comment]
We haven't set one up for wolfSSH yet. I'd love to see it.

**Pull request closed without merging**
