### PR TITLE
actions: Build wolfSSL in seperate job

### PR DESCRIPTION
**Pull request by julek-wolfssl**

### CODE REVIEW

**Comment by bandi13** [comment]
Should we have a consistent naming for the artifacts across workflows? Maybe the artifact name should contain the workflow that generated it. Also, maybe we want to use the `github.run_id` or `github.sha` in the name?

**Comment by julek-wolfssl** [comment]
From what I understand from the docs, the artifacts are only visible within the same workflow. The issue is that all of our workflows are called from `main.yml` which I think counts as one workflow. We just need to have a unique artifact name so I think including the workflow name in the artifact should be enough.

**Comment by bandi13** [comment]
Jenkins retest this please

**Comment by julek-wolfssl** [comment]
@bandi13 What is failing in the Jenkins tests here?

**Comment by julek-wolfssl** [comment]
@JacobBarthelmeh can we get this merged despite the Jenkins failures? They are irrelevant to this PR and this PR can speed up the GH actions considerably.

**Review by JacobBarthelmeh — APPROVED** [review]

**Pull request merged**
