### PR TITLE
Support for custom ECC curves and math lib updates

### PR DESCRIPTION
**Pull request by dgarske**
ECC changes to support custom curves. Added new "WOLFSSL_CUSTOM_CURVES" option to support non-standard ECC curves in ecc_is_point and ecc_projective_dbl_point. Refactor to load and pass curve "a" parameter down through ECC functions. Relocated mp_submod and added mp_addmod. Refactor to pass mp variable directly (not pointer) for montgomery variable. Fix in mp_jacobi to also handle case of a == 0. Cleanup of *_ecc_mulmod and wc_ecc_make_key_ex error handling. Cleanup of ecc_map for handling normal, fast and alt_ecc math for optimization of performance and allowing reduced ecc_size.

Updated the naming for the ECC curve sets. Additional comments for each curve parameter.

Math updates from libtom. Fixes in mp_read_radix for to include char 36 and clear the destination before checks. Fix to clear tmp value on fp_sub_d and fp_add_d. Fixes in assembly for x86-32 INNERMUL, PPC32 INNERMUL and PROPCARRY and x86-64 SQRADD. Added mp_isneg. Refactor of mp_iszero, mp_iseven, mp_isodd and mp_isneg to check using MP_YES or MP_NO. Changed fp_read_unsigned_bin "b" arg to const. Removal of the "register" on stack variables to let compiler determine best optimization.

### CODE REVIEW

**Comment by dgarske** [comment]
Jenkins please tests again. It had error trying to talk to windows slave.

**Comment by toddouska** [comment]
Going to wait for a clean night on Jenkins with the latest math changes before merging this.

**Comment by toddouska** [comment]
Looks good but with jenkins stable and release pending I'll wait until post release to merge.

**Comment by dgarske** [comment]
Hey @toddouska, I made a few enhancements in a commit this morning. Added a new configure option "--enable-ecccustcurves". Exposed/add API's that allow using a "const ecc_set_type* dp" that's not in the "ecc_sets" list. Added custom curve test/example using BRAINPOOL256R1 curve. This allows use of custom curves along side SSL/TLS. Relates to ticket 2001.

**Comment by toddouska** [comment]
Thanks David!

**Pull request merged**
