### PR TITLE
Fix for stack and heap measurements of a 32-bit build

### PR DESCRIPTION
**Pull request by tmael**
# Description

Improve stack and heap measurements of a 32-bit build

This PR corrects 32-bit build errors on a 64-bit machine.

`./configure CPPFLAGS=-m32 LDFLAGS=-m32 --enable-singlethreaded --enable-stacksize=verbose --enable-trackmemory=verbose --enable-memory && make`

```
./wolfssl/test.h:3123:46: error: passing argument 3 of ‘pthread_create’ from incompatible pointer type [-Werror=incompatible-pointer-types]
 3123 |     ret = pthread_create(&threadId, &myAttr, (thread_func)debug_stack_size_verbose_shim, (void *)&shim_args);
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                              |
      |                                              THREAD_RETURN (*)(void *) {aka unsigned int (*)(void *)}

...
./wolfssl/test.h:3066:12: error: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘ssize_t’ {aka ‘int’} [-Werror=format=]
 3066 |     printf("    relative stack peak usage = %ld bytes\n", HWM);  \
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~
      |                                                           |
      |                                                           ssize_t {aka int}


./wolfssl/test.h:3069:16: error: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘int’ [-Werror=format=]
 3069 |         printf("    relative stack usage at %s L%d exceeds designated max %ld bytes.\n", __FILE__, __LINE__, (ssize_t)(max)); \
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                      ~~~~~~~~~~~~~~
      |                                                                                                              |
      |                                                                                                              int

wolfcrypt/test/test.c:76:12: error: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘ssize_t’ {aka ‘const int’} [-Werror=format=]
   76 |     printf("    relative heap peak usage: %ld alloc%s, %ld bytes\n",    \
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   77 |            _rha,                                                        \
      |            ~~~~
      |            |
      |            ssize_t {aka const int}
```

# Testing
`./configure CPPFLAGS=-m32 LDFLAGS=-m32 --enable-singlethreaded --enable-stacksize=verbose --enable-trackmemory=verbose --enable-memory && make`
`./configure --enable-singlethreaded --enable-stacksize=verbose --enable-trackmemory=verbose --enable-memory && make`
`./configure CC=clang CPPFLAGS=-m32 LDFLAGS=-m32 --enable-singlethreaded --enable-stacksize=verbose --enable-trackmemory=verbose --enable-memory --disable-asm && make`

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Review by dgarske — APPROVED** [review]

**Review by douzzer — CHANGES_REQUESTED** [review]
doesn't build yet -- one stray error in testsuite.c:
```
In file included from ./wolfssl/wolfcrypt/asn_public.h:34,
                 from ./wolfssl/ssl.h:35,
                 from testsuite/testsuite.c:29:
testsuite/testsuite.c: In function ‘main’:
./wolfssl/wolfcrypt/types.h:1186:39: error: returning ‘void *’ from a function with return type ‘int’ makes integer from pointer without a cast [-Werror=int-conversion]
 1186 |         #define EXIT_TEST(ret) return (THREAD_RETURN)((size_t)(ret))
      |                                       ^
testsuite/testsuite.c:634:5: note: in expansion of macro ‘EXIT_TEST’
  634 |     EXIT_TEST(EXIT_SUCCESS);
      |     ^~~~~~~~~
```

also, can you leave the formats as `%ld` and cast to `long int`, rather, than change the formats and cast to `int`?  unnecessarily risking integer truncation is a pet peeve of mine -- though obviously not likely to happen here.

**Comment by tmael** [comment]
@douzzer, Good catch! Interesting, CC=clang doesn't build but CC=gcc does.

**Comment by tmael** [comment]
@douzzer,  This build should succeed now:
`./configure CC=clang CPPFLAGS=-m32 LDFLAGS=-m32 --enable-singlethreaded --enable-stacksize=verbose --enable-trackmemory=verbose --enable-memory --disable-fastmath && make`

without the `--disable-fastmath`, I'm seeing another unrelated issue
```
wolfcrypt/src/tfm.c:3225:11: error: inline assembly requires more registers than available
          SQRADD2(*tmpx++, *tmpy--);
          ^
./wolfcrypt/src/asm.c:712:6: note: expanded from macro 'SQRADD2'
     "movl  %3,%%eax     \n\t"                            \
     ^
1 error generated.

```

**Review by douzzer — APPROVED** [review]
works for me.  nice improvement.

btw, the 32 bit build wins with or without `--enable-singlethreaded`, but the 64 bit build loses with `--enable-singlethreaded` around pthreads stuff.  I wonder how the 32 bit build is working `--enable-singlethreaded`, given that the stack instrumentation mechanism leverages pthreads.

**Comment by douzzer** [comment]
btw the `-Wint-conversion` was from a late-model gcc, can't remember now which it was but probably gcc-12.

I did my final check-over using gcc-13 btw.

**Pull request merged**
