### PR TITLE
Coverity fixes

### PR DESCRIPTION
**Pull request by embhorn**
Remaining issues in wolfcrypt and examples are resolved in this PR.

### CODE REVIEW

**Comment by embhorn** [comment]
Thanks. I am addressing all the test related defects in Coverity now. I will commit those changes today and then this PR should be complete.

**Comment by embhorn** [comment]
There are two remaining issues that I wanted to get some team input on.
CID 185023
CID 185132
Both affect wolfcrypt/src/asn.c and have similar problem reports. My analysis for 185132 was:

> "der->akid" is created with size MAX_KID_SIZE (45), while "cert->akid" is created with size CTC_MAX_AKID_SIZE (32). It seems like these should be created using the same size define. Otherwise there should be a conditional that prevents accessing this buffer out-of-bounds.

**Comment by dgarske** [comment]
Hey Eric, I investigated this issue with difference between `MAX_KID_SZ` and `CTC_MAX_SKID_SIZE` as well for a previous Coverity scan. I believe the MAX_KID_SZ accounts for some additional bytes. See `SetSKID`. With the previous fix I implemented checks to prevent overrun. If you are able to find a way to resolve this better that would be great.

Here are some previous fixes in that area.
https://github.com/wolfSSL/wolfssl/pull/886/files#diff-43a13479890e70352967043045d1f2ceR7934
https://github.com/wolfSSL/wolfssl/pull/883/files#diff-43a13479890e70352967043045d1f2ceR7924

**Comment by embhorn** [comment]
There are two more issues that I marked as "Fix Required".
CID 185009 for which my comment was:

> This needs some more input from other members of the team. It does appear that the SHA512 case will write 64 bytes of data into the 32 byte hash variable.

...and CID 185113 in which I mentioned:

> Definitely a problem, but I prefer to get some feedback on how to proceed. Is "UNKNOWN" a valid protocol version? If so, there could be a 7th protocol entry for each state/mode combination. Otherwise simply returning NULL seems like a good solution for an invalid protocol version.

**Pull request merged**
