### PR TITLE
Changes to date

### PR DESCRIPTION
**Pull request by jrblixt**
Made changes to the date of last version release.

### CODE REVIEW

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by JacobBarthelmeh** [comment]
Test this please Jenkins

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by JacobBarthelmeh** [comment]
Thanks for updating the date.

**Pull request merged**
