### PR TITLE
systemCaDirs for Android

### PR DESCRIPTION
**Pull request by depler**
systemCaDirs for Android

### CODE REVIEW

**Comment by dgarske** [comment]
Hi @depler thank you for this PR! Are you planning to make additional code contributions? Can you tell us more about your project? To get setup with a contributor agreement please email us at support@wolfssl.com.

**Comment by depler** [comment]
Hi! So far I use WolfSSL in my pet project: https://github.com/depler/transmission-android. I am not a professional in security related code and not going to contribute much, just adding missing platform.

**Comment by dgarske** [comment]
Hi @depler , thank you for the information on your project. We will treat this as a feature request and put up a pull request soon.

**Comment by depler** [comment]
Yes, I can confirm that. There is only one path used in Android for CA path `/system/etc/security/cacerts`

**Pull request closed without merging**
