### PR TITLE
Update arduino script to reflect includes of inline files

### PR DESCRIPTION
**Pull request by kaleb-himes**

### CODE REVIEW

**Comment by k-zhai** [comment]
So that solves the issue with evp.c, but another error arises:

Documents/Arduino/libraries/wolfssl/wolfcrypt/src/evp.c:35:35: fatal error: wolfssl/openssl/ecdsa.h: No such file or directory

**Comment by k-zhai** [comment]
I fixed the issue by adding the below to ```wolfssl-arduino.sh```

```
    #copy files from openssl
    mkdir ./wolfSSL/wolfssl/openssl
    cp ../../wolfssl/openssl/* ./wolfSSL/wolfssl/openssl
```

**Comment by kaleb-himes** [comment]
@k-zhai,

Thank you so much for the feedback. Implemented the change to pull in OpenSSL headers also!

Cheers,

KH

**Comment by kaleb-himes** [comment]
retest this please.

**Pull request merged**
