### PR TITLE
Fix for FIPS ready with openssl compat

### PR DESCRIPTION
**Pull request by dgarske**
Fix for `./configure --enable-fips=ready --enable-opensslextra`.

### CODE REVIEW

**Review by kaleb-himes — CHANGES_REQUESTED** [review]
David, I know I didn't mention opensslall and pkcs7 but for the sake of adding these to the regression system:

--enable-fips=ready --enable-opensslextra
--enable-fips=ready --enable-opensslall
--enable-fips=ready --enable-pkcs7

--enable-fips=ready --enable-opensslextra --enable-pkcs7
--enable-fips=ready --enable-opensslall --enable-pkcs7

Can I sneak a few more changes into this PR? Here's a patch to make it easy!

[opensslall_pkcs7.patch.txt](https://github.com/wolfSSL/wolfssl/files/5498127/opensslall_pkcs7.patch.txt)

**Comment by kaleb-himes** [comment]
Addresses failures from release 4.5.0, relates to https://github.com/wolfSSL/testing/pull/170

**Comment by cconlon** [comment]
Note that Kojo has a similar PR up in https://github.com/wolfSSL/wolfssl/pull/3450

**Review by dgarske — COMMENTED** [review]
Approved. Assigning to John for final.

**Review by ejohnstown — APPROVED** [review]

**Review by kaleb-himes — APPROVED** [review]

**Pull request merged**
