### PR TITLE
20240404-fips-VERSION3

### PR DESCRIPTION
**Pull request by douzzer**
add "VERSION3" variants of macros for testing and computing FIPS versions.

cherry-picked from 87b1aeff75 in #7295, with the `test/test.c` change snipped out.

tested with `wolfssl-multi-test.sh ... check-source-text cppcheck-all clang-tidy-fips-140-3-dev-all`

note I was the original author of the FIPS version macro changes so it's appropriate for @kaleb-himes to review them despite his being the author of #7295.  oh what a twisted tale we weave :slightly_smiling_face:

### CODE REVIEW

**Comment by kaleb-himes** [comment]
Could I request the following change please? Very subtle update got missed by the singular cherry-pick:

```
diff --git a/kh-pr.txt b/dz-pr.txt
index e031af0..13ce07d 100644
--- a/wolfssl/wolfcrypt/settings.h
+++ b/wolfssl/wolfcrypt/settings.h
@@ -5,9 +5,9 @@
                                   WOLFSSL_MAKE_FIPS_VERSION3(major, minor, 0)
 
 #if !defined(HAVE_FIPS)
-    #define WOLFSSL_FIPS_VERSION_CODE WOLFSSL_MAKE_FIPS_VERSION3(0,0,0)
+    #define WOLFSSL_FIPS_VERSION_CODE WOLFSSL_MAKE_FIPS_VERSION(0,0)
 #elif !defined(HAVE_FIPS_VERSION)
-    #define WOLFSSL_FIPS_VERSION_CODE WOLFSSL_MAKE_FIPS_VERSION3(1,0,0)
+    #define WOLFSSL_FIPS_VERSION_CODE WOLFSSL_MAKE_FIPS_VERSION(1,0)
 #elif !defined(HAVE_FIPS_VERSION_MINOR)
     #define WOLFSSL_FIPS_VERSION_CODE \
             WOLFSSL_MAKE_FIPS_VERSION3(HAVE_FIPS_VERSION,0,0)
```

**Review by kaleb-himes — CHANGES_REQUESTED** [review]
Very minor update request that was added in a later update if you would be so kind sir.

**Comment by douzzer** [comment]
applied that patch.  also noticed and fixed a bug introduced in the incumbent `FIPS_VERSION_{LT,LE,EQ,GE,GT}` macros .

**Review by kaleb-himes — APPROVED** [review]
Changes look good to the eye, gotta break will do a quick sanity test in the AM and merge if all is checking out!

**Pull request merged**
