### PR TITLE
update oid value for secp160r1

### PR DESCRIPTION
**Pull request by JacobBarthelmeh**
Update OID value for secp160r1 based on OID repository.

### CODE REVIEW

**Comment by dgarske** [comment]
Confirmed,secp160r1 OID should be 8. Will merge after Jenkins is done. Thanks Jacob for finding these!

**Comment by ejohnstown** [comment]
The Ecc_Sum value for ECC_160R1 also needs to be updated to 178.

(We use the sums of the raw OIDs as a shorthand in the code so we can do word32 compares instead of memcmps.)

**Comment by dgarske** [comment]
Received email from @ejohnstown saying:
"The Ecc_Sum value for ECC_160R1 also needs to be updated to 178.

(We use the sums of the raw OIDs as a shorthand in the code so we can do word32 compares instead of memcmps.)"

@JacobBarthelmeh its in asn.h line 247. The ECC_160R1 value should be 178 (43+129+4+0+2). Since the value is currently 184 it was already wrong. I confirmed the others are correct.

**Comment by JacobBarthelmeh** [comment]
It was different for previous with 2 but using 8 as the last value it is correct as is. (43+129+4+0+8) is 184.

**Comment by dgarske** [comment]
You are right. The correct value is 184, which it already is. Merging it into master. Thanks!!

**Comment by ejohnstown** [comment]
(I posted that comment late at night and deleted it when I realized the value for the constant in the code was correct.)

**Pull request merged**
