### PR TITLE
Ensure that i2d APIs for public keys gives appropriate data.

### PR DESCRIPTION
**Pull request by anhu**
# Description
Fixes ZD15563

# Testing
make check and ran against reproducer. 

 - [x] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Comment by anhu** [comment]
Conceptually, the PR is correct, but the if statements need to be refactored into switch...case statements in order to satisfy various features being enabled/disabled.

**Review by SparkiDev — CHANGES_REQUESTED** [review]
No need to create an RsaKey or ecc_key.
The rsa and ecc fields are populated already.

**Comment by anhu** [comment]
> No need to create an RsaKey or ecc_key. The rsa and ecc fields are populated already.

But those are of type `WOLFSSL_RSA` and `WOLFSSL_EC_KEY`  respectively.  I don't know how to get the DER from those types.

**Comment by SparkiDev** [comment]
wolfSSL_i2d_RSAPublicKey()
No API currently for WOLFSSL_EC_KEY.

**Comment by anhu** [comment]
Hi @SparkiDev , 
calling `wolfSSL_i2d_RSAPublicKey()` would require `--enable-keygen`.  Not sure if that is desirable?

**Review by SparkiDev — APPROVED** [review]

**Review by dgarske — APPROVED** [review]

**Comment by dgarske** [comment]
```./configure --disable-ecc --enable-rsa --enable-tls13 --enable-opensslextra && make
...
make[2]: warning: -j17 forced in submake: resetting jobserver mode.
src/ssl.c: In function ‘wolfSSL_i2d_PublicKey’:
src/ssl.c:22965:12: error: unused variable ‘inOutIdx’ [-Werror=unused-variable]
22965 |     word32 inOutIdx = 0;
      |            ^~~~~~~~
src/ssl.c:22960:20: error: unused variable ‘pub_der’ [-Werror=unused-variable]
22960 |     unsigned char *pub_der = NULL;
      |                    ^~~~~~~
src/ssl.c:22959:12: error: unused variable ‘local_derSz’ [-Werror=unused-variable]
22959 |     word32 local_derSz = 0;
      |            ^~~~~~~~~~~
src/ssl.c:22958:20: error: unused variable ‘local_der’ [-Werror=unused-variable]
22958 |     unsigned char *local_der = NULL;
      |                    ^~~~~~~~~```

**Comment by anhu** [comment]
Squashed and ready for merge.  @SparkiDev , if all tests pass, please merge.

**Comment by dgarske** [comment]
Retest this please

**Comment by anhu** [comment]
Retest this please

**Pull request merged**
