### PR TITLE
Remove automatically generated file wolfssl.pc

### PR DESCRIPTION
**Pull request by danielinux**
The file `support/wolfssl.pc` is automatically generated by make, and it should not be part of the wolfssl repository, thus ignored as it used to be with `support/cyassl.pc`.

### CODE REVIEW

**Comment by cconlon** [comment]
Test this please Jenkins

**Comment by cconlon** [comment]
Please resolve conflicts, thanks!

**Comment by danielinux** [comment]
Hello @cconlon - thanks for considering this.

I have just rebased my commit on latest master. This is fairly trivial change, removing one (automatically generated) file and adding it to .gitignore.

Can you please verify this?

**Comment by dgarske** [comment]
Verified this change is valid and `support/wolfssl.pc` should not be in the git repository. I've noticed this as well when building with `./configure --prefix=[non/default/location]`. Daniele has contrib agreement in place. Thanks @danielinux.

**Pull request merged**
