### PR TITLE
Add tvos target to the xcode project

### PR DESCRIPTION
**Pull request by tmpduarte**

### CODE REVIEW

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by JacobBarthelmeh** [comment]
Hi tmpduarte,
Thank you for opening the pull request. Can you provide us with some information about the project being worked on with it? We are carful with licensing and testing of additions to the base wolfSSL code. Is the email listed on the commit a good one for sending a contributor agreement form to be signed? If it is not a good email we can be contacted at info@wolfssl.com, using the subject line "Contributor Agreement".

Regards,
Jacob

**Comment by tmpduarte** [comment]
Hi Jacob,
yes the email on the commit is my personal email so you can send the "Contributor Agreement" to it.

We are using wolfssl on [Cyberfables](https://itunes.apple.com/en/app/id1073545875?mt=8). Currently we only have the iOS version available but we are working on an Apple TV version, hence my pull request to "Add tvos target to the xcode project".

cheers,
Tiago

**Comment by JacobBarthelmeh** [comment]
Thank you Tiago,

Received the "Contributor Agreement" and will keep you posted on review of code.

Regards,
Jacob

~ test this please Jenkins

**Comment by JacobBarthelmeh** [comment]
Hi Tiago,

Confirmed the project builds with XCode, am looking into a couple of warnings about unused functions in misc.c that came up for me with the build though.

Regards,
Jacob

**Pull request merged**
