### PR TITLE
Fix for the AVX implemetation of Poly1305

### PR DESCRIPTION
**Pull request by SparkiDev**
Need one more multiple of r (0..6 instead of 0..5)

### CODE REVIEW

**Comment by dgarske** [comment]
Passing this over to Kaleb to validate with the test script he built. Code changes look good.

**Comment by JacobBarthelmeh** [comment]
Thanks, can confirm that commit 3b351fd resolved Clang build for me.

**Comment by kaleb-himes** [comment]
I can confirm clang issue no longer reported.
I can confirm all test cases that previously failed are now passing.

**Comment by kaleb-himes** [comment]
Thanks Sean!

**Pull request merged**
