### PR TITLE
AES RISC-V 64-bit ASM: ECB/CBC/CTR/GCM/CCM

### PR DESCRIPTION
**Pull request by SparkiDev**
# Description

Add implementations of AES for ECB/CBC/CTR/GCM/CCM for RISC-V using assembly.
Assembly with standard/scalar cryptography/vector cryptographt instructions.

# Testing

./configure --enable-all --enable-riscv-asm

# Checklist

 - [x] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Comment by dgarske** [comment]
@SparkiDev I've got a few RISC-V targets here now, so I will try this on actual HW.

**Review by dgarske — CHANGES_REQUESTED** [review]
./configure --enable-all --enable-riscv-asm

```
wolfcrypt/src/aes.c: In function '_AesXtsHelper':
wolfcrypt/src/aes.c:12631:16: error: implicit declaration of function '_AesEcbEncrypt'; did you mean 'wc_AesEcbEncrypt'? [-Werror=implicit-function-declaration]
12631 |         return _AesEcbEncrypt(aes, out, out, totalSz);
      |                ^~~~~~~~~~~~~~
      |                wc_AesEcbEncrypt
wolfcrypt/src/aes.c:12631:16: error: nested extern declaration of '_AesEcbEncrypt' [-Werror=nested-externs]
wolfcrypt/src/aes.c:12634:16: error: implicit declaration of function '_AesEcbDecrypt'; did you mean 'wc_AesEcbDecrypt'? [-Werror=implicit-function-declaration]
12634 |         return _AesEcbDecrypt(aes, out, out, totalSz);
      |                ^~~~~~~~~~~~~~
      |                wc_AesEcbDecrypt
wolfcrypt/src/aes.c:12634:16: error: nested extern declaration of '_AesEcbDecrypt' [-Werror=nested-externs]
```

**Comment by dgarske** [comment]
HiFive Unleashed at 1.4GHz
The new asm is like 50 times faster

```
./configure --enable-riscv-asm && make

root@HiFiveU:~/wolfssl-riscv# ./wolfcrypt/benchmark/benchmark -aes-cbc -aes-gcm------------------------------------------------------------------------------
 wolfSSL version 5.7.0
------------------------------------------------------------------------------
Math:   Multi-Precision: Wolf(SP) word-size=64 bits=3072 sp_int.c
wolfCrypt Benchmark (block bytes 1048576, min 1.0 sec each)
AES-128-CBC-enc             20 MiB took 1.076 seconds,   18.588 MiB/s
AES-128-CBC-dec             20 MiB took 1.083 seconds,   18.473 MiB/s
AES-192-CBC-enc             20 MiB took 1.245 seconds,   16.062 MiB/s
AES-192-CBC-dec             20 MiB took 1.246 seconds,   16.047 MiB/s
AES-256-CBC-enc             15 MiB took 1.057 seconds,   14.189 MiB/s
AES-256-CBC-dec             15 MiB took 1.055 seconds,   14.212 MiB/s
AES-128-GCM-enc             15 MiB took 1.300 seconds,   11.543 MiB/s
AES-128-GCM-dec             15 MiB took 1.300 seconds,   11.535 MiB/s
AES-192-GCM-enc             15 MiB took 1.425 seconds,   10.526 MiB/s
AES-192-GCM-dec             15 MiB took 1.425 seconds,   10.523 MiB/s
AES-256-GCM-enc             10 MiB took 1.032 seconds,    9.687 MiB/s
AES-256-GCM-dec             10 MiB took 1.032 seconds,    9.691 MiB/s
GMAC Table 4-bit            31 MiB took 1.025 seconds,   30.251 MiB/s
Benchmark complete
```

On master 

```
./configure —enable-all && make

root@HiFiveU:~/wolfssl# ./wolfcrypt/benchmark/benchmark -aes-cbc -aes-gcm
------------------------------------------------------------------------------
 wolfSSL version 5.7.0
------------------------------------------------------------------------------
Math:   Multi-Precision: Wolf(SP) word-size=64 bits=4096 sp_int.c
wolfCrypt Benchmark (block bytes 1048576, min 1.0 sec each)
AES-128-CBC-enc              5 MiB took 12.798 seconds,    0.391 MiB/s
AES-128-CBC-dec              5 MiB took 12.672 seconds,    0.395 MiB/s
AES-192-CBC-enc              5 MiB took 15.301 seconds,    0.327 MiB/s
AES-192-CBC-dec              5 MiB took 15.181 seconds,    0.329 MiB/s
AES-256-CBC-enc              5 MiB took 17.820 seconds,    0.281 MiB/s
AES-256-CBC-dec              5 MiB took 17.669 seconds,    0.283 MiB/s
AES-128-GCM-enc              5 MiB took 12.870 seconds,    0.388 MiB/s
AES-128-GCM-dec              5 MiB took 12.870 seconds,    0.388 MiB/s
AES-192-GCM-enc              5 MiB took 15.375 seconds,    0.325 MiB/s
AES-192-GCM-dec              5 MiB took 15.376 seconds,    0.325 MiB/s
AES-256-GCM-enc              5 MiB took 17.878 seconds,    0.280 MiB/s
AES-256-GCM-dec              5 MiB took 17.896 seconds,    0.279 MiB/s
AES-128-GCM-STREAM-enc       5 MiB took 12.878 seconds,    0.388 MiB/s
AES-128-GCM-STREAM-dec       5 MiB took 12.878 seconds,    0.388 MiB/s
AES-192-GCM-STREAM-enc       5 MiB took 15.379 seconds,    0.325 MiB/s
AES-192-GCM-STREAM-dec       5 MiB took 15.385 seconds,    0.325 MiB/s
AES-256-GCM-STREAM-enc       5 MiB took 17.881 seconds,    0.280 MiB/s
AES-256-GCM-STREAM-dec       5 MiB took 17.888 seconds,    0.280 MiB/s
GMAC Table 4-bit            30 MiB took 1.006 seconds,   29.831 MiB/s
Benchmark complete
```

**Comment by dgarske** [comment]
> ./configure --enable-all --enable-riscv-asm
> 
> ```
> wolfcrypt/src/aes.c: In function '_AesXtsHelper':
> wolfcrypt/src/aes.c:12631:16: error: implicit declaration of function '_AesEcbEncrypt'; did you mean 'wc_AesEcbEncrypt'? [-Werror=implicit-function-declaration]
> 12631 |         return _AesEcbEncrypt(aes, out, out, totalSz);
>       |                ^~~~~~~~~~~~~~
>       |                wc_AesEcbEncrypt
> wolfcrypt/src/aes.c:12631:16: error: nested extern declaration of '_AesEcbEncrypt' [-Werror=nested-externs]
> wolfcrypt/src/aes.c:12634:16: error: implicit declaration of function '_AesEcbDecrypt'; did you mean 'wc_AesEcbDecrypt'? [-Werror=implicit-function-declaration]
> 12634 |         return _AesEcbDecrypt(aes, out, out, totalSz);
>       |                ^~~~~~~~~~~~~~
>       |                wc_AesEcbDecrypt
> wolfcrypt/src/aes.c:12634:16: error: nested extern declaration of '_AesEcbDecrypt' [-Werror=nested-externs]
> ```

@SparkiDev  says AES XTS is not yet support with RISC-V ASM. Note: I tried to use `./configure --enable-all --disable-aesxtx --enable-riscv-asm` but that didn't work. We normally support a way to disable a specific option with all. Sean please review.

**Comment by dgarske** [comment]
@SparkiDev is this RISC-V ASM PR ready for merge? I can’t tell if you are planning to push anything else to it.

**Comment by SparkiDev** [comment]
Fixed --enable-all to work.

**Comment by SparkiDev** [comment]
retest this please

**Review by dgarske — APPROVED** [review]

**Comment by gojimmypi** [comment]
@dgarske - question on the benchmarks fix data size vs fixed time:

In  the `master` and `riscv_aes_asm` branch you [ran](https://github.com/wolfSSL/wolfssl/pull/7569#issuecomment-2132248155) these commands, respectively:

```
# before, on master
./configure —enable-all
```
vs

```
# after, with ASM Optimization
./configure --enable-all --enable-riscv-asm
```

Then for comparison your ran this for both:
```
./wolfcrypt/benchmark/benchmark -aes-cbc -aes-gcm
```

The output on `master` took a fixed 5MB chunk of data and timed the completion: in this example 12.798 seconds:

```
AES-128-CBC-enc              5 MiB took 12.798 seconds,    0.391 MiB/s
```

The output on  `riscv_aes_asm` completed as soon as reasonable after a fixed one second duration and determined the amount of data processed:

```
AES-128-CBC-enc             20 MiB took 1.076 seconds,   18.588 MiB/s
```

Why the difference in fixed data size vs fixed time? 

Additionally, perhaps just nit-picky, but curious: it appears there was also difference in `bits` size generated. `bits=4096`:

```
# master
Math:   Multi-Precision: Wolf(SP) word-size=64 bits=4096 sp_int.c
```
vs `bits=3072`

```
# ASM
Math:   Multi-Precision: Wolf(SP) word-size=64 bits=3072 sp_int.c
```


It appears that `./configure --enable-all --enable-riscv-asm` produces different `user_settings.h`  than `./configure —enable-all` affecting more than just assembly optimization.  Perhaps it should be consistent, at least for the benchmark configuration? I'm also left wondering for a real apples-to-apples if master was set to `bits=3072` whether there would be a performance difference?

In any case - that's an astonishing performance boost by @SparkiDev :)

**Comment by SparkiDev** [comment]
The size of data processed is the number of 1048576 byte (=1MB) buffers encrypted/decrypted.
We do a minimum number of buffers regardless of platform but no less than for 1 second.

I have no idea why the number of bits in SP changed though.

**Pull request merged**
