### PR TITLE
WIP: Added AES-XTS mode to the OpenSSL compatibility layer

### PR DESCRIPTION
**Pull request by victork1996**
Added support for AES XTS mode in the OpenSSL compatibility layer.

About testing this feature, I tested it on my private project and it works, however I would like to add tests to this repo as well and I would like your guidance on where to add them and what exactly to test for.

Thanks!

### CODE REVIEW

**Comment by dgarske** [comment]
OK to test. Victor has signed contributor agreement on file.

**Comment by dgarske** [comment]
Hi Victor,

Testing reports:

```
1 src/ssl.c:13674:17: error: implicit declaration of function 'wc_AesXtsSetInternalTweakValue' [-Werror=implicit-function-declaration]
--
2 src/ssl.c:13674:17: error: nested extern declaration of 'wc_AesXtsSetInternalTweakValue' [-Werror=nested-externs]
```

David

**Comment by JacobBarthelmeh** [comment]
Hi Victor,

In regards to adding test cases:

For tests we often add them either to tests/api.c or to wolfcrypt/test/test.c. In this case adding a new function to tests/api.c would be good. If adding it, the block of function calls at https://github.com/wolfSSL/wolfssl/blob/master/tests/api.c#L24377 would be a good location, which is a grouping of most compatibility layer tests in that test suite. Each test has macro guards on when it should run and a print of the test name followed by result, an example of the print of test case would be here https://github.com/wolfSSL/wolfssl/blob/master/tests/api.c#L3916. Inside the function follow the Assert patterns for checking return values. An example would be AssertNotNull(...) for checking that something is not NULL. After it has been added "./tests/unit.test" should output the name of the test and pass/fail result.

For test cases a basic start would be expected result test, expected failure case, multiple AES block size test, small input test, null input sanity check tests. With the compatibly layer function also check padding if applicable in comparison to how the OpenSSL version pads. Having that test in tests/api.c and when --enable-all is used will run it through our memory checking and address sanitize tests when Jenkins tests the pull request.

Regards,
Jacob

**Comment by victork1996** [comment]
Hi, before adding new unittests, I'm trying to compile the existing tests but it seems that the tests directory isn't a part of the solution (I'm working with visual studio on windows). Do you compile the tests on windows? And if so, how do you do it? 

Thanks.

**Comment by JacobBarthelmeh** [comment]
Hi Victor,

Sorry for the delay in response. The tests on Windows goes through wolfcrypt/test/test.c only when running the testsuite project. To run the API unit tests a Unix type system would be needed like Cygwin or the Ubuntu terminal emulator thing that Windows has.

~Jacob

**Comment by bgermann** [comment]
#2775 contains XTS as well.

**Comment by bgermann** [comment]
... which just got merged. I think you can close this PR.

**Comment by kaleb-himes** [comment]
@bgermann,

Thank you for pointing out the overlap! @victork1996 we are closing this PR in lieu of PR #2775. Thank you again for the proposed solution and for working with @JacobBarthelmeh and @dgarske on this one.

Regards,

K

**Pull request closed without merging**
