### PR TITLE
`a` and `key` were not being freed => leak in `PrintPubKeyEC`

### PR DESCRIPTION
**Pull request by julek-wolfssl**

### CODE REVIEW

**Comment by kaleb-himes** [comment]
Juliusz,

In the original report there were 5 leaks, 4 in evp.c and 1 in asn.c.
The 4 in evp.c have been fixed, however the asn.c leak remains. Should this last remaining leak be assigned to another party or could this also be addressed in this PR?

```
=================================================================
==5662==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x7ff3d1735f90 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xedf90)
    #1 0x55f4aaf15283 in wolfSSL_Malloc wolfcrypt/src/memory.c:147
    #2 0x55f4aaf14ab5 in wc_bigint_alloc wolfcrypt/src/wolfmath.c:274
    #3 0x55f4aaf14bae in wc_bigint_from_unsigned_bin wolfcrypt/src/wolfmath.c:296
    #4 0x55f4aaf184fd in GetInt wolfcrypt/src/asn.c:3079
    #5 0x55f4ab05317f in wolfSSL_ASN1_INTEGER_to_BN src/ssl.c:51900
    #6 0x55f4ab022548 in wolfSSL_ASN1_INTEGER_get src/ssl.c:27902
    #7 0x55f4aaea4d63 in test_wolfSSL_ASN1_INTEGER_get_set tests/api.c:48720
    #8 0x55f4aaeb04ec in ApiTest tests/api.c:52101
    #9 0x55f4aaddf13a in unit_test tests/unit.c:129
    #10 0x55f4aaddf107 in main tests/unit.c:43
    #11 0x7ff3d0edab96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

SUMMARY: AddressSanitizer: 1 byte(s) leaked in 1 allocation(s).
```

**Review by kaleb-himes — CHANGES_REQUESTED** [review]
Tenative: Request that last leak in the report also be fixed, unless the final leak should be assigned to another to look into.

**Comment by julek-wolfssl** [comment]
Whoops. Valgrind stopped reporting leaks so I didn't notice the last one. I'll fix it as part of this pr. Thanks @kaleb-himes for being diligent

**Comment by julek-wolfssl** [comment]
@kaleb-himes fixed the additional leak in the latest commit. Passing back to you.

**Review by kaleb-himes — APPROVED** [review]
All checks are passing, thank you so much @julek-wolfssl! Excellent work!

**Pull request merged**
