### PR TITLE
Improve liboqs integration

### PR DESCRIPTION
**Pull request by Frauschi**
Hi everybody,

this PR improves the integration of liboqs, focussing on two key aspects.

First, I added PQC support for the Zephyr port using liboqs by adding the necessary files to the `CMakeLists.txt` for the Zephyr module. The integration of liboqs as an additional Zephyr module is currently based on a [liboqs fork of mine](https://github.com/Frauschi/liboqs), which I am trying to upstream (see [https://github.com/open-quantum-safe/liboqs/pull/1621](https://github.com/open-quantum-safe/liboqs/pull/1621)).

Furthermore, I added support for proper random number generation from within liboqs using the WolfSSL interface. Before, random data is either obtained from OpenSSL, from `/dev/urandom`, or using the `get_entropy()` method, depending on the build configuration of liboqs. With the proposed changes, we use the `OQS_randombytes_custom_algorithm()` interface to provide a custom RNG method for liboqs. Using a custom method, we can obtain RNG data from WolfSSL. I further added support in different places to use the correct RNG, which is provided in the related context as arguments. In case no RNG is provided by the wrapping context, a new default RNG object is used. As we switch the RNG object to use during runtime, I had to protect the interface with a mutex. 

I placed the new liboqs related code in new header and source files, which are located in the new `wolfCrypt/port/liboqs` directory. The files are added both to the Make and CMake build infrastructure. However, I'm not sure if this is the right place for these files, to be honest.

 I look forward to your feedback!
 
 Kind regards,
 Tobi

### CODE REVIEW

**Comment by Frauschi** [comment]
As https://github.com/open-quantum-safe/liboqs/pull/1621 is merged now, `liboqs` has official Zephyr support. Therefore, it should be safe to use the module from within the WolfSSL Zephyr port without relying on my fork of the library.

**Comment by douzzer** [comment]
@Frauschi  that's good news -- thanks for the update.  This PR is working its way through our review+testing process and we'll keep you posted.

**Comment by anhu** [comment]
Hi @Frauschi !! 
First of all, thank you so much for this change. 

May I ask why you need to wolfSSL's rng facility?  Is it something particular about Zephyr? 

Warm regards, Anthony

**Comment by Frauschi** [comment]
> May I ask why you need to wolfSSL's rng facility? Is it something particular about Zephyr?

Hi @anhu,

The integration of the WolfSSL RNG facility is not directly related to Zephyr. The embedded nature of Zephyr and the hardware platforms it runs on merely increases the need for proper high quality random data, especially as the default random sources of liboqs aren‘t available in embedded environments. Hence, we needed a coupling between liboqs and WolfSSL for our Zephyr platforms anyways. In this context, I thought that a well defined interface between both libraries regarding random data would also benefit other environments like Linux (we also have Linux platforms in our research project) and ease software development. 
Furthermore, we are able to use the crypto callback API of WolfSSL to integrate external TRNGs into our platforms using a well defined interface, which will also propergate down to liboqs without additional work or complexity.

**Comment by anhu** [comment]
Thank you @Frauschi !!  That is an excellent explanation.

I've looked over your changes and they look good to me from a general perspective. I was the original author of most of the code you have touched.  Back to @douzzer for general code review.

**Review by anhu — APPROVED** [review]

**Review by douzzer — APPROVED** [review]
LGTM

There was a trivial rebase conflict in `wc_port.c` that I've fixed to unblock merge.

Oh, and your choice of `wolfcrypt/src/port/` for the liboqs-specific files is consistent with our previous decision to put the `af_alg/`, `aria/`, `devcrypto/`, and `kcapi` implementations there.

**Comment by Frauschi** [comment]
Thanks for the feedback and also for the rebase 😄 I‘m happy that this is merged 😄

**Pull request merged**
