### PR TITLE
Eliminate the recursion in "WOLFSSL_BUFFER".

### LINKED ISSUE #2451: Recursion in "WOLFSSL_BUFFER" leads to buffer overrun on Arduino.
There is a recursion in "WOLFSSL_BUFFER", line 281, "wolfcrypt\src\logging.c". It would lead to buffer overrun when being run on MCU which has limited stack size. Theoretically, any recursion should be eliminated in production code.

### PR DESCRIPTION
**Pull request by jim-king-2000**
Fix #2451 .
Turn the recursion into loop.

### CODE REVIEW

**Comment by dgarske** [comment]
Hi jim-king-2000,

Thanks for this excellent patch for eliminating the recursive function call. This happens to be the only one left in our library. This function is only for debugging and only when printing buffers. We would love to accept, but require a signed contributor agreement. To receive a form please email us at support@wolfssl.com and reference this pull request.

Thanks,
David Garske, wolfSSL

**Comment by jim-king-2000** [comment]
Hi @dgarske , I encountered a crash when I had debugged wolfssl on Arduino because of this recursion. So I fixed it on local and finally I decided to share the fix to everyone who would port wolfssl to MCU. Why we need a signed agreement? Why not just take it? Or can you copy my change into your own PR so that I'm NOT the very contributor?

**Comment by dgarske** [comment]
Hi @jim-king-2000 , if you are unwilling to do the contribution agreement we can implement our own fix to eliminate the recursive call on this function. I'll put together a new PR today and post reference to it here and close this.

**Comment by dgarske** [comment]
Closing in favor of https://github.com/wolfSSL/wolfssl/pull/2460

**Pull request closed without merging**
