### PR TITLE
SP int: get rsavfy and rsapub working again

### PR DESCRIPTION
**Pull request by SparkiDev**
Fixes:

```
./configure --enable-cryptonly --enable-rsavfy --enable-sp --disable-ecc --disable-dh --disable-pkcs12  && make
./configure --enable-cryptonly --enable-rsavfy --enable-sp --enable-sp-math --disable-ecc --disable-dh --disable-pkcs12  && make
./configure --enable-cryptonly --enable-rsavfy --enable-sp-math-all --disable-ecc --disable-dh --disable-pkcs12  && make
```

### CODE REVIEW

**Review by dgarske — CHANGES_REQUESTED** [review]
```
./configure --enable-rsapub --enable-sp-math-all && make
dh.c:(.text+0x6be): undefined reference to `sp_prime_is_prime_ex'
```

```
./configure --enable-rsapub --enable-sp-math-all CFLAGS="-DWOLFSSL_RSA_VERIFY_ONLY" && make
wolfcrypt/src/sp_int.c:4034:5: error: implicit declaration of function ‘_sp_add_off’; did you mean ‘_sp_sub_off’? [-Werror=implicit-function-declaration]

 4034 |     _sp_add_off(a, b, r, 0);

      |     ^~~~~~~~~~~

      |     _sp_sub_off

wolfcrypt/src/sp_int.c:4034:5: error: nested extern declaration of ‘_sp_add_off’ [-Werror=nested-externs]
```

**Review by dgarske — CHANGES_REQUESTED** [review]
Thanks @SparkiDev for the clarification on the rsavfy and rsapub usage. It is meant to be wolfCrypt only RSA verify only.

Still getting an error with --enable-sp-math or --enable-sp-math-all:

```
./configure --enable-cryptonly --enable-rsavfy --enable-sp-math-all --disable-ecc --disable-dh && make
...
asn.c:(.text+0x1fc5): undefined reference to `sp_cmp'
/usr/bin/ld: asn.c:(.text+0x1fef): undefined reference to `sp_cmp'
/usr/bin/ld: wolfcrypt/src/.libs/src_libwolfssl_la-wolfmath.o: in function `mp_cond_copy':
wolfmath.c:(.text+0x7c): undefined reference to `sp_grow'
/usr/bin/ld: wolfcrypt/src/.libs/src_libwolfssl_la-wolfmath.o: in function `wc_export_int':
wolfmath.c:(.text+0x243): undefined reference to `sp_to_unsigned_bin'
/usr/bin/ld: src/.libs/libwolfssl.so.24.3.0: hidden symbol `sp_cmp' isn't defined
/usr/bin/ld: final link failed: bad value
```

**Comment by SparkiDev** [comment]
--enable-rsavfy --disable-dh --disable-ecc --disable-pkcs12 and combinations of --enable-sp --enable-sp-math --enable-sp-math-all
--disable-shared was used in testing but now shared works.

**Review by dgarske — APPROVED** [review]
Thanks Sean!

**Pull request merged**
