### PR TITLE
Added support for an anonymous cipher suite

### PR DESCRIPTION
**Pull request by thivyaashok**
Support for cipher suite TLS_DH_anon_WITH_AES256_GCM_SHA384 was added.

### CODE REVIEW

**Comment by kaleb-himes** [comment]
Hi Thivya,

Thank you for opening this pull request. Before we can review for relevance could you check why the diff is reporting:

```
+20,095 −17,967
```

It looks like the editor you used may have done some automatic formatting of white space as many of these changes are simply indentation changes. We like our current offsets for readability!
(See screenshot). Could you clean those up so we can better review this PR for relevance?

Warm Regards,

Kaleb

screen shot 2017-12-13 at 12 26 46

**Comment by thivyaashok** [comment]
Hi Kaleb,
Sorry about the format issues. I've corrected them and the differences show up only the additions to the code.

**Comment by kaleb-himes** [comment]
@thivyaashok that is excellent, much cleaner and easier to review now! Thanks!

One of our developers will be reviewing in the near future and we will let you know if we have any feedback on your changes.

If your additions are accepted then I will confirm your contributor status with wolfSSL Inc.

Warm Regards,

- K

**Comment by kaleb-himes** [comment]
Jenkins,

Thivya is now an approved contributor. It is ok to test this pull request!

**Pull request merged**
