### PR TITLE
alter return value and add error string

### PR DESCRIPTION
**Pull request by JacobBarthelmeh**
# Description

Please describe the scope of the fix or feature addition.

Fixes zd#

# Testing

How did you test?

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Review by julek-wolfssl — COMMENTED** [review]
Are you sure this should be `X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY` instead of `X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT`? I'm reading the OpenSSL source and manual but I still don't understand the difference fully.

**Comment by JacobBarthelmeh** [comment]
Not 100% sure, from what I understood the difference was if a CA was loaded and there still was not a match versus no CA's loaded. The "_LOCALLY" meaning it actually tried to match with a CA but could not find it. It could be improved on to check if CA's had been loaded to switch between the 2 errors, had avoided that though because it would take some more code changes and add complexity.

**Comment by JacobBarthelmeh** [comment]
The X509_V_ERR_INVALID_CA error though should be if there was an error with the CA itself, possibly when parsing it.

**Review by julek-wolfssl — APPROVED** [review]
`X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY` looks to be the prevalent error that gets checked in projects consuming OpenSSL. Both `X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY` and `X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT` are treated the same in most cases but in some places only `X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY` is used.

**Pull request merged**
