### PR TITLE
Support spaces in path passed to Espressif\ESP-IDF\setup_win.bat

### PR DESCRIPTION
**Pull request by PaulMartinsen**
# Description

`wolfssl\IDE\Espressif\ESP-IDF\setup_win.bat` provides a handy mechanism to copy required files into a project by supplying a destination path as the first argument, however it doesn't support paths containing spaces (even when quoted). 

# Testing

Deployed library to a folder that contained spaces by running `setup_win.bat "<directory containing spaces>"` and to a directory without spaces by running `setup_win.bat <directory_without_spaces>` from a console.

### CODE REVIEW

**Comment by gojimmypi** [comment]
@PaulMartinsen thanks very much for this modification!

I've tested this with `setup.bat "C:\SysGCC\esp32\esp-idf\v5 with spaces"` and confirmed the examples and component install are completed successfully for new and existing directories.

**Comment by gojimmypi** [comment]
@PaulMartinsen thank you again for your suggestion. All contributors must have a signed contribution agreement on file. If you have additional pull requests planned we can evaluate getting you setup. For now I will treat this as a bug report and we will fix internally. I’ve noted this bug confirmation as related to https://github.com/wolfSSL/wolfssl/issues/5154 and will provide you a link to the new PR when it is ready. 

Can you tell us more about your project and use case for wolfSSL on the ESP32?

**Comment by PaulMartinsen** [comment]
Thanks for considering the PR @gojimmypi. I might be using the library for a while, so it would be great to have it incorporated. 

I'm evaluating the WolfSSL library to support IEEE 11073 standard communications on an ESP32S3 before we look at a commercial license. I realize that board isn't supported yet so I was going to take a quick look to see what is needed to get that going today. I saw a couple of issues talking about the S3 that were a couple of months old. Do you know if there is a roadmap for S3 support at this point?

**Comment by gojimmypi** [comment]
Hi @PaulMartinsen  that's cool you plan on using the wolfSSL library!

I do have automated support for all of the ESP32-nn chips in the works in my [Espressif_Multichip Branch](https://github.com/gojimmypi/wolfssl/tree/Espressif_Multichip). It's still half-baked, so proceed with caution if you test drive it. In short, I have a new [CMakeLists.txt](https://github.com/gojimmypi/wolfssl/blob/Espressif_Multichip/IDE/Espressif/ESP-IDF/examples/wolfssl_benchmark/CMakeLists.txt) to detect the Espressif chips. At the moment, it is copying one of the [files in the libs directory](https://github.com/gojimmypi/wolfssl/tree/Espressif_Multichip/IDE/Espressif/ESP-IDF/examples/wolfssl_benchmark/libs) to the `./component` directory at build time. It works, but I think I will instead use only one more elaborate `user_settings.h` for all chips instead of separate files. Your input is certainly welcome here.

We do plan on supporting this soon. Please send an email to support@wolfssl.com , reference this PR discussion, and let them know your general location & we can get this bumped up on my priority list for you.

**Comment by gojimmypi** [comment]
Hi @PaulMartinsen  I have a bit more information for you regarding the ESP32-S3:  I've confirmed wolfSSL will work with hardware acceleration turned off. Looks like between SoC chipsets, there were many changes at the HAL level, register naming, include files, etc. So it will take a bit of work to be able to turn that feature on. 

I'll await hearing from support once you contact them and we can all decide together how best to proceed.

In the meantime, here's the benchmark on my ESP32-S3 DevKitC-1, again no HW encryption, and no optimizations:

```
ESP-ROM:esp32s3-20210327
I (301) spi_flash: detected chip: generic
I (305) spi_flash: flash io: dio
;33mW (309) spi_flash: Detected size(8192k) larger than the size in the binary image header(2048k). Using the size in
 the binary image header.
I (323) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (338) wolfssl_benchmark: --------------------------------------------------------
I (347) wolfssl_benchmark: --------------------------------------------------------
I (355) wolfssl_benchmark: ---------------------- BEGIN MAIN ----------------------
I (363) wolfssl_benchmark: --------------------------------------------------------
I (372) wolfssl_benchmark: --------------------------------------------------------
I (380) wolfssl_benchmark: LIBWOLFSSL_VERSION_STRING = 5.5.3
I (386) wolfssl_benchmark: CONFIG_IDF_TARGET = esp32s3
I (392) wolfssl_benchmark: Xthal_have_ccount = 1
I (397) wolfssl_benchmark: Stack HWM: 53524

I (402) wolfssl_benchmark: NO_ESP32WROOM32_CRYPT defined! HW acceleration DISABLED.
I (411) wolfssl_benchmark: app_main CONFIG_BENCH_ARGV = -lng 0
I (417) wolfssl_benchmark: construct_argv arg:-lng 0

------------------------------------------------------------------------------
 wolfSSL version 5.5.3
------------------------------------------------------------------------------
wolfCrypt Benchmark (block bytes 1024, min 1.0 sec each)
RNG                        725 KiB took 1.010 seconds,  717.822 KiB/s Cycles per byte = 217.73
AES-128-CBC-enc            950 KiB took 1.005 seconds,  945.274 KiB/s Cycles per byte = 165.25
AES-128-CBC-dec            925 KiB took 1.000 seconds,  925.000 KiB/s Cycles per byte = 168.81
AES-192-CBC-enc            875 KiB took 1.006 seconds,  869.781 KiB/s Cycles per byte = 179.62
AES-192-CBC-dec            875 KiB took 1.026 seconds,  852.827 KiB/s Cycles per byte = 183.23
AES-256-CBC-enc            825 KiB took 1.024 seconds,  805.664 KiB/s Cycles per byte = 193.88
AES-256-CBC-dec            800 KiB took 1.011 seconds,  791.296 KiB/s Cycles per byte = 197.49
AES-128-GCM-enc            250 KiB took 1.107 seconds,  225.836 KiB/s Cycles per byte = 692.08
AES-128-GCM-dec            250 KiB took 1.108 seconds,  225.632 KiB/s Cycles per byte = 692.51
AES-192-GCM-enc            225 KiB took 1.018 seconds,  221.022 KiB/s Cycles per byte = 706.81
AES-192-GCM-dec            225 KiB took 1.019 seconds,  220.805 KiB/s Cycles per byte = 707.21
AES-256-GCM-enc            225 KiB took 1.039 seconds,  216.554 KiB/s Cycles per byte = 721.33
AES-256-GCM-dec            225 KiB took 1.040 seconds,  216.346 KiB/s Cycles per byte = 721.75
GMAC Default               303 KiB took 1.003 seconds,  302.094 KiB/s Cycles per byte = 517.13
3DES                       350 KiB took 1.010 seconds,  346.535 KiB/s Cycles per byte = 450.85
MD5                         10 MiB took 1.002 seconds,   10.307 MiB/s Cycles per byte =  14.80
SHA                          4 MiB took 1.005 seconds,    4.348 MiB/s Cycles per byte =  35.07
SHA-256                      2 MiB took 1.007 seconds,    1.697 MiB/s Cycles per byte =  89.85
SHA-512                    950 KiB took 1.004 seconds,  946.215 KiB/s Cycles per byte = 165.21
HMAC-MD5                    10 MiB took 1.002 seconds,   10.185 MiB/s Cycles per byte =  14.97
HMAC-SHA                     4 MiB took 1.002 seconds,    4.313 MiB/s Cycles per byte =  35.39
HMAC-SHA256                  2 MiB took 1.000 seconds,    1.685 MiB/s Cycles per byte =  90.61
HMAC-SHA512                950 KiB took 1.020 seconds,  931.373 KiB/s Cycles per byte = 167.78
PBKDF2                     224 bytes took 1.061 seconds,  211.122 bytes/s Cycles per byte = 758154.62
RSA     2048   public        36 ops took 1.033 sec, avg 28.694 ms, 34.850 ops/sec
RSA     2048  private         2 ops took 3.512 sec, avg 1756.000 ms, 0.569 ops/sec
ECC   [      SECP256R1]   256  key gen         6 ops took 1.485 sec, avg 247.500 ms, 4.040 ops/sec
ECDHE [      SECP256R1]   256    agree         6 ops took 1.482 sec, avg 247.000 ms, 4.049 ops/sec
ECDSA [      SECP256R1]   256     sign         4 ops took 1.004 sec, avg 251.000 ms, 3.984 ops/sec
ECDSA [      SECP256R1]   256   verify         4 ops took 1.913 sec, avg 478.250 ms, 2.091 ops/sec
CURVE  25519  key gen         2 ops took 1.136 sec, avg 568.000 ms, 1.761 ops/sec
CURVE  25519    agree         2 ops took 1.136 sec, avg 568.000 ms, 1.761 ops/sec
ED     25519  key gen        55 ops took 1.012 sec, avg 18.400 ms, 54.348 ops/sec
ED     25519     sign        44 ops took 1.019 sec, avg 23.159 ms, 43.180 ops/sec
ED     25519   verify        12 ops took 1.072 sec, avg 89.333 ms, 11.194 ops/sec
Benchmark complete
I (42490) wolfssl_benchmark: wolf_test_task complete success result code = 0
I (42495) wolfssl_benchmark: Stack HWM: 12484

```

**Comment by PaulMartinsen** [comment]
Thanks for the benchmark data @gojimmypi . I wasn't sure how to run without the hardware acceleration; looks like it is definitely needed though. 

I made a little progress adding support for ESP32s3 in a fork here: https://github.com/PaulMartinsen/wolfssl  with eh v5 version of ESP-IDF. 

I reworked the port files to build with the ESP32s3 and have started testing the SHA acceleration using `wolfssl\wolfcrypt\test\test.c`. Output (with some additional diagnostics):

```
------------------------------------------------------------------------------
 wolfSSL version 5.5.4
------------------------------------------------------------------------------
error    test passed!
MEMORY   test passed!
base64   test passed!
asn      test passed!
RANDOM   test passed!
MD5      test passed!
MD4      test passed!
i=0
input=, len=0
Result: 0F FD 8D 43 B4 E3 3C 7C 53 46 1B D1 0F 27 A5 46 10 50 D9 0D 
Expected: DC 39 A3 EE 5E 6B 4B 0D 32 55 BF EF 95 60 18 90 AF D8 07 09 
SHA      test failed!
 error = -1806
Test result = -1
```

The test that is failing starts on line 2335 (in `test.c`) and it seems to be testing copying a test result. I suspect the problem is that for the ESP32s3 it may be necessary to load the hash function output with a partly completed result to continue processing.  I'll reach out to your support team to ask about timelines as it may be a week or two for me to get back to this. 

Of particular note, the ESP32s3 appears to handle byte order differently than the ESP32. I had to explicitly swap byte order sending message data into and retrieving hash result from the SHA accelerator with the ESP32s3.

**Comment by gojimmypi** [comment]
Hello @PaulMartinsen ! That's awesome you are making progress! Have you had a chance to reach out to support and get a contributor agreement signed? Otherwise we won't be able to merge any of your code. 

I've already started down the road of some of the conditional HW too, so let's see if we can share the workload efficiently.

If you have confirmed the tests run properly _without_ HW acceleration, then skip to the end of this message "Hardware Test".

# Software Test

If you do not yet have software-only, no HW acceleration wolfSSL tests running, some tips:  in my experience many of the oddities are caused by low memory: running out of stack and/or heap. Most often stack.

I just ran the ESP32-S3 tests successfully on my board (still on the prior wolfSSL 5.5.3 release)

```
ESP-ROM:esp32s3-20210327
I (303) sleep: Configure to isolate all GPIO pins in sleep state
I (310) sleep: Enable automatic switching of GPIO sleep configuration
I (317) cpu_start: Starting scheduler on PRO CPU.
I (322) wolfssl_test: --------------------------------------------------------
I (322) wolfssl_test: --------------------------------------------------------
I (332) wolfssl_test: ---------------------- BEGIN MAIN ----------------------
I (342) wolfssl_test: --------------------------------------------------------
I (352) wolfssl_test: --------------------------------------------------------
I (352) wolfssl_test: LIBWOLFSSL_VERSION_STRING = 5.5.3
I (362) wolfssl_test: CONFIG_IDF_TARGET = esp32s3
I (372) wolfssl_test: Stack HWM: 53588

I (372) wolfssl_test: NO_ESP32WROOM32_CRYPT defined! HW acceleration DISABLED.
I (382) wolfssl_test: CONFIG_IDF_TARGET=esp32s3
------------------------------------------------------------------------------
 wolfSSL version 5.5.3
------------------------------------------------------------------------------
error    test passed!
MEMORY   test passed!
base64   test passed!
asn      test passed!
RANDOM   test passed!
MD5      test passed!
MD4      test passed!
SHA      test passed!
SHA-256  test passed!
SHA-512  test passed!
Hash     test passed!
HMAC-MD5 test passed!
HMAC-SHA test passed!
HMAC-SHA256 test passed!
HMAC-SHA512 test passed!
HMAC-KDF    test passed!
TLSv1.3 KDF test passed!
GMAC     test passed!
DES      test passed!
DES3     test passed!
AES      test passed!
AES192   test passed!
AES256   test passed!
AES-GCM  test passed!
RSA      test passed!
PWDBASED test passed!
ECC      test passed!
ECC buffer test passed!
CURVE25519 test passed!
ED25519  test passed!
logging  test passed!
time test passed!
mutex    test passed!
Test complete
I (122512) wolfcrypt_test: Exiting main with return code:  0

I (122512) wolfssl_test: MqttClient_NetConnect Task main, Stack HWM: 5684

```
I did have an interesting problem though: I don't often change chipsets and IDF versions (perhaps you saw my toolchain train wreck in the sysprogs forum). I kept seeing all sorts of bizarre error messages. I found that an effective solution for just weird stuff is to exit Visual Studio and delete these three directories:

```
./.vs
./build
./.visualgdb
```
(that `.vs` is hidden)

As for other possible causes, be sure to _completely_ turn off HW acceleration for the `-S3` at this time in the `user_settings.h`:

```
#define NO_ESP32WROOM32_CRYPT
#define NO_WOLFSSL_ESP32WROOM32_CRYPT_HASH
#define NO_WOLFSSL_ESP32WROOM32_CRYPT_AES
#define NO_WOLFSSL_ESP32WROOM32_CRYPT_RSA_PRI
```

If you believe you've done this, keep in mind there's a wonky problem in the ESP-IDF mentioned in https://github.com/wolfSSL/wolfssl/issues/5727  -  this means sometimes wolfSSL won't "see" the desire to use the `user_settings.h` file. It's not at all intuitive. 

Also: make sure there are no stray `user_settings.h` files. There should be exactly one. Mine for example, is located in 

```
C:\SysGCC\esp32\esp-idf\v4.4.2\components\wolfssl\include
```

As for the stack, see my [sdkconfig.defaults](https://github.com/gojimmypi/wolfssl/blob/Espressif_Multichip/IDE/Espressif/ESP-IDF/examples/wolfssl_test/sdkconfig.defaults). I set an obscenely large stack, but it will reliably work. Once implemented in a specific application there are tools to monitor and tune the actual stack size. As you are using VisualGDB, here are all my settings, you can also manually set stack size here:

image

Heads up using the code in my [Espressif_Multichip branch](https://github.com/gojimmypi/wolfssl/tree/Espressif_Multichip/IDE/Espressif/ESP-IDF/examples/wolfssl_test) that I needed to add this line:

```
#if defined(WOLFSSL_ESPIDF)
    int wolf_test_task(void);
#endif
```
... to the wolfssl `test.h` , in my case located in:

```
C:\SysGCC\esp32\esp-idf\v4.4.2\components\wolfssl\wolfcrypt\test
```

# Hardware Test

As for the HW acceleration you are working on, I would be surprised if this is true:

>  necessary to load the hash function output with a partly completed result

In my experience on both the Xtensa ESP32 and the RISC-V ESP32-C3, the register itself retains the in-progress hash value: you don't _need_ to keep restuffing the result. There is however a new "interleaving" feature where you _can_ - if perhaps you have concurrent calculations. See section 18.4.2.1 on page 822 & 823 of the [ESP32-S3 Technical Reference Manual](https://www.espressif.com/sites/default/files/documentation/esp32-s3_technical_reference_manual_en.pdf#page=823)

image

I definitely recommend first getting the simple case working: no interleave, no DMA. 

I'm looking forward to working with you on this. Cheers.

**Comment by PaulMartinsen** [comment]
Thanks @gojimmypi . I'll check out the no-acceleration version when I get back. I had been comparing the ESP32 results with ESP32s3 results and output from a different library. An earlier test in `test.c` uses Sha-256, which dealing with endians fixed. The failing test is using Sha1 I believe. I didn't have time to look into it closely so was just guessing with hash initialization. Though I believe the engine is disabled when the hardware is unlocked, which may be a contributing factor. 

I reached out to the WolfSSL licensing team to check the commercial license is going to work for us & look forward to finding a path forward in the new year.

**Pull request closed without merging**
