### PR TITLE
wolfcrypt/src/asn.c: fix buffer underrun in EncodeExtensions() and leak in ParseCRL_Extensions()

### PR DESCRIPTION
**Pull request by douzzer**
wolfcrypt/src/asn.c: fix buffer underrun in EncodeExtensions(), due to faulty iteration limit calculation, when smallstack build.

fixes these:
```
[all-sp-small-stack-asn-template] [5 of 76] [6b7f0d4ee7]
    configure...   real 0m6.724s  user 0m3.743s  sys 0m3.653s
    build...wolfcrypt/src/asn.c: In function ‘EncodeExtensions’:
0053bd3af1 (<anthony@wolfssl.com> 2022-03-02 15:16:39 -0500 23426)          i < (int)(sizeof(certExtsASN) / sizeof(ASNItem)); i += 4) {
wolfcrypt/src/asn.c:23426:40: error: division ‘sizeof (ASNItem *) / sizeof (ASNItem)’ does not compute the number of array elements [-Werror=sizeof-pointer-div]
23426 |          i < (int)(sizeof(certExtsASN) / sizeof(ASNItem)); i += 4) {
      |                                        ^
0053bd3af1 (<anthony@wolfssl.com> 2022-03-02 15:16:39 -0500 23399)     ASNItem *certExtsASN = (ASNItem *)XMALLOC(certExtsASN_Length *
wolfcrypt/src/asn.c:23399:14: note: first ‘sizeof’ operand was declared here
23399 |     ASNItem *certExtsASN = (ASNItem *)XMALLOC(certExtsASN_Length *
      |              ^~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:5691: wolfcrypt/src/src_libwolfssl_la-asn.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:6576: all-recursive] Error 1
make: *** [Makefile:3943: all] Error 2
   real 0m17.880s  user 1m11.021s  sys 0m3.116s
    all-sp-small-stack-asn-template fail_build
```

```[clang-tidy-asn-template-sp-all-small-stack] [12 of 76] [6b7f0d4ee7]
    configure...   real 0m10.556s  user 0m5.072s  sys 0m6.262s
    build...0053bd3af1 (<anthony@wolfssl.com> 2022-03-02 15:16:39 -0500 23426)          i < (int)(sizeof(certExtsASN) / sizeof(ASNItem)); i += 4) {
/home/wolfbot/tmp/wolfssl_test_workdir.20197/wolfssl/wolfcrypt/src/asn.c:23426:20: warning: suspicious usage of 'sizeof(A*)'; pointer to aggregate [bugprone-sizeof-expression]
i < (int)(sizeof(certExtsASN) / sizeof(ASNItem)); i += 4) {
                   ^
0053bd3af1 (<anthony@wolfssl.com> 2022-03-02 15:16:39 -0500 23426)          i < (int)(sizeof(certExtsASN) / sizeof(ASNItem)); i += 4) {
/home/wolfbot/tmp/wolfssl_test_workdir.20197/wolfssl/wolfcrypt/src/asn.c:23426:20: warning: suspicious usage of sizeof pointer 'sizeof(T*)/sizeof(T)' [bugprone-sizeof-expression]
/home/wolfbot/tmp/wolfssl_test_workdir.20197/wolfssl/wolfcrypt/src/asn.c:23426:40: warning: 'sizeof (certExtsASN)' will return the size of the pointer, not the array itself [clang-diagnostic-sizeof-pointer-div]
i < (int)(sizeof(certExtsASN) / sizeof(ASNItem)); i += 4) {
                   ~~~~~~~~~~~~~~~~~~~ ^
0053bd3af1 (<anthony@wolfssl.com> 2022-03-02 15:16:39 -0500 23399)     ASNItem *certExtsASN = (ASNItem *)XMALLOC(certExtsASN_Length *
/home/wolfbot/tmp/wolfssl_test_workdir.20197/wolfssl/wolfcrypt/src/asn.c:23399:14: note: pointer 'certExtsASN' declared here
ASNItem *certExtsASN = (ASNItem *)XMALLOC(certExtsASN_Length *
             ^
make[2]: *** [Makefile:5691: wolfcrypt/src/src_libwolfssl_la-asn.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:6576: all-recursive] Error 1
make: *** [Makefile:3943: all] Error 2
   real 5m15.488s  user 10m14.623s  sys 0m11.961s
    clang-tidy-asn-template-sp-all-small-stack fail_build
```

### CODE REVIEW

**Comment by anhu** [comment]
:facepalm:

**Review by anhu — APPROVED** [review]
Thanks for finding this douzzer!!

**Review by anhu — APPROVED** [review]
Wow....Nice!!  However, the scope of this PR has changed.  Maybe edit the title?

**Review by dgarske — APPROVED** [review]
Over to @SparkiDev

**Comment by douzzer** [comment]
```
76 of 77 checks succeeded, 0 skipped, 0 forced, and 1 failed, for fb0c9b2a66.
```
(the one fail was on memory leaks in `sp-asn-template-asm-smallstack-sanitizer`, already reported to @SparkiDev )

**Pull request merged**
