### PR TITLE
Udp proxy fixes

### PR DESCRIPTION
**Pull request by bandi13**
Address @julek-wolfssl 's concerns with the script

### CODE REVIEW

**Review by julek-wolfssl — APPROVED** [review]
If we make the example apps smarter then we can go back to dropping evey ith packet.

**Review by julek-wolfssl — CHANGES_REQUESTED** [review]
I think it is better to use `bwrap` for the port isolation and use `mktemp` to get a unique pcap file name (if that is a concern).

**Comment by bandi13** [comment]
> I think it is better to use `bwrap` for the port isolation and use `mktemp` to get a unique pcap file name (if that is a concern).

I could do `bwrap` though it seems overkill. The PCAP file name doesn't need to be unique, and would make the Jenkins side more difficult.

**Comment by bandi13** [comment]
Actually, upon further consideration, the calling script would have to be doing the `bwrap`-ing which is not ideal. I can't bwrap and have multiple applications running in the same wrapped environment.

**Review by JacobBarthelmeh — DISMISSED** [review]

**Comment by JacobBarthelmeh** [comment]
Assigning to @julek-wolfssl for review of requested changes.

**Comment by julek-wolfssl** [comment]
Take a look at https://github.com/wolfSSL/wolfMQTT/blob/master/scripts/client.test#L28-L35 to see how a script can `bwrap` itself.

**Comment by bandi13** [comment]
retest this please

**Review by julek-wolfssl — APPROVED** [review]

**Review by JacobBarthelmeh — APPROVED** [review]

**Pull request merged**
