### PR TITLE
expand subject name and req attribute support

### PR DESCRIPTION
**Pull request by JacobBarthelmeh**

### CODE REVIEW

**Comment by JacobBarthelmeh** [comment]
FYI this increases sizes of structures, potentially we should be using a macro guard if needed?

**Review by dgarske — APPROVED** [review]
Looks good, tests out. The `struct CertName` growth is my only concern, but it is acceptable. I'd like @SparkiDev to review also.

**Comment by SparkiDev** [comment]
SetSubject() doesn't support the new attributes. Is this intentional?
Expanding the structure without an ifdef doesn't feel right.
Maybe a define like WOLFSSL_CERT_NAME_SMALL_ATTR_LIST to disable the commonly used ones.

**Review by SparkiDev — APPROVED** [review]

**Comment by JacobBarthelmeh** [comment]
retest this

**Pull request merged**
