### PR TITLE
Zephyr port: fix setup.sh script

### PR DESCRIPTION
**Pull request by SparkiDev**
Apply diff to include wolfssl as a zephyr module

### CODE REVIEW

**Comment by ejohnstown** [comment]
retest this please

**Comment by ejohnstown** [comment]
When I run the setup.sh, it fails on the patch step:

    error: patch failed: modules/Kconfig:52
    error: modules/Kconfig: patch does not apply
    error: patch failed: west.yml:158
    error: west.yml: patch does not apply

I'm using zephyr 0.12.4.

**Comment by maximevince** [comment]
Why is wolfSSL using this setup.sh script?
Wouldn't it be possible to create a `zephyr` directory in the repo, containing a `module.yml` file, describing the `Kconfig` and `CMakeLists.txt` files?

The only thing which is then required from a Zephyr user, is to add the wolfssl repo as a project/module to their `west.yml`.
No funky `setup.sh` patches making assumptions about your repo layout are required. Additionally, no files are modified, which are not part of any repository that `west` is tracking.

See https://docs.zephyrproject.org/latest/guides/modules.html#build-system-integration and https://docs.zephyrproject.org/latest/guides/modules.html#using-west

**Comment by SparkiDev** [comment]
Hi @maximevince

The setup.sh script is doing the minimum necessary to get wolfSSL into the zephyrproject directories.
That is, it is copying the library over, creating a wolfSSL module in zephyr with the module.yml and Kconfig, adding reference in west.yml  plus adding in examples.

The west tracking requires Zephyr to track our repository, which they are not currently doing. So I'm doing things manually.

I've update the README.md to describe a manual setup.

**Comment by SparkiDev** [comment]
> When I run the setup.sh, it fails on the patch step:
> 
> ```
> error: patch failed: modules/Kconfig:52
> error: modules/Kconfig: patch does not apply
> error: patch failed: west.yml:158
> error: west.yml: patch does not apply
> ```
> 
> I'm using zephyr 0.12.4.

I've changed the patching to check if it is already applied before patching.
Hopefully this works better.

**Review by ejohnstown — CHANGES_REQUESTED** [review]
I had to modify the west.yml file by hand as the script failed to do it. After that, the build succeeded and the test passed.

**Review by ejohnstown — APPROVED** [review]

**Comment by maximevince** [comment]
> Hi @maximevince
> 
> The setup.sh script is doing the minimum necessary to get wolfSSL into the zephyrproject directories.
> That is, it is copying the library over, creating a wolfSSL module in zephyr with the module.yml and Kconfig, adding reference in west.yml plus adding in examples.
> 
> The west tracking requires Zephyr to track our repository, which they are not currently doing. So I'm doing things manually.
> 
> I've update the README.md to describe a manual setup.

Hi Sean,

Yes, I get that the setup.sh script works that way.
However, if you directly create the `zephyr/module.yaml` in the wolfssl repo, you do not need a 'setup.sh' script to copy all sorts of stuff manually.

There would just be one step required: modifying the west.yml (just like your script is requesting to do):
```
    - name: wolfssl
      url-base: https://github.com/wolfssl
```

And add the following lines to the end of 'projects' in your west.yml:
```
    - name: wolfssl
      path: modules/crypto/wolfssl
      revision: master
      remote: wolfssl

```

That's really it; now `west` will track wolfSSL, and find all the Kconfig + CMakeLists.txt from there. No `setup.sh` needed.
I can try and make an example of this real quick in my own wolfSSL fork.

**Comment by maximevince** [comment]
I have created a PR implementing what I was trying to explain :)
https://github.com/wolfSSL/wolfssl/pull/4264

I am open for feedback, of course!

**Comment by SparkiDev** [comment]
Closing in favour of #4264 that uses the west repository tool.

**Pull request closed without merging**
