### PR TITLE
Create APIs to expose IANA id array values

### PR DESCRIPTION
**Pull request by mmann78**
Added the following APIs:
wolfSSL_get_cipher_iana_list
wolfSSL_CTX_get_cipher_iana_list
wolfSSL_get_compiled_cipher_iana_list
wolfSSL_get_cipher_string

wolfSSL_[CTX_]get_cipher_iana_list populate passed in array with data from Suites structure.  wolfSSL_get_compiled_cipher_iana_list populated passed in array with data directly from cipher_names.
Both return number of suites found (based on array size passed in)

Also compressed cipher_names and cipher_name_idx into a single structure that represents name and both IANA byte values.

### CODE REVIEW

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Hi mmann78, sorry about this. We were setting up three new pull request tests today and even though it looks like me, it's just Jenkins using my credentials to verify things. I apologize for the three additional emails you received today. Chris brought it to my attention so I wanted to reach out and explain.

-Kaleb

**Comment by ejohnstown** [comment]
I apologize for the long delay getting back to you. Could you update this pull request with the following changes:

1. Remove the user specific debugging commit, it is in PR 420 already. (Maybe rebase and push it again. Or just resubmit the cipher list commit.)
2. Change the cipherPrefix and cipherSuite to byte values.
3. Resolve the conflicts.

Otherwise, this is great. I just need the signed contributor agreement and we can accept this. Thanks!

**Comment by dgarske** [comment]
Closing in favor of wolf changes to add these features.

We ended up doing our refactor of that code and added a new API:
See these PR's:
https://github.com/wolfSSL/wolfssl/pull/1560
https://github.com/wolfSSL/wolfssl/pull/1586

Added new API const char* wolfSSL_get_cipher_name_from_suite(const byte cipherSuite0, const byte cipherSuite) to get the IANA name from the cipher suite bytes.

Thanks,
David Garske, wolfSSL

**Pull request closed without merging**
