### PR TITLE
Aarch64: make code compile when no hardware crypto avail

### PR DESCRIPTION
**Pull request by SparkiDev**
# Description

Detects availability of instructions for Aarch64.

# Testing

With and without WOLFSSL_ARMASM_NO_HW_CRYPTO

./configure --enable-armasm CFLAGS="-DWOLFSSL_ARMASM_NO_HW_CRYPTO" && make check

Regression tested Aarch64, ARMv8 and ARMv7a with ARM assembly.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Comment by SparkiDev** [comment]
retry this please

**Comment by SparkiDev** [comment]
retest this please

**Review by dgarske — APPROVED** [review]
Tested on Pi4, Pi5 and STM32MP1. Thank you @SparkiDev . Over to @douzzer

**Review by douzzer — APPROVED** [review]
tested with `wolfssl-multi-test.sh ... check-source-text quantum-safe-wolfssl-all-cross-armv7a-armasm-unittest quantum-safe-wolfssl-all-cross-aarch64-armasm-unittest-Os`

**Pull request merged**
