### PR TITLE
Move ASN.1 APIs out to separate file: ssl_asn1.c

### PR DESCRIPTION
**Pull request by SparkiDev**
# Description

Implementations of ASN.1 APIs reworked.

Added tests.

Added wolfssl_bn_set_neg for ASN.1 code.
Added wolfssl_sk_new_type() and wolfssl_sk_pop_type() to generically handle creating and popping a stack of elements of a type.

No longer freeing pathlen field of ASN1 OBJECT in
wolfSSL_X509_EXTENSION_free(). This is happening in wolfSSL_ASN1_OBJECT_free().
Stop wolfSSL_i2d_X509_NAME_canon from double freeing ASN.1 STRING's data field.

Fixed up GetFormattedTime() to be better code.
Added ASN_CLASS_MASK to mask off the class part of an ASN.1 tag. NO_ASN_TIME means no implementation to get the current time. Disable features that won'r work without time.

# Testing

Regression tested OpenSSL compatibility APIs.

# Checklist

 - [x] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Comment by SparkiDev** [comment]
retest this please

**Comment by SparkiDev** [comment]
retest this please

**Comment by SparkiDev** [comment]
retest this please

**Review by dgarske — APPROVED** [review]

**Comment by dgarske** [comment]
Looks like getting error on:

```
Testing DEFAULT: --enable-arc4 --enable-opensslextra
src/ssl.c:154:16: warning: ‘wolfssl_bn_set_neg’ used but never defined
  154 |     static int wolfssl_bn_set_neg(WOLFSSL_BIGNUM* bn, int n);
      |                ^~~~~~~~~~~~~~~~~~
```

**Comment by SparkiDev** [comment]
> Looks like getting error on:
> 
> ```
> Testing DEFAULT: --enable-arc4 --enable-opensslextra
> src/ssl.c:154:16: warning: ‘wolfssl_bn_set_neg’ used but never defined
>   154 |     static int wolfssl_bn_set_neg(WOLFSSL_BIGNUM* bn, int n);
>       |                ^~~~~~~~~~~~~~~~~~
> ```

This doesn't happen for me.
Updated pull request and I can't see a reason for a failure.

**Review by dgarske — APPROVED** [review]

**Comment by dgarske** [comment]
FYI: My bad for not better catching the issues on this PR.

1) The patches @douzzer had pushed to this branch got overwritten with the force push. @douzzer is working on a new PR with those patches.
2) The used but never defined was still broken. @julek-wolfssl  put up a PR here:  https://github.com/wolfSSL/wolfssl/pull/6255

**Pull request merged**
