### PR TITLE
Support for Frosted OS

### PR DESCRIPTION
**Pull request by danielinux**
Add support for Frosted OS userspace applications. Compile with -D WOLFSSL_FROSTED.

https://github.com/insane-adding-machines/frosted
https://github.com/insane-adding-machines/frosted-userland

### CODE REVIEW

**Comment by cconlon** [comment]
Hey Daniele!

Thanks for contributing a port for Frosted!  We'll need to have you sign a Contributor Agreement before we can pull these in.  Can you shoot me an email and we can get that started?

Thanks,
Chris

**Comment by cconlon** [comment]
Test this please jenkins

**Comment by danielinux** [comment]
Hello Chris! Will do, thanks!

**Comment by cconlon** [comment]
Signed Contributor Agreement received and filed, thanks!  Happy to have support for FROSTED in wolfSSL.

**Pull request merged**
