### PR TITLE
DTLS Test Speedup

### PR DESCRIPTION
**Pull request by ejohnstown**
Change the example client to use select instead of sleep. If building for the standalone client, it will wait 1 second. If built for no main driver, it'll wait 10ms rather than 1 second.

### CODE REVIEW

**Comment by ejohnstown** [comment]
Jenkins please retest this.

**Comment by ejohnstown** [comment]
jenkins retest this

**Comment by ejohnstown** [comment]
retest this please jenkins

**Comment by ejohnstown** [comment]
retest this please

**Comment by ejohnstown** [comment]
Please retest this

**Comment by ejohnstown** [comment]
David, your changes look good, too.

**Comment by dgarske** [comment]
Over to @toddouska for final as both John and I made changes here.

**Pull request merged**
