### PR TITLE
AES ARM32 and Thumb2 ASM: fixup ARM32 and add Thumb2

### PR DESCRIPTION
**Pull request by SparkiDev**
# Description

Fix which functions and data are compiled in depending on defines.
Better handing of constants.

# Testing

Regression tested ARM32 and Thumb2 assembly including inline.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Comment by dgarske** [comment]
@SparkiDev 

```
/tmp/workspace/PRB-multi-test-script/wolfssl/wolfcrypt/src/port/arm/armv8-aes.c:6312:39: warning: ISO C requires a translation unit to contain at least one declaration [clang-diagnostic-empty-translation-unit]
#endif /* !NO_AES && WOLFSSL_ARMASM */
^
```

**Comment by SparkiDev** [comment]
AES works for me cross-compiling for ARMv7a.
Which version of the compiler are you using?

**Comment by douzzer** [comment]
for all ARM variants, `gcc-12.3.1_p20230623`.

**Comment by douzzer** [comment]
retried with `gcc-13.2.0`.  same result:
```
[cross-armv7a-all-armasm-testsuite] [1 of 1] [d00a0a2b2a]
    using armv7a-unknown-linux-gnueabihf-gcc 13.2.0
    autogen.sh d00a0a2b2a...   real 0m15.909s  user 0m14.008s  sys 0m1.037s
    configure...   real 0m14.481s  user 0m7.559s  sys 0m8.136s
    build.../usr/libexec/gcc/armv7a-unknown-linux-gnueabihf/ld: warning: creating DT_TEXTREL in a shared object
   real 0m54.116s  user 2m39.239s  sys 0m5.974s
    testsuite.test...   real 0m0.705s  user 0m0.689s  sys 0m0.016s
testsuite.test for scenario cross-armv7a-all-armasm-testsuite exited with status 255.
================================================================================
[...]
DES3     test passed!
AES      test failed!
 error L=10775
 [fiducial line numbers: 7836 23987 35081 47260]
```

Maybe `qemu` is the variable:
```
qemu-arm version 8.0.4
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
```

**Comment by douzzer** [comment]
Upgraded to qemu 8.1.0 here this morning, and reran under that.  Same result.

Bear in mind these tests were all succeeding until 36b92a4cef.

**Comment by SparkiDev** [comment]
retest this please

**Comment by SparkiDev** [comment]
retest this please

**Comment by douzzer** [comment]
Jenkins, retest this please.

**Comment by douzzer** [comment]
Jenkins, retest this please.

**Review by JacobBarthelmeh — APPROVED** [review]

**Comment by markhermeling** [comment]
I have a static analysis finding in CodeSonar that popped up due to this PR. Screenshot attached.

I have to admit, I do not understand the logic. line 1015 in wolfcrypt/src/ed25519.c passes in in+1+ED25519_PUB_KEY_SIZE. Problem is that in points to a buffer of ED25519_PUB_KEY_SIZE, so by definition that pointer is outside of the buffer and then used by XMEMCPY.

SARIF also attached, this you can load into VS Code to see the flow.

[2283404.sarif.zip](https://github.com/wolfSSL/wolfssl/files/12529436/2283404.sarif.zip)
Screenshot 2023-09-05 at 8 21 48 PM

**Comment by SparkiDev** [comment]
Hi @markhermeling

Thank you for letting us know about this so quickly!
I have a new PR that contains a fix for this: #6750

Let us know if it is not fixed in the PR.

Thanks,
Sean :-)

**Pull request merged**
