### PR TITLE
autoconf 2.70 / gcc-10 updates

### PR DESCRIPTION
**Pull request by douzzer**
fix numerous warnings from autoconf, and a large batch of warnings on improper function declarations in api.c.

### CODE REVIEW

**Review by dgarske — APPROVED** [review]
Changes look good. It would be great to have Brian, John or Felix also review.

**Comment by lechner** [comment]
@dgarske @douzzer Yeah, I can approve building for `target_os` and adding some backslash escapes. Looks good! :+1:

**Comment by kaleb-himes** [comment]
I'd suggest @BrianAker review as well just in case! 😄

**Comment by douzzer** [comment]
@lechner btw note that the PR _removes_ backslashes in quoted text.  c.f. https://www.mail-archive.com/bug-autoconf@gnu.org/msg04730.html "autoconf-2.70 released [stable]":

```
*** Many macros have become pickier about argument quotation.

  If you get a shell syntax error from your generated configure
  script, or seemingly impossible misbehavior (e.g. entire blocks of
  the configure script not getting executed), check first that all
  macro arguments are properly quoted. The “M4 Quotation” section of
  the manual explains how to quote macro arguments properly.

  It is unfortunately not possible for autoupdate to correct
  quotation errors.
```

**Review by dgarske — APPROVED** [review]

**Pull request merged**
