### PR TITLE
Fix ARMv8 Poly1305 inline assembly code to compile with clang 3.5

### PR DESCRIPTION
**Pull request by SparkiDev**

### CODE REVIEW

**Comment by JacobBarthelmeh** [comment]
please double check the commit author on this before it gets merged into master

**Comment by SparkiDev** [comment]
retest this please

**Comment by SparkiDev** [comment]
retest this please

**Comment by SparkiDev** [comment]
Re-based and forced push the commit again.
Now commit is by Sean Parkinson.

**Pull request merged**
