### PR TITLE
Fix for repeatable build for --enable-sha3

### PR DESCRIPTION
**Pull request by BrianAker**
AC_ARGE_ENABLE was used but the variable it creates was ignored.
AC_ARGE_ENABLE is defined as value given, value not provided. There are a number of places where I believe it is scene around yes/no.
For AS_HELP_STRING and enabled argument has default values of "yes" or "no", not "enabled". Autoconf represents values as [ = ], not " define: ...". There is a number of help strings that don't provide the right value to enable, and are cutoff by the default 80 column formatting.
Use AC_DEFINE, don't try to manipulate AM_CFLAGS, which is an automake variable.
Repeatable builds are broken, which config.status will confirm.
Passed argument was not being checked for valid answer

./configure
./config.status --config | grep sha3
grep "define WOLFSSL_SHA3 1" config.h
./config.status --recheck
./config.status --config | grep sha3

./configure --enable-sha3=small
grep "define WOLFSSL_SHA3 1" config.h
grep "define WOLFSSL_SHA3_SMALL 1" config.h
 ./config.status && ./config.status --config | grep sha3

./configure --enable-sha3
grep "define WOLFSSL_SHA3 1" config.h
./config.status --recheck
./config.status --config | grep sha3

./configure --disable-sha3
grep "define WOLFSSL_SHA3 1" config.h
./config.status --config | grep sha3
./config.status && ./config.status --config | grep sha3
grep "define WOLFSSL_SHA3 1" config.h

./configure --enable-sha3=crud
( this should throw an error )

Note: There is a logic error already around "no" in the SHAKE256; I believe that should have been a test for  != "yes", but I am not wanting to change the logic without better confirmation.

Indention style: I tried to use GNU style, but since the rest of the file is not formatted, I had to hand format lines. My vim style choked on the file ( which... it is not the greatest vim sytle ever written as well )

### CODE REVIEW

**Comment by dgarske** [comment]
Ok to test

**Comment by ejohnstown** [comment]
Does it make sense to add `#include <config.h>` to mcapi/mcapi_test.c? It is missing the WOLFSSL_SHA3 define and with gcc on our Debian jessie machine it is breaking HMAC in MCAPI builds. (It works on other machines, go figure.)

**Comment by BrianAker** [comment]
Right now mcapi/crypto.c is built correctly with config.h but mcapi/mcapi_test.c lacks the file.

So the resulting binary is inconsistent. If the note in options.h is true about injecting/overriding system values via variables… well that will definitely lead to crashes in the resulting binary.

config.h needs to be included in everything being compiled ( in particularly consistently ). 

	— Brian

乌

**Comment by dgarske** [comment]
@BrianAker , what is the status of this PR? There are merge conflicts that need resolved. Several Jenkins jobs reported issues. The `mcapi/crypto.c` is specifically for Microchip and they use the config.h for their build settings. I would not worry about reproducibility fixes in any of the `mcapi/` stuff.
Thanks, David Garske, wolfSSL

**Review by BrianAker — COMMENTED** [review]
It looks great, I cannot speak to the test cases which are failing.

**Comment by dgarske** [comment]
Replaced with https://github.com/wolfSSL/wolfssl/pull/5261

**Pull request closed without merging**
