### PR TITLE
Preserve the order of subject/issuer ASN.1 name components when generating certificates

### PR DESCRIPTION
**Pull request by jspada**

### CODE REVIEW

**Comment by jspada** [comment]
A few notes.

* The sizes for `CTC_MAX_RAW_SIZE` and `ASN_NAME_MAX` were selected to keep things inline with the sizes of `struct CertName`'s members and are not cache aligned, so you may want to revise these.

* The overflow check (`cn->rawLen < decoded->subjectRawLen`) in `SetNameFromCert()` may not be required, depending on what the preceding layers of code do, but I left it in for good measure and so that a (potential) overflow would not be overlooked.

* Refrained from creating new methods for copying the raw ASN.1 sequence (since `subjectRaw` was already there and it's only a few lines of code)...  Similarly, I did not introduce a new function for setting the issuer in `EncodeCert()`, again, because it's only a few lines of code.

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by ejohnstown** [comment]
This isn't a technical problem. It is a licensing/contributor agreement problem.

**Comment by jspada** [comment]
AFAIK the licensing issue should be resolved now.  Could you please stage this patch for inclusion into the next version?

Many thanks,
Joe

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by dgarske** [comment]
Looking like the contributor agreement is in place now, so assigning this to John for review.

**Comment by ejohnstown** [comment]
Joe:

We don't have a contributor agreement from you. I know we've gone over this a few times before, I think it's gotten lost between you and us.

--John

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by ejohnstown** [comment]
I'm closing this due to no movement.

**Pull request closed without merging**
