### PR TITLE
New fail with no peer cert behavior and allow RSA signed ECC key certs

### PR DESCRIPTION
**Pull request by JacobBarthelmeh**
Adds the option to fail out on no peer certs except with PSK cipher suites.
'-j' option with example/server/server.c to test this functionality.
```./example/server/server -j```

Allow for using RSA signed ECC key certs.
On now by default but can be compiled out with the macro WC_STRICT_SIG.
Three files added to certs directory to test this.
```./examples/server/server -c certs/rsa-signed-ecc-cert.pem -k certs/rsa-ecc-key.pem 
./examples/client/client -A certs/rsa-signed-ecc-ca.pem ```

### CODE REVIEW

**Comment by toddouska** [comment]
Thanks, looks good overall.  One suggested change is to remove:
1) rsa-signed-ecc-cert.pem  (we already have server-ecc-rsa.pem)
2) rsa-ecc-key.pem (we already have esc-key.pem)
3) rsa-signed-ecc-ca.pem (we already have ca-cert.pem which is RSA)

And the associated changes in include.am and renewcerts.sh.

Also, shouldn't there be added tests into tests/ .conf to test the ECDHE-ECDSA cipher suites where the peer cert signer is using RSA?  At least a subset of the common ones anyway.

NOTE: tested against OpenSSL and worked as expected with ECDHE-ECDSA  signed with RSA.

**Comment by JacobBarthelmeh** [comment]
Thanks for reviewing the code Todd. Good suggestion and thought of adding to tests/.conf files. Will implement the changes.

**Comment by JacobBarthelmeh** [comment]
New file test-sig.conf was added because of the case when running just test.conf and having the macro WC_STRICT_SIG defined.

Tested ```make distcheck``` with a standard build.

**Comment by JacobBarthelmeh** [comment]
retest this please Jenkins

**Comment by toddouska** [comment]
Great, thanks for the changes.

**Pull request merged**
