### PR TITLE
Generate 64-bit random number for M-R prime test

### PR DESCRIPTION
**Pull request by unseddd**
When `b` is out-of-range for Miller-Rabin primality test, generate random 64-bit number to bring `b` into range

### CODE REVIEW

**Comment by SparkiDev** [comment]
Hi @unseddd 
The code currently generates a new random in the correct range as specified by FIPS 186-4.
Note the count of trials is not modified.
Why would you like us to change the code to generate a 64-bit value?

**Comment by unseddd** [comment]
> The code currently generates a new random in the correct range as specified by FIPS 186-4.

It's entirely possible I'm just misunderstanding the code. When I read this snippet:

```
if (fp_cmp_d(b, 2) != FP_GT || fp_cmp(b, c) != FP_LT) {
    continue
}
```

I understood it as skipping an iteration where `b` was out-of-range. Am I mistaken? If so, should the conditional be removed?

**Comment by SparkiDev** [comment]
The requirement is test n values >2 and <c.
The conditional is forcing a new number to be generated, without modifying the count, if the generated value is not in range.
Conditional should not be removed!

**Comment by unseddd** [comment]
Ok, but it skips an iteration of the loop without performing Miller-Rabin. So, the count isn't modified, but one less iteration is done.

**Comment by unseddd** [comment]
Nevermind... I forgot this was in a while loop, and `t` isn't decremented. Apologies for the noise. :sweat_smile:

**Comment by SparkiDev** [comment]
No worries!
Thanks for your looking into wolfSSL.

**Pull request closed without merging**
