### PR TITLE
Innolectric CMake changes

### PR DESCRIPTION
**Pull request by innolectric**
# Description

slight changes to CMake setup to integrate it into our build. To achieve this we added following variables to control CMake

- "WOLFSSL_INSTALL", encapsulate install target. If CMake install is present it requires every target to be installable. But our targets can not be installed. 
- WOLFSSL_X86_64_BUILD. x86 Assembler code is not build on non-x86-Builds. This way we do not need to integrate additional shell script in build system.
- "WOLFSSL_X86_64_BUILD_ASM" is used within our X86 based software tests. We do have several unit / integration tests that are tested on developer computers directly after cross-compiled binaries are being build. Without this change x86 based builds were not possible.

# Testing

We can build wolfSSL for ARM and X86 platforms

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Comment by dgarske** [comment]
Okay to test. Working on getting contributor agreement setup.

**Comment by kareem-wolfssl** [comment]
FYI - approved contributor agreement on file, see ZD 16728.

**Review by douzzer — APPROVED** [review]

**Comment by dgarske** [comment]
FYI: This breaks `make install` and `cmake --install .`. I suspect MANY CMake users will not like this. 
Took me a few hours to trace down why my wolfTPM CMake test was failing.
Apparently we added a new "WOLFSSL_INSTALL" option? This NEEDS to be clearly documented in the INSTALL file.

**Comment by dgarske** [comment]
@douzzer please resolve.

Either:
Add `-DWOLFSSL_INSTALL=yes` to the INSTALL CMake instructions. 
OR
Change the behavior to default to install and new option to disable the install. Like `-DWOLFSSL_NO_INSTALL=yes`

**Comment by dgarske** [comment]
See: https://github.com/wolfSSL/wolfTPM/pull/329

**Pull request merged**
