### PR TITLE
Add user cert chain DER support and OpenSSL compatibility fixes/improvements

### PR DESCRIPTION
**Pull request by dgarske**
* Added processing of user cert chain in DER format.
* Added arg check on "wolfSSL_get_certificate" to fix NULL dereference if certificate not yet set via "wolfSSL_use_certificate_buffer" or "wolfSSL_use_certificate_file”.
* Added "wolfSSL_CTX_use_certificate_chain_buffer_format" to expose way to import certificate chain buffer as ASN1 (since "wolfSSL_CTX_use_certificate_chain_buffer" assumes PEM).
* Changed ProcessFile from static and added as local in internal.h.
* Added new API "wolfSSL_CIPHER_get_name_from_suite" to allow use of the cipherSuite and cipherSuite0 args directly to get cipher suite name.
* Changed "wolfSSL_CIPHER_get_name" to call new API (based on original). ASN change to allow ToTraditional and SetName for OPENSSL_EXTRA.
* Added "wolfSSL_use_certificate_chain_buffer_format”.
* Added "wolfSSL_SESSION_CIPHER_get_name" to get cipher suite name using WOLFSSL_SESSION*.
* Moved the "wolfSSL_get_cipher_name_from_suite" function to internal.c.

### CODE REVIEW

**Comment by toddouska** [comment]
ProcessBuffer() currently only handles cert chain processing in PEM format.

I think we'd have to:
1) Add a wrapper, ProcessUserChainBuffer()
2) The wrapper determines the DER sz of the first (self) cert and calls ProcessBuffer() with that sz
3) Then the wrapper determines that remaining sz and calls ProcessBuffer() in userChain DER mode
4) Add a new case in ProcessBuffer() for userChain DER that is like the current userChain PEM.

Another solution is to create a ProcessUserChain() wrapper that handles both PEM and DER cases using the above pattern.  That would probably simplify the ProcessBuffer() code.

**Comment by dgarske** [comment]
Good catch. Assign back to me and I'll implement a solution. Thanks!

**Comment by toddouska** [comment]
Kaleb,

When you're back, please add test cases for DER buffer chain cases that will help us validate and maintain these changes.

**Comment by kaleb-himes** [comment]
Todd,

No problem. I'll be working on this as I get time, thank you!

**Comment by kaleb-himes** [comment]
Initial testing started, should be complete by COB today.

**Comment by kaleb-himes** [comment]
Internal testing complete.

**Comment by dgarske** [comment]
@toddouska: This is ready for review. See commit 7be2eed for details on how to test.

**Pull request merged**
