### PR TITLE
tlsx_sni.[ch]

### PR DESCRIPTION
**Pull request by gstrauss**
* put all SNI code behind simpler preprocessor directive HAVE_SNI, replacing more complex, inconsistent preprocessor logic
* split code into separate files: tlsx_base.[ch], tlsx_sni.[ch]
* demonstrate steps towards cleaner code compartmentalization

Collecting and isolating the code leads to simpler audits and more consistent preprocessor directives, which can be more easily audited for consistent use.  Generally speaking, a *.c file with tens of thousands of lines of code is often less maintainable than a set of smaller *.c files which each focus on a more concentrated set of functionality.

Submitting for discussion.  I understand that this merge request might not be accepted.

### CODE REVIEW

**Comment by gstrauss** [comment]
I should clarify something more directly:
**If I build wolfssl with `--enable-sni`, then SNI should work.**
This is not currently true in all cases with the wolfssl complex, inconsistent preprocessor logic.

**Comment by kaleb-himes** [comment]
Jenkins, @gstrauss is an approved contributor, it is ok to test this PR.

**Comment by kaleb-himes** [comment]
Hi @gstrauss,

Here are some of the logs if it is helpful:

From test "Enable Options part A" (NOTE: Other configure options tests have a similar log with different configure combinations):

```
./configure --enable-jobserver=4 --enable-tls13-draft18
make[2]: warning: -jN forced in submake: disabling jobserver mode.
src/tls.c: In function ‘TLSX_FreeAll’:
src/tls.c:8453:9: error: enumeration value ‘TLSX_SERVER_NAME’ not handled in switch [-Werror=switch]
         switch (extension->type) {
         ^
src/tls.c: In function ‘TLSX_GetSize’:
src/tls.c:8585:9: error: enumeration value ‘TLSX_SERVER_NAME’ not handled in switch [-Werror=switch]
         switch (extension->type) {
         ^
src/tls.c: In function ‘TLSX_Write’:
src/tls.c:8736:9: error: enumeration value ‘TLSX_SERVER_NAME’ not handled in switch [-Werror=switch]
         switch (extension->type) {
         ^
src/tlsx_base.c: In function ‘TLSX_Push’:
src/tlsx_base.c:73:16: error: ‘MEMORY_E’ undeclared (first use in this function)
         return MEMORY_E;
                ^
src/tlsx_base.c:73:16: note: each undeclared identifier is reported only once for each function it appears in
src/tlsx_base.c: In function ‘TLSX_Prepend’:
src/tlsx_base.c:111:16: error: ‘MEMORY_E’ undeclared (first use in this function)
         return MEMORY_E;
                ^
src/tlsx_base.c: In function ‘TLSX_HandleUnsupportedExtension’:
src/tlsx_base.c:151:12: error: ‘UNSUPPORTED_EXTENSION’ undeclared (first use in this function)
     return UNSUPPORTED_EXTENSION;
            ^
src/tlsx_base.c:152:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
```

From test "PRB ABI test":

```
./configure --disable-dependency-tracking --disable-shared --enable-alpn --enable-sni --enable-tls13
...
src/internal.c: In function ‘DoClientHello’:
src/internal.c:27872:25: error: implicit declaration of function ‘SNI_Callback’ [-Werror=implicit-function-declaration]
                 if((ret=SNI_Callback(ssl)))
                         ^~~~~~~~~~~~
src/internal.c:27872:25: error: nested extern declaration of ‘SNI_Callback’ [-Werror=nested-externs]
cc1: all warnings being treated as errors
Makefile:5050: recipe for target 'src/src_libwolfssl_la-internal.lo' failed
make: *** [src/src_libwolfssl_la-internal.lo] Error 1
```

Those appear to be the two consistent errors throughout the tests, if there are more after those are fixed I will try to get you logs.

Warm Regards,

K

**Comment by gstrauss** [comment]
Pushed changes with above warnings and errors fixed.
The declaraction of `SNI_Callback()` needed `HAVE_SNI` instead of other preproc directives
The missing defines were fixed with a missing `#include`
The unhandled `switch` cases were fixed by adding a `default` case.

**Comment by gstrauss** [comment]
```
       -Wswitch-enum
           Warn whenever a "switch" statement has an index of enumerated type and lacks a "case" for one or more of the named codes of that enumeration.  "case" labels outside the enumeration range also provoke warnings when this option is used.  The only difference between -Wswitch and this option is that
           this option gives a warning about an omitted enumeration code even if there is a "default" label.
```

The tests are still failing due to `-Wswitch-enum`.  I'll make a small modification instead of adding a default case.

**Comment by gstrauss** [comment]
Most checks are now passing.  Two test failures are not reproducible by me (race conditions in the test?)

`--enable-cryptonly --enable-opensslextra` is a questionable combination.  I'll see where to add more `#ifndef WOLFCRYPT_ONLY`.  ... It might be better if --enable-cryptonly `#undef` other feature defines.

**Comment by kaleb-himes** [comment]
> Most checks are now passing. Two test failures are not reproducible by me (race conditions in the test?)
> 
> `--enable-cryptonly --enable-opensslextra` is a questionable combination. I'll see where to add more `#ifndef WOLFCRYPT_ONLY`. ... It might be better if --enable-cryptonly `#undef` other feature defines.

Glenn, because we support additional features in "certificate processing" (asn.c) that aren't available without OpenSSL extra and we have many customers that still create, parse and use certificates and keys when not doing TLS (firmware updates etc) we do want to make sure opensslextra with wolfcrypt_only still works correctly with the wc_ (wolfcrypt level) APIs'.

I did see one failure I couldn't reproduce on my work station but if needed I can log into the actual test rigs and see what's happening if there is something failing consistently that isn't reproducible.

We test with multiple compilers and OS's so it might be something specific to the environment, let me know if there is a specific one you need me to look into!

Warm Regards,

K

**Comment by gstrauss** [comment]
@kaleb-himes now that the SNI code has been collected, and a basic pattern established for isolating the code for other TLS extensions, is doing so of interest to the wolfssl team?

It is now much easier to see that `SNI_Callback()` is executed only when `defined(HAVE_SNI)` and `!defined(NO_WOLFSSL_SERVER)`.  Therefore, when `defined(NO_WOLFSSL_SERVER)`, should these members NOT EXIST  in WOLFSSL_CTX?
```
    CallbackSniRecv sniRecvCb;
    void*           sniRecvCbArg;
```
and should these functions also NOT EXIST?
```
typedef int (*CallbackSniRecv)(WOLFSSL *ssl, int *ret, void* exArg);

WOLFSSL_API void wolfSSL_CTX_set_servername_callback(WOLFSSL_CTX *,
        CallbackSniRecv);
WOLFSSL_API int wolfSSL_CTX_set_tlsext_servername_callback(WOLFSSL_CTX *,
        CallbackSniRecv);

WOLFSSL_API int  wolfSSL_CTX_set_servername_arg(WOLFSSL_CTX *, void*);
```
Also, should
```
WOLFSSL_API int wolfSSL_CTX_set_tlsext_servername_callback(WOLFSSL_CTX *,
        CallbackSniRecv);
```
only be defined when `OPENSSL_EXTRA`, since that is a compatibility interface for the openssl API, and is duplicative of the wolfSSL interface `wolfSSL_CTX_set_servername_callback()`?

**Comment by kaleb-himes** [comment]
--------

> now that the SNI code has been collected, and a basic pattern established for isolating the code for other TLS extensions, is doing so of interest to the wolfssl team?

Glenn, I will go over it with the team in tomorrows' meeting and send the teams feedback.
(My personal input: I see the benefits of the design changes and I personally think it is an excellent design refactor. My only note would be it is a significant design refactor that we would want to vet thoroughly before deploying so I think it would be best to consider these for merge AFTER the upcoming release next week so these changes get the full 2-3 month testing treatment and fuzzing between now and the next release in March 2021)

--------

> It is now much easier to see that SNI_Callback() is executed only when defined(HAVE_SNI) and !defined(NO_WOLFSSL_SERVER). Therefore, when defined(NO_WOLFSSL_SERVER), should these members NOT EXIST in WOLFSSL_CTX?
>
>```
>    CallbackSniRecv sniRecvCb;
>    void*           sniRecvCbArg;
>```
>
> and should these functions also NOT EXIST?
>
>```
>typedef int (*CallbackSniRecv)(WOLFSSL *ssl, int *ret, void* exArg);
>
> WOLFSSL_API void wolfSSL_CTX_set_servername_callback(WOLFSSL_CTX *,
>        CallbackSniRecv);
>WOLFSSL_API int wolfSSL_CTX_set_tlsext_servername_callback(WOLFSSL_CTX *,
>        CallbackSniRecv);
>
> WOLFSSL_API int  wolfSSL_CTX_set_servername_arg(WOLFSSL_CTX *, void*);
>```

Oh absolutely, anytime we can reduce memory (remove items from a structure) or exclude unnecessary code (save the compiler time in optimizing it out) that is always a good practice. Not one we always achieve perfectly but yes if the prototypes and structure elements are not necessary one can wrap them in the appropriate ifdefs'.

--------

> Also, should
>
> WOLFSSL_API int wolfSSL_CTX_set_tlsext_servername_callback(WOLFSSL_CTX *,
>         CallbackSniRecv);
> only be defined when OPENSSL_EXTRA, since that is a compatibility interface for the openssl API, and is duplicative of the wolfSSL interface wolfSSL_CTX_set_servername_callback()?

Agreed, if the wrapper is not used it can be excluded with an ifdef wrapper.

Warm Regards,

K

**Comment by gstrauss** [comment]
> My only note would be it is a significant design refactor that we would want to vet thoroughly before deploying so I think it would be best to consider these for merge AFTER the upcoming release next week so these changes get the full 2-3 month testing treatment and fuzzing between now and the next release in March 2021

That makes sense for the refactoring.  The code was moved mostly intact, with minor changes to some internal function signatures and modifications to preprocessor wrappings, but it is still a large change and so should not be rushed.

What about the first three commits?  If I split those out into a separate pull request, that pull request will be a much smaller change set for HAVE_SNI.  Would that be reviewable for possible inclusion in the upcoming release?

**Comment by gstrauss** [comment]
`<p>Build duration: 3 hr 14 min </p>`

Has the wolfssl team considered that the tests taking this long might have some race conditions that cause them to spin for a very long time before (possibly) finishing after some minor perturbation?  Are there any tests that should take longer than a few minutes?  (I have seen some tests spin, and when I run them manually, they finish sucessfully in under a minute, e.g. `./testsuite/testsuite.test`)

**Comment by kaleb-himes** [comment]
Team Notes:

Understand consolidating the code and cleaning it up but request that it be grouped inside tls.c to avoid adding new files. (Team foresees changes like this could lead to a cascade of requested refactors to break out items)

On test spinning: Our back-ends are limited and when multiple PRs' are being tested at once some will sit in the queue for some time before actually starting. Others can be blocked (There are a limited number of ports on any given back-end and we run thousands of connection tests, each has to wait for a port to be available to run it's test which can lead to congestion). We have discussed a refactor to use the custom I/O callback routines and move the TLS connection tests to an in-memory test keeping only a small number of network tests requiring TCP/IP ports/sockets for testing but that refactor has not yet been scheduled or approved by management.

If you want to split out the first three commits before new files were added yes that could have a potential to make the release. The release cycle kicks off Monday from what I hear so the sooner the better to get it reviewed in time!

- K

**Comment by gstrauss** [comment]
> Understand consolidating the code and cleaning it up but request that it be grouped inside tls.c to avoid adding new files. (Team foresees changes like this could lead to a cascade of requested refactors to break out items)

Yes.  That is the point.  Parallel compilation is faster, git history is faster, code for a specific bit of functionality is collected, interfaces to that specific functionality are more obvious, etc etc etc.  What are the "benefits" or "advantages" of a single tls.c file consistenting of 11842 lines of code?  My proposed modifications slightly change `internal.h` but do not change public interfaces.

> If you want to split out the first three commits before new files were added yes that could have a potential to make the release. The release cycle kicks off Monday from what I hear so the sooner the better to get it reviewed in time!

Will do shortly, as a separate PR.  I would like to leave this one as-is for the moment, and to continue the discussion for potential inclusion in a future release.  Thanks.

**Comment by gstrauss** [comment]
I filed #3548 with the first part of this pull request, and I re-titled this pull request.

**Comment by gstrauss** [comment]
>> Understand consolidating the code and cleaning it up but request that it be grouped inside tls.c to avoid adding new files. (Team foresees changes like this could lead to a cascade of requested refactors to break out items)

> Yes. That is the point. Parallel compilation is faster, git history is faster, code for a specific bit of functionality is collected, interfaces to that specific functionality are more obvious, etc etc etc. What are the "benefits" or "advantages" of a single tls.c file consisting of 11842 lines of code? My proposed modifications slightly change internal.h but do not change public interfaces.

@kaleb-himes What are the WolfSSL teams' concerns with multiple files?  I am not suggesting 1,000 files each with 10 lines.  I am suggesting that if **each TLS extension** were a standalone file, reading the code would be simpler, unit testing would be more straightforward, compilation would be faster, git history would be faster, writing new extensions would be more isolated, other modifications would not touch these files, ... (I could go on).  There are already multiple files in `src/` so the wolfssl build system(s) on different platforms already handle this.

**Comment by gstrauss** [comment]
>> Understand consolidating the code and cleaning it up but request that it be grouped inside tls.c to avoid adding new files. (Team foresees changes like this could lead to a cascade of requested refactors to break out items)

> Yes. That is the point. Parallel compilation is faster, git history is faster, code for a specific bit of functionality is collected, interfaces to that specific functionality are more obvious, etc etc etc. What are the "benefits" or "advantages" of a single tls.c file consisting of 11842 lines of code? My proposed modifications slightly change internal.h but do not change public interfaces.

@kaleb-himes What are the WolfSSL teams' concerns with multiple files?  I am not suggesting 1,000 files each with 10 lines.  I am suggesting that if **each TLS extension** were a standalone file, reading the code would be simpler, unit testing would be more straightforward, compilation would be faster, git history would be faster, writing new extensions would be more isolated, other modifications would not touch these files, ... (I could go on).  There are already multiple files in `src/` so the wolfssl build system(s) on different platforms already handle this.

**Comment by dgarske** [comment]
Hi @gstrauss ,

The main issue with adding more files is the difficulty that causes when a user upgrades wolfSSL versions. Many compilers and build setups are not including *.c, so customers end up having to make changes to support this. Also if we do add files it should be for new features and also have to add them to several other places such as the CMakeList.txt and the VisualStudio projects.

I totally understand the desires to split out the TLS extensions as you have done, however it is unlikely this change will get accepted. Is it possible you can accomplish the goal of having the `HAVE_SNI` code together in the existing file?

Thanks,
David Garske, wolfSSL

**Comment by gstrauss** [comment]
> Many compilers and build setups are not including *.c, so customers end up having to make changes to support this.

I do not understand.  If you do not include the .c file, then how do they compile the current .c files?

If there were some independent, hard-coded list of files, or the wolfssl team provided only object code, then wolfssl team can simply concatenate the new files to the end of (likely) `src/internal.c` before special packaging for those customers.

> Also if we do add files it should be for new features and also have to add them to several other places such as the CMakeList.txt and the VisualStudio projects.

Have you looked at the proposed diff?  I have included trivial changes for
```
cmake/functions.cmake 
rpm/spec.in
src/include.am
wolfssl/include.am
wolfssl-ntru.vcproj   
wolfssl.vcproj
wolfssl.vcxproj
```

**Comment by gstrauss** [comment]
rebased and all wolfssl CI checks pass: 27 successful checks.

**Comment by kaleb-himes** [comment]
@gstrauss I just wanted to reach out today and let you know that your feedback via @julek-wolfssl has reached a wider audience and we will be re-viewing this PR with fresh eyes over the next 1-2 weeks. Someone from our team (or myself) will provide definitive feedback once the internal discussions have concluded OR we will let you know if they go longer than 2 weeks. We sincerely apologize for the time that has lapsed on this so far!

All the best,

- Kaleb & the wolfSSL Team

**Comment by gstrauss** [comment]
Thanks for the update @kaleb.  I had misunderstood @dgarske :
>>  Many compilers and build setups are not including *.c, so customers end up having to make changes to support this.

> I do not understand. If you do not include the .c file, then how do they compile the current .c files?

@julek-wolfssl told me more clearly that customers might manually have to update the file list for inclusion of wolfssl into *their* builds.  Another solution might be a policy approach: e.g. no file list changes in wolfssl patch releases (x.x.x), but allowed in minor (x.x.0) releases, possibly along with guidance to customers that file list changes will only happen once or twice a year.

**Comment by gstrauss** [comment]
Another option: a preprocessor define wrapping include of .c files into one of the original .c files, as I mentioned further above,
e.g. in `src/tls.c`
```
#ifdef WOLFSSL_COMBINED_C_FILES_FOR_BUILD_SYSTEMS_WITH_MANUAL_FILE_LISTS
#include "tlsx_base.c"
#include "tlsx_sni.c"
#endif
```
That might help some customers who might not have the resources to have someone spend 60 seconds (<sigh>) updating Makefiles after downloading a new wolfssl release and reading the release notes.  It won't address fragile build systems which are coded to individually pick a (short) list of files from the wolfssl release.  Those file lists will have to be updated.  I understand the desire to minimize changes needed for customers to integrate updates.  That's all well and good.  If it were necessary to address this to make it easier for customers, then the wolfssl packaging process could combine `src/tlsx_*.c` into `src/tls.c` to create a special package for customers who are unable or do not want to modify file lists.

Before pondering further, I'll wait for your updates.  Is this file list limitation only for `*.c` files?  Does it include `*.h` files?  That might help determine what approaches are taken to address the file list limitation.

**Comment by kaleb-himes** [comment]
Glenn,

Exactly, I am glad Juliusz was able to help clarify. Internally when talking amongst ourselves when we see `*.c` we tend to read that as "wild-card dot c", I suspect this was an "internal wolfssl to external wolfssl language barrier" and we do apologize. Yes, David was attempting to convey that MANY customers don't use a wild-card to include every C file in a directory and therefore they will see build errors immediately upon introducing new files that contain OLD logic. We tend to only introduce new files with new features so that we know for certain we are not breaking existing use-cases when the new file comes out. Whenever we are talking about moving existing functionality to new files that is when things become "sticky" to get through the review process.

Anytime we add new source files and put existing logic into those files, end users experience build issues pulling in a  new release (which can lead to hesitancy to update which can lead to running with vulnerabilities if the latest release fixed a vulnerability while at the same time introducing new dependency files). Since we are providing a "Security" solution there are many nuances that apply to our library that do NOT apply to other similar type projects. We must consider these nuances before forcing something new on our users both open-source and commercial alike.

Open source projects can typically adapt to changes with ease where we have multiple commercial customers that have to do months of testing on anything new which can severely impacted those customers release process. The changes you have proposed, we ALL like! In the initial internal discussions everyone loves your proposals but as soon as we begin to discuss how it will impact specific customers and their release process that is where we keep hitting a wall on advancing this PR.

There is a way to do this by starting out with lots of advanced warnings and hints of the coming change before implementing and those avenues are what we are beginning to explore when considering this PR.

Warm Regards,

Kaleb

**Comment by kaleb-himes** [comment]
> Before pondering further, I'll wait for your updates. Is this file list limitation only for *.c files? Does it include *.h files? That might help determine what approaches are taken to address the file list limitation.

Header files are similarly effected. The goal for us is typically that a user can download the new release and without making any changes to their application or build process, pull in the release seamlessly. This helps to ensure the "trust" aspect in a security solution. Now granted this is not (and never will be) a perfect world, there are times when it becomes necessary to implement a change to the detriment of the end user, we just hope to mitigate the impact as much as possible whenever possible.

Warm Regards,

K

**Comment by gstrauss** [comment]
Where I had misunderstood @dgarske was in how it might affect customers.

You see, I have extensive professional experience with many different build systems, including cross-compilation.  If a customer is building against the wolfssl shared library, then the wolfssl-provided build systems should be used to build the shared library.  If a customer is building against wolfssl as a static library for inclusion in their application, I have a hard time imagining why any solution would be better than **using the wolfssl-provided build to create a static archive** and linking against that `.a`.  Also, I would consider any build system broken if it was unable to use the `include/wolfssl/*` installation location of a `make install` (or equivalent) of the wolfssl `.a` and header files.  I'm sure that there are other backwards systems out there, but I don't have a high opinion of them.

**Comment by kaleb** [comment]
> Thanks for the update @kaleb. I had misunderstood @dgarske :
> 
> > > Many compilers and build setups are not including *.c, so customers end up having to make changes to support this.
> 
> > I do not understand. If you do not include the .c file, then how do they compile the current .c files?
> 
> @julek-wolfssl told me more clearly that customers might manually have to update the file list for inclusion of wolfssl into _their_ builds. Another solution might be a policy approach: e.g. no file list changes in wolfssl patch releases (x.x.x), but allowed in minor (x.x.0) releases, possibly along with guidance to customers that file list changes will only happen once or twice a year.

Wrong guy you are mentioning

**Comment by kaleb-himes** [comment]
@gstrauss,

A fair critique however I would note that the critique assumes our goal is to only support systems where a "library" is built. I must stress that while wolfSSL is very proud to support modern systems, our roots however are in the embedded space. 

wolfSSL is to be small enough, and fast enough to run on embedded and IoT edge devices. Inadvertently that is why it scales exceptionally well on backend systems due to low run-time resource use and a small footprint, larger systems can often service more connections per box using a library designed for embedded use!

Many wolfSSL users do not use configure, CMake, or some other build process that results in a "library". Many wolfSSL users are building in MPLabx IDE, LPCExpresso IDE, Atollic IDE,  IAR EWARM, Arduino ... <insert any other IDE for embedded systems> and so on. It is very common for these build systems to pull in the source files they need for the project and build a single binary image without ever composing a library. It is very common that a "make install" does not occur on such build systems if that makes sense?

Warm Regards,

K

**Comment by kaleb-himes** [comment]
Status Update:

This PR lead to an in-depth internal conversation regarding the break up of ssl.c both in reference to this PR and the OpenSSL compatibility layer code.

The current concensus is to table this discussion until the annual all-hands meeting in Jan of 2022 at which time we will re-visit the topic of breaking up ssl.c and introducing new source files. The discussion in January 2022 will cover both this PR and the OpenSSL compatibility layer which could use a breakout to reduce the size and complexity of ssl.c.

- KH

**Pull request closed without merging**
