### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by fos9191**
# Description

Fixed small grammer typo in READMEs.

# Testing

No testing needed

### CODE REVIEW

**Comment by embhorn** [comment]
Hi @fos9191 

Thanks for your interest in wolfSSL. Can you tell us a bit about your project? 

We do not typically accept small changes like this. Do you anticipate making any more significant updates? Otherwise I can just get these into another PR.

Kind regards,
@embhorn - wolfSSL Support

**Comment by fos9191** [comment]
Hey @embhorn,

I'm doing my thesis on a QUIC/HTTP3 implementation on Embedded Systems and was just having a look at wolfSSL on ESP32s today and noticed the typo. I don't anticipating making any significant changes.

Kind regards,
Fionnan

**Comment by embhorn** [comment]
@fos9191 
Thanks for sharing those details. Sounds like a very interesting project!

@gojimmypi 
I've assigned this to you. Please incorporate these changes in a PR of your own. Afterwards this PR may be be closed.

**Comment by dgarske** [comment]
These were fixed in #8076 and merged. Closing PR. Thank you @fos9191

**Pull request closed without merging**
