### PR TITLE
Fix typo with armv8-aes wc_AesInit function

### PR DESCRIPTION
**Pull request by dgarske**

### CODE REVIEW

**Comment by dgarske** [comment]
This PR #852 and PR #858 need to get into master to resolve build errors, which are causing failures. @toddouska : requested override / review to get these fixes into master. Thanks.

**Comment by toddouska** [comment]
Why did these suddenly show up?

**Comment by dgarske** [comment]
Distro added scrypt, which apparently wasn't in the Jenkins scripts. And the armv8 I'm guessing only runs on master, not PRs.

**Comment by dgarske** [comment]
Closing this PR. Moved fix to PR #858.

**Pull request closed without merging**
