### PR TITLE
For NO_RSA, don't advertise support for RSA.

### PR DESCRIPTION
**Pull request by anhu**
Fixes https://github.com/wolfSSL/wolfssl/issues/6451

Tested with: 
`--disable-rsa --enable-dtls`

### CODE REVIEW

**Review by JacobBarthelmeh — APPROVED** [review]

**Review by dgarske — APPROVED** [review]

**Comment by maxgerhardt** [comment]
1. Applying only the change in `internal.c` already successfully removed the `rsa_pkcs1_sha*` cipersuites for me, is the `tls.c` change a leftover from the first try?
2. This just disables lots of tests. Why would it be impossible to e.g. do `test_WOLFSSL_dtls_version_alert` when RSA is disabled? Those things should be independent, no?

image

**Comment by anhu** [comment]
Hello @maxgerhardt , 

1. You are correct, it is not required to guard with `NO_RSA` to get the correct results.  But that said, it is also true that `TLSX_SignatureAlgorithms_MapPss()` does not need to be executed when RSA is disabled. So, this can be thought of as an optimization. 
2. Yes, some tests get disabled. The  tests require a lot more investigation as to how to keep them enable while RSA is disabled.  At this time, it is not a priority to do this investigation.  It will be re-prioritized at a later date.  For Now, we disable the relevant tests when RSA is disabled. 

Hope this helps. 
Warm regards, Anthony

**Comment by JacobBarthelmeh** [comment]
@anhu please follow up with opening a pull request on our testing repo. for a PRB enable addition (something like --enable-dtls --disable-rsa), thanks

**Comment by anhu** [comment]
@JacobBarthelmeh,  @douzzer will be doing it.

**Pull request merged**
