### PR TITLE
Test api.c: change more tests to use Expect instead of Assert

### PR DESCRIPTION
**Pull request by SparkiDev**
# Description

    bio.c:
      wolfSSL_BIO_flush(): check allocation to bio->ip succeeded.
    
    internal.c:
      InitSSL_Ctx(): set ctx->heap to heap if value passed in
    ProcessPeerCerts(): check for error MEMORY_E too as a fatal parsing
    error
    
    ssl.c:
    wolfSSL_shutdown(): SOCKET_ERROR_E is also an indication that the
    socket is done, MEMORY_E is a fatal error
      wolfSSL_Cleanup(): move free of memory fail couting to wolfSSL API
      SessionTicketNoncePrealloc(): eror return must be non-zero
    AddSessionToCache(): XFREE checks for NULL no need to do it before
    call
    wolfSSL_set_psk_use_session_callback(): ensure ssl is not NULL before
    dereferencing
    wolfSSL_SMIME_read_PKCS7(): check for error return from
    wolfSSL_BIO_gets()
    
    asn.c:
      wc_MIME_parse_headers(): check allocation succeeded into nextHdr
    
    compress.c:
      wc_DeCompressDynamic(): free tmp on inflateInit2 failure
    
    memory.c: rework where memory allocation failure counting code for when
    WOFLSSL_STATIC_MEMORY is defined
    
  wc_port.c:
    wolfCrypt_Cleanup(): only call wc_MemFailCount_Free() when no
    wolfSSL_Cleanup()

# Testing

Memory allocation failure testing as well.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Comment by SparkiDev** [comment]
retest this please

**Comment by SparkiDev** [comment]
retest this please

**Review by dgarske — CHANGES_REQUESTED** [review]
```tests/api.c: In function ‘_test_wolfSSL_dtls_stateless_resume’:
tests/api.c:58157:39: error: ‘WOLFSSL_SESSION’ has no member named ‘ticket’
58157 |     if (bad && (sess != NULL) && (sess->ticket != NULL)) {
      |                                       ^~
make[2]: *** [Makefile:7079: tests/unit_test-api.o] Error 1```

**Comment by SparkiDev** [comment]
Fixed check of sess->ticket to be in #ifdef

**Review by dgarske — CHANGES_REQUESTED** [review]
```    build...tests/api.c: In function ‘test_wc_PKCS7_EncodeSignedData’:
tests/api.c:22621:5: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
22621 |     WC_RNG rng;
      |     ^~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:7075: tests/unit_test-api.o] Error 1
```

**Comment by SparkiDev** [comment]
fixed

**Review by dgarske — APPROVED** [review]

**Pull request merged**
