### PR TITLE
Tls13 updates

### PR DESCRIPTION
**Pull request by SparkiDev**
Improve PSK timeout checks
Add Post-handshake Authentication - not compiled by default.
Fix KeyUpdate to derive keys properly (interop with OpenSSL found issue)
Fix supported curves (not checking ctx extensions)

### CODE REVIEW

**Comment by toddouska** [comment]
Sean, can you fix up the merge conflicts please?

**Comment by dgarske** [comment]
I went ahead and did a rebase -> force push on this branch for Sean. The merge conflicts were due to the TLS async changes I made. All good now.

**Comment by dgarske** [comment]
FYI: Just did another rebase -> force push to resolve conflict in benchmark.c.

**Comment by dgarske** [comment]
FYI: Did another rebase -> force push to resolve merge conflict with PR #963.

**Pull request merged**
