### PR TITLE
AES XTS x64 ASM: add AVX1 and AESNI implementations

### PR DESCRIPTION
**Pull request by SparkiDev**
# Description

Adding AES-XTS AVX1 and AESNI implementations.
Fix name in comment at top of x64 assembly files.

# Testing

Tested with and without xts and intelasm.

# Checklist

 - [x] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Comment by SparkiDev** [comment]
retest this please

**Review by douzzer — APPROVED** [review]
Looks great.  Performance is as hoped for:
```
AES-XTS-enc               5160 MiB took 1.001 seconds, 5155.927 MiB/s Cycles per byte =   0.63
AES-XTS-dec               5160 MiB took 1.001 seconds, 5156.762 MiB/s Cycles per byte =   0.63
```
and tests good loaded in the kernel, including kernel sanitizer:
```
[linuxkm-aesni-ksanitize-insmod] [1 of 2] [62481293ae]
    autogen.sh 62481293ae...   real 0m16.394s  user 0m14.380s  sys 0m1.151s
    configure...   real 0m9.814s  user 0m4.628s  sys 0m6.148s
    build...warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Gentoo 11.3.1_p20230427 p9) 11.3.1 20230427
  You are using:           gcc (Gentoo 12.3.1_p20230825 p2) 12.3.1 20230825
   real 0m30.510s  user 1m47.309s  sys 0m14.381s
    dracut...   real 0m16.023s  user 0m14.206s  sys 0m2.123s
    boot and insmod with self-test...done.
    [  350.338507] insmod (667) used greatest stack depth: 22312 bytes left
    linuxkm-aesni-ksanitize-insmod OK
[linuxkm-mainline-aesni-pie-gcc-latest-insmod] [2 of 2] [62481293ae]
    [targeting kernel /usr/src/linux-6.6-rc3]
    configure...   real 0m10.238s  user 0m4.737s  sys 0m6.572s
    build...warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Gentoo 12.3.1_p20230825 p2) 12.3.1 20230825
  You are using:           gcc-13 (Gentoo 13.2.1_p20230826 p7) 13.2.1 20230826
   real 0m16.002s  user 1m1.092s  sys 0m12.110s
    dracut...   real 0m11.856s  user 0m9.966s  sys 0m2.132s
    boot and insmod with self-test...done.
    [   68.798037] insmod (1195) used greatest stack depth: 9944 bytes left
    linuxkm-mainline-aesni-pie-gcc-latest-insmod OK
```
Changes in C files all look good.  I ran my eyes over the asm but I'm basing my approval strictly on the automated test results :wink:

**Comment by douzzer** [comment]
Jenkins, retest this please.

**Review by JacobBarthelmeh — APPROVED** [review]
Nice! Looks good

**Pull request merged**
