### PR TITLE
Aarch64: make code compile when no hardware crypto avail

### PR DESCRIPTION
**Pull request by SparkiDev**
Description

Detects availability of instructions for Aarch64.

## Testing

With and without WOLFSSL_ARMASM_NO_HW_CRYPTO

```
./configure --enable-armasm CFLAGS="-DWOLFSSL_ARMASM_NO_HW_CRYPTO" && make check
```

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Review by dgarske — CHANGES_REQUESTED** [review]
Tested on Rpi4 that does not support aes/sha instructions.

```
./configure --enable-armasm && make
$ ./wolfcrypt/test/testwolfcrypt
Math: 	Multi-Precision: Wolf(SP) word-size=64 bits=4096 sp_int.c
------------------------------------------------------------------------------
 wolfSSL version 5.7.4
------------------------------------------------------------------------------
error    test passed!
MEMORY   test passed!
base64   test passed!
asn      test passed!
Illegal instruction
```

```
./configure --enable-armasm CFLAGS="-DWOLFSSL_ARMASM_NO_HW_CRYPTO" && make
  CCLD     src/libwolfssl.la
/usr/bin/ld: wolfcrypt/src/port/arm/.libs/src_libwolfssl_la-armv8-aes.o: in function `wc_AesSetIV':
armv8-aes.c:(.text+0x100): multiple definition of `wc_AesSetIV'; wolfcrypt/src/.libs/src_libwolfssl_la-aes.o:aes.c:(.text+0x1620): first defined here
/usr/bin/ld: wolfcrypt/src/port/arm/.libs/src_libwolfssl_la-armv8-aes.o: in function `wc_AesSetKey':
armv8-aes.c:(.text+0x148): multiple definition of `wc_AesSetKey'; wolfcrypt/src/.libs/src_libwolfssl_la-aes.o:aes.c:(.text+0x1668): first defined here
/usr/bin/ld: wolfcrypt/src/port/arm/.libs/src_libwolfssl_la-armv8-aes.o: in function `wc_AesCbcEncrypt':
armv8-aes.c:(.text+0x230): multiple definition of `wc_AesCbcEncrypt'; wolfcrypt/src/.libs/src_libwolfssl_la-aes.o:aes.c:(.text+0x1e18): first defined here
/usr/bin/ld: wolfcrypt/src/port/arm/.libs/src_libwolfssl_la-armv8-aes.o: in function `wc_AesCbcDecrypt':
armv8-aes.c:(.text+0x2a8): multiple definition of `wc_AesCbcDecrypt'; wolfcrypt/src/.libs/src_libwolfssl_la-aes.o:aes.c:(.text+0x1f78): first defined here
/usr/bin/ld: wolfcrypt/src/port/arm/.libs/src_libwolfssl_la-armv8-aes.o: in function `GenerateM0':
armv8-aes.c:(.text+0x320): multiple definition of `GenerateM0'; wolfcrypt/src/.libs/src_libwolfssl_la-aes.o:aes.c:(.text+0x2f70): first defined here
/usr/bin/ld: wolfcrypt/src/port/arm/.libs/src_libwolfssl_la-armv8-aes.o: in function `wc_AesGcmSetKey':
armv8-aes.c:(.text+0xb60): multiple definition of `wc_AesGcmSetKey'; wolfcrypt/src/.libs/src_libwolfssl_la-aes.o:aes.c:(.text+0x37b0): first defined here
/usr/bin/ld: wolfcrypt/src/port/arm/.libs/src_libwolfssl_la-armv8-aes.o: in function `wc_AesGcmEncrypt':
armv8-aes.c:(.text+0xbf8): multiple definition of `wc_AesGcmEncrypt'; wolfcrypt/src/.libs/src_libwolfssl_la-aes.o:aes.c:(.text+0x3878): first defined here
/usr/bin/ld: wolfcrypt/src/port/arm/.libs/src_libwolfssl_la-armv8-aes.o: in function `wc_AesGcmDecrypt':
armv8-aes.c:(.text+0xf60): multiple definition of `wc_AesGcmDecrypt'; wolfcrypt/src/.libs/src_libwolfssl_la-aes.o:aes.c:(.text+0x3c28): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:6383: src/libwolfssl.la] Error 1
```

**Comment by SparkiDev** [comment]
Need to specify WOLFSSL_ARMASM_NO_HW_CRYPTO to force compilation without.
Alternatively, it will detect based on which mechanism you use to detect availability of instructions.
Defining WOLFSSL_AARCH64_PRIVILEGE_MODE means app can use the "mrs" instruction.
Otherwise it has to go on build flags if not a know OS.

**Comment by dgarske** [comment]
> Need to specify WOLFSSL_ARMASM_NO_HW_CRYPTO to force compilation without use of hardware crypto instructions. It will detect instructions availability based on supported OSes. You don't have an OS, so, if you have the "mrs" instruction available then define WOLFSSL_AARCH64_PRIVILEGE_MODE. Otherwise it has to go on build flags.

The second test uses `WOLFSSL_ARMASM_NO_HW_CRYPTO` and gets duplicate symbols.

**Review by dgarske — DISMISSED** [review]
This works wonderfully now! Anyway to get `WOLFSSL_ARMASM_NO_HW_CRYPTO` as a configure option??

**Comment by SparkiDev** [comment]
Added --enable-armasm=no-crypto

**Review by dgarske — APPROVED** [review]

**Comment by douzzer** [comment]
note, reverted by #8290, then merged again after rework as #8293

**Pull request merged**
