### PR TITLE
when dropping a DTLS message, drop the whole datagram

### PR DESCRIPTION
**Pull request by ejohnstown**
Fixes an issue found with extended fuzz testing.

### CODE REVIEW

**Comment by ejohnstown** [comment]
retest please

**Comment by ejohnstown** [comment]
Test this please Jenkins.

**Comment by cconlon** [comment]
Assigning back to John to investigate Kaleb's fuzzer findings.

**Comment by kaleb-himes** [comment]
relates to https://github.com/wolfSSL/wolfFuzz/commit/71c0aff6b03bbbec5a4ead4b1444a8226a0e4e9a

**Comment by kaleb-himes** [comment]
relates to PR 4 in private repo see Commits from ejohnstown on fuzzer project

**Comment by kaleb-himes** [comment]
Looks good in my local fuzzer John. Thanks for the hard work on this. Let's let Jenkins have a go the reset of the weekend. Great work!

**Pull request merged**
