### PR TITLE
Fixed scripts/benchmark.test, replaced == with -eq

### PR DESCRIPTION
**Pull request by shihrer**
Just replaced instances of "==" with "-eq" on lines 55, 63, 78, and 87.  Needed to run the script since == is an alias for a string comparison.

### CODE REVIEW

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by JacobBarthelmeh** [comment]
Test this please Jenkins

**Comment by JacobBarthelmeh** [comment]
Thanks for changing this.

**Pull request merged**
