### PR TITLE
Improve checking of XSNPRINTF return value in DecodePolicyOID

### PR DESCRIPTION
**Pull request by guidovranken**
ZD 12421

### CODE REVIEW

**Comment by JacobBarthelmeh** [comment]
Ok to test

**Review by JacobBarthelmeh — APPROVED** [review]
Thanks! These are good changes.

**Comment by kaleb-himes** [comment]
retest this please

**Review by JacobBarthelmeh — CHANGES_REQUESTED** [review]
I was revisiting this after the Jenkins tests had passed and see now that the change for catching the positive 'w' value with the return of XSNPRINTF would then exit the DecodePolicyOID function with a positive 'w' return value. Can we instead have a negative error value returned, such as BUFFER_E?

**Review by JacobBarthelmeh — APPROVED** [review]

**Pull request merged**
