### PR TITLE
Create API to expose IANA id array (cipher_name_idx).

### PR DESCRIPTION
**Pull request by mmann78**
Populate passed in array with data from cipher_name_idx and pass remaining array with -1.

### CODE REVIEW

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by ejohnstown** [comment]
Michael:

We require a contributor agreement to accept any pull requests. I will contact you via email to discuss this.

--John

**Comment by ejohnstown** [comment]
The IANA IDs are two byte values. The first byte usually indicates that a suite is ECC (C0), ChaCha (CC), or for lack of a better term basic (00). This function is only going to give you a list of the second parts of all the IDs. This array you are copying out is used to figure out the cipher suite passed in with the set cipher list command. That uses a string match to figure out the first byte, then another string match across the list of names to find the second byte. We use the combination to find a suite description from a table. The array returned from your function may very well have value collisions. (Like ECDHE-RSA-CHACHA20-POLY1305-SHA256 (CCA8) and PSK-AES128-GCM-SHA256 (00A8.))

A better solution may be to refactor the cipher name list and full IDs into one array, and maybe fold it into the cipher descriptors.

**Pull request closed without merging**
