### PR TITLE
fix aes_asm.asm header format

### PR DESCRIPTION
**Pull request by cconlon**
This pull request fixes the header format of the aes_asm.asm file to match the header style throughout the codebase.

### CODE REVIEW

**Comment by toddouska** [comment]
Can you verify this still builds on Windows 64bit?  I can't imagine the spacing,  [] -> () changes, tabs in comments would matter but I'm not sure why Kojo had those in the initial convert.

**Comment by toddouska** [comment]
With AES-NI on if that wasn't clear.

**Comment by cconlon** [comment]
Verified that this compiles and runs on Windows 10 with Visual Studio 2015 Community in Release and Debug x64 builds.

Thanks for double checking, I didn't know why the () were switched to []'s in the first place either.

**Comment by toddouska** [comment]
Thanks.

**Pull request merged**
