### PR TITLE
Improve AES-GCM performance on AVX1 (IvyBridge) and AVX2

### PR DESCRIPTION
**Pull request by SparkiDev**

### CODE REVIEW

**Comment by toddouska** [comment]
Do I need to do anything besides --enable-intelasm?

Before this PR I get:
AES-128-GCM-enc   2610 MB took 1.001 seconds, 2608.563 MB/s Cycles per byte =   0.91
AES-128-GCM-dec   2590 MB took 1.001 seconds, 2587.157 MB/s Cycles per byte =   0.92
AES-192-GCM-enc   2365 MB took 1.002 seconds, 2361.203 MB/s Cycles per byte =   1.01
AES-192-GCM-dec   2385 MB took 1.001 seconds, 2382.530 MB/s Cycles per byte =   1.00
AES-256-GCM-enc   2160 MB took 1.000 seconds, 2159.853 MB/s Cycles per byte =   1.10
AES-256-GCM-dec   2180 MB took 1.001 seconds, 2177.017 MB/s Cycles per byte =   1.09

After I get:
AES-128-GCM-enc   2715 MB took 1.001 seconds, 2712.421 MB/s Cycles per byte =   0.88
AES-128-GCM-dec   2560 MB took 1.002 seconds, 2555.433 MB/s Cycles per byte =   0.93
AES-192-GCM-enc   2330 MB took 1.001 seconds, 2327.291 MB/s Cycles per byte =   1.02
AES-192-GCM-dec   2280 MB took 1.000 seconds, 2279.902 MB/s Cycles per byte =   1.04
AES-256-GCM-enc   2030 MB took 1.002 seconds, 2026.583 MB/s Cycles per byte =   1.17
AES-256-GCM-dec   2175 MB took 1.000 seconds, 2173.976 MB/s Cycles per byte =   1.09

Which looks slightly slower.

**Comment by SparkiDev** [comment]
Each CPU has different characteristics and benchmark results vary greatly from run to run.
Which CPU are you running the benchmarks on?

**Comment by toddouska** [comment]
2.5GHz quad-core Intel Core i7 processor (Turbo Boost up to 3.7GHz) with 6MB shared L3 cache.

What improvement % have you seen?

**Comment by SparkiDev** [comment]
IvyBridge CPU
Before:
AES-128-GCM-enc   1055 MB took 1.003 seconds, 1052.150 MB/s Cycles per byte =   3.08
AES-128-GCM-dec   1070 MB took 1.002 seconds, 1067.354 MB/s Cycles per byte =   3.04
AES-192-GCM-enc    990 MB took 1.002 seconds,  987.899 MB/s Cycles per byte =   3.28
AES-192-GCM-dec   1030 MB took 1.003 seconds, 1026.890 MB/s Cycles per byte =   3.16
AES-256-GCM-enc    960 MB took 1.004 seconds,  955.852 MB/s Cycles per byte =   3.39
AES-256-GCM-dec    980 MB took 1.003 seconds,  977.490 MB/s Cycles per byte =   3.32

After:
AES-128-GCM-enc   1455 MB took 1.002 seconds, 1451.590 MB/s Cycles per byte =   2.23
AES-128-GCM-dec   1455 MB took 1.002 seconds, 1452.293 MB/s Cycles per byte =   2.23
AES-192-GCM-enc   1385 MB took 1.002 seconds, 1381.906 MB/s Cycles per byte =   2.35
AES-192-GCM-dec   1385 MB took 1.003 seconds, 1380.767 MB/s Cycles per byte =   2.35
AES-256-GCM-enc   1300 MB took 1.002 seconds, 1297.743 MB/s Cycles per byte =   2.50
AES-256-GCM-dec   1290 MB took 1.001 seconds, 1288.817 MB/s Cycles per byte =   2.52

Skylake CPU
Before:
AES-128-GCM-enc   4980 MB took 1.001 seconds, 4977.108 MB/s Cycles per byte =   0.50
AES-128-GCM-dec   4910 MB took 1.000 seconds, 4908.738 MB/s Cycles per byte =   0.50
AES-192-GCM-enc   4370 MB took 1.001 seconds, 4367.533 MB/s Cycles per byte =   0.57
AES-192-GCM-dec   4385 MB took 1.001 seconds, 4381.223 MB/s Cycles per byte =   0.56
AES-256-GCM-enc   3785 MB took 1.000 seconds, 3783.358 MB/s Cycles per byte =   0.65
AES-256-GCM-dec   3790 MB took 1.001 seconds, 3785.061 MB/s Cycles per byte =   0.65

After:
AES-128-GCM-enc   5125 MB took 1.000 seconds, 5123.244 MB/s Cycles per byte =   0.48
AES-128-GCM-dec   5180 MB took 1.001 seconds, 5175.115 MB/s Cycles per byte =   0.48
AES-192-GCM-enc   4400 MB took 1.000 seconds, 4397.947 MB/s Cycles per byte =   0.56
AES-192-GCM-dec   4365 MB took 1.001 seconds, 4360.168 MB/s Cycles per byte =   0.57
AES-256-GCM-enc   3785 MB took 1.001 seconds, 3780.275 MB/s Cycles per byte =   0.65
AES-256-GCM-dec   3785 MB took 1.000 seconds, 3784.432 MB/s Cycles per byte =   0.65

**Pull request merged**
