### PR TITLE
Benchmark, SM3: fix full hash testing

### PR DESCRIPTION
**Pull request by SparkiDev**
# Description

Test now has an array of hashes.
Use only first hash when testing full digest operation.

# Testing

Install SM code.
./configure --enable-sm3
make

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Comment by SparkiDev** [comment]
retest this please

**Comment by SparkiDev** [comment]
retest this please

**Comment by SparkiDev** [comment]
retest this please

**Review by douzzer — CHANGES_REQUESTED** [review]
This all looks fine, but I can't get a proper read on whether it works because of preexisting defects in the wolfsm code.

I've implemented several tests for it in the usual way, and the initial report is
[65a2e5265c-multi-test-log.html.gz](https://github.com/wolfSSL/wolfssl/files/15258045/65a2e5265c-multi-test-log.html.gz)

From the looks of it, most of the fixes will be to the wolfsm repo.  Assign the wolfsm fixit PR(s) to me when they're ready.

**Comment by SparkiDev** [comment]
retest this please

**Comment by SparkiDev** [comment]
Let me know if there are further clang-tidy fixes required.

**Review by douzzer — APPROVED** [review]

**Pull request merged**
