### PR TITLE
ChaCha20, Poly1305 ASM for MSVC

### LINKED ISSUE #7213: How to compile chacha_asm.S for Windows x86_64?
### Version

5.6.6

### Description

my user_settings.h include:
```
#undef  HAVE_CHACHA
#define HAVE_CHACHA

#undef  USE_INTEL_SPEEDUP
#define USE_INTEL_SPEEDUP
```
But when i try to link my app with WolfSSL static lib, compiled with those defines i have errors:

> Severity	Code	Description	Project	File	Line	Suppression State	Details
> Error	LNK2001	unresolved external symbol chacha_encrypt_avx2	E:\WORK\test\out\build\x64-release\test	E:\WORK\test\out\build\x64-release\wolfssl.lib(chacha.obj)	1		
> Error	LNK2001	unresolved external symbol chacha_encrypt_avx1	E:\WORK\test\out\build\x64-release\test	E:\WORK\test\out\build\x64-release\wolfssl.lib(chacha.obj)	1		
> Error	LNK2001	unresolved external symbol chacha_encrypt_x64	E:\WORK\test\out\build\x64-release\test	E:\WORK\test\out\build\x64-release\wolfssl.lib(chacha.obj)	1		
> Error	LNK1120	3 unresolved externals	E:\WORK\test\out\build\x64-release\test	E:\WORK\test\out\build\x64-release\cha_test.exe	1

As i understand this is because chacha_asm.S is not included inside .sln project, if i remove USE_INTEL_SPEEDUP everything is ok, but the thing is i want to use asm speedup for performace. 
Is there any way to compile chacha_asm.S for windows version of WolfSSL?

### PR DESCRIPTION
**Pull request by SparkiDev**
# Description

Make ChaCha20 and Poly1305 asm available for MSVC.

Fixes #7213

# Testing

Linux ASM still works.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Comment by bandi13** [comment]
retest this please

**Comment by SparkiDev** [comment]
retest this please

**Comment by SparkiDev** [comment]
Tests passed.
Removed the algorithms from user_settings.h

**Review by douzzer — APPROVED** [review]
also tested with `linuxkm-mainline-intelasm-sp-asm-pie-gcc-latest-insmod` due to minor changes in .S asm files.  all good.

**Pull request merged**
