### PR TITLE
Retry hwsim tests 3 times on fail

### PR DESCRIPTION
**Pull request by julek-wolfssl**

### CODE REVIEW

**Comment by bandi13** [comment]
Jenkins retest this please

**Comment by bandi13** [comment]
Jenkins retest this please

**Comment by julek-wolfssl** [comment]
The jenkins failures are not caused by this PR. It would be good to merge this so that the hwsim tests are more reliable.

**Comment by bandi13** [comment]
Jenkins retest this please

**Comment by bandi13** [comment]
> The jenkins failures are not caused by this PR. It would be good to merge this so that the hwsim tests are more reliable.

I agree. I think if it fails again, we can still merge.

**Review by dgarske — APPROVED** [review]

**Pull request merged**
