### PR TITLE
PQC: Update Falcon support to match OQS

### PR DESCRIPTION
**Pull request by Frauschi**
Hi there,

To keep compatibility with the Open Quantum Safe projects, we have to follow their OID changes. After Round 3 of the NIST PQC competition, OQS changed the OIDs of Falcon, resulting in an incompatibility with WolfSSL. This PR resolves the incompatibility and updates the Falcon OIDs to match the current OQS ones (see [here](https://github.com/open-quantum-safe/oqs-provider/blob/main/oqs-template/oqs-sig-info.md)).

This should also fix the certificate issues mentioned in #7095.

### CODE REVIEW

**Comment by dgarske** [comment]
Okay to test. Contributor agreement on file

**Review by dgarske — APPROVED** [review]

**Comment by dgarske** [comment]
Hi @Frauschi , you might need to rebase this PR to latest master to get it to pass. The curl error was `configure: error: libpsl was not found`, which is likely solved with a rebase.

**Comment by Frauschi** [comment]
> Hi @Frauschi , you might need to rebase this PR to latest master to get it to pass. The curl error was `configure: error: libpsl was not found`, which is likely solved with a rebase.

Just rebased :+1:

**Comment by anhu** [comment]
Hi @Frauschi , Thank you so much for submitting this change. I understand your reasoning, but wolfSSL isn't always so keen to follow up on tracking OpenSSL's every move and moving forward with them. We enjoying helping people move at their own pace and that has been the hallmark of the success of our OpenSSL Compatibility Layer. 

All of that said, I do agree that we need to move forward and continue tracking the OID and codepoint changes defined by the OQS team.  As such, I agree with the need for this PR.  I have reviewed the diff of the change and it look fine to me. 

Can you please change the comment to reflect that this is for the purpose of tracking OQS Teams changes in OIDs.  No need to mention OpenSSL in there.

**Comment by dgarske** [comment]
okay to test

**Pull request merged**
