### PR TITLE
fix c89 build on windows

### PR DESCRIPTION
**Pull request by JacobBarthelmeh**

### CODE REVIEW

**Comment by JacobBarthelmeh** [comment]
This builds for me on windows VS. Please check Jenkins Visual Studio test is pulling in the pull request rather then master branch.

**Comment by kaleb-himes** [comment]
retest this please jenkins

**Comment by kaleb-himes** [comment]
Looks good thank you Jacob for taking the initiative here!

- Kaleb

**Comment by kaleb-himes** [comment]
Will merge as soon as Jenkins is done chewing on it

**Pull request merged**
