### PR TITLE
Add wolfSSL_PEM_read_RSAPrivateKey to OpenSSL compatible API

### PR DESCRIPTION
**Pull request by satoshiyamaguchi**
# Description

This PR adds wolfSSL_PEM_read_RSAPrivateKey() to the OpenSSL compatible API,
and adds the unit-test code to tests/api.c .

wolfSSL_PEM_read_RSAPrivateKey() was added from line 1782 to line 1822.
\#ifdef is on line 1346.
\#endif is on line 2062.

# Testing

Built example app using wolfSSL_PEM_read_RSAPrivateKey() and ran it.
Checked if wolfSSL_PEM_read_RSAPrivateKey() returns RSA structure 
and if RSA_print_fp() can print the RSA structure.

# Checklist

 - [x] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Comment by dgarske** [comment]
OK to test . @satoshiyamaguchi is a contractor.

**Review by dgarske — CHANGES_REQUESTED** [review]
```
./configure --disable-filesystem --enable-opensslextra && make

make[2]: warning: -j5 forced in submake: resetting jobserver mode.
In file included from src/ssl.c:94:
./wolfssl/openssl/pem.h:53:45: error: unknown type name ‘XFILE’; did you mean ‘FILE’?
   53 | WOLFSSL_RSA* wolfSSL_PEM_read_RSAPrivateKey(XFILE fp,
      |                                             ^~~~~
      |                                             FILE
```

**Comment by satoshiyamaguchi** [comment]
@dgarske I fixed the cause of the error. Thank you.

**Review by dgarske — APPROVED** [review]
Good work. Thank you

**Comment by cconlon** [comment]
Retest this please jenkins

**Comment by satoshiyamaguchi** [comment]
I fixed the part that seemed to be the cause of the error.

**Review by cconlon — APPROVED** [review]
Thanks Yamaguchi-san!  I'm holding off on merging this until I confirm that your contributor agreement has been approved and filed.

**Comment by cconlon** [comment]
Contributor agreement filed and approved.

**Pull request merged**
