### PR TITLE
copy missing Espressif/ESP-IDF files from wolfssl/wolfcrypt/benchmark

### PR DESCRIPTION
**Pull request by gojimmypi**
when compiling the example benchmark app, there were two key files were missing. 

in WSL, copy the `WolfSSL/IDE/Espressif/ESP-IDF/examples` project:

```
cp -r /mnt/c/workspace/WolfSSL/IDE/Espressif/ESP-IDF/examples/wolfssl_benchmark .
cd wolfssl_benchmark
. $HOME/esp/esp-idf/export.sh
make
```
resulting in this error:
```
AR build/xtensa/libxtensa.a
Generating sections.ld
LD build/wolfssl_benchmark.elf
/home/gojimmypi/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/gojimmypi/esp/wolfssl_benchmark/build/main/libmain.a(helper.o):(.literal.app_main+0x0): undefined reference to `wolf_benchmark_task'
/home/gojimmypi/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/gojimmypi/esp/wolfssl_benchmark/build/main/libmain.a(helper.o): in function `app_main':
/home/gojimmypi/esp/wolfssl_benchmark/main/helper.c:169: undefined reference to `wolf_benchmark_task'
collect2: error: ld returned 1 exit status
/home/gojimmypi/esp/esp-idf/make/project.mk:574: recipe for target '/home/gojimmypi/esp/wolfssl_benchmark/build/wolfssl_benchmark.elf' failed
make: *** [/home/gojimmypi/esp/wolfssl_benchmark/build/wolfssl_benchmark.elf] Error 1
```

so I copied these two `wolfssl/wolfcrypt` files into the example directory:
```
cd ~/esp/wolfssl_benchmark/main
cp /mnt/c/workspace/wolfssl/wolfcrypt/benchmark/benchmark.c .
cp /mnt/c/workspace/wolfssl/wolfcrypt/benchmark/benchmark.h .
```

This fixed the `make` problems above; `idf.py build` was also successful, despite the compile problems I had in https://github.com/espressif/esp-wolfssl/issues/11 and https://github.com/wolfSSL/wolfssl/issues/4272 

Also, note there's no native USB support in WSL1, so to program the device (in my case an M5Stack ESP32) call the Windows/DOS `python.exe`. Here we are using `COM4` with Python 3.6 installed in `C:\python36`:
```
/mnt/c/Python36/python.exe ~/esp/esp-idf/components/esptool_py/esptool/esptool.py  -p com4 -b 460800 --before default_reset --after hard_reset --chip esp32  write_flash --flash_mode dio --flash_size detect --flash_freq 40m 0x1000 build/bootloader/bootloader.bin 0x8000 build/partition_table/partition-table.bin 0x10000 build/wolfssl_benchmark.bin
```

### CODE REVIEW

**Comment by dgarske** [comment]
Hi @gojimmypi ,

Would it make sense to update the `setup.sh` and `setup_win.bat` to do this as a copy? I cannot see us accepting this change because we would have a duplicate copy of benchmark.c or .h in the repo.

Thanks,
David Garske, wolfSSL

**Review by dgarske — CHANGES_REQUESTED** [review]
Will you squash these two commits so there is no history of the benchmark.c copy/delete?
Can you also make these changes to the .bat file for Windows users?

Note: I order to accept this we will need to get a signed contributor agreement. Please email support@wolfssl.com with your contact info and reference to this PR. Thanks.

**Comment by gojimmypi** [comment]
Hi @dgarske ,

Yes, I can see how that might be an issue having multiple copies of `benchmark.c` and `benchmark.h` in the repo.

It still may not be the most graceful method to rely on the end user to re-run `setup` after a fresh `git pull`. I wonder if some sort of git symbolic link would work for both Windows and Linux clients?

In any case,  I've updated the `setup.sh` to include the copy operation. I've also updated `setup.bat` -  I believe it *should* work, but I *have not tested* the Windows batch file. Despite being on a Windows machine, my `ESP-IDF` is in WSL, not Windows.

I believe Visual Studio should have sent my commit squash & I've sent an email to support for the contributor agreement.

**Comment by gojimmypi** [comment]
Hi @dgarske ,

I'm awaiting reply from support to see if there is some alternative agreement acknowledgement, as I don't have a printer to put an ink signature on your contributor agreement PDF. Have you considered using some sort of automated mechanism such as the [GitHub Contributor License Agreement Assistant](https://github.com/cla-assistant/cla-assistant#readme)?

**Comment by embhorn** [comment]
Jenkins please test this

**Comment by embhorn** [comment]
@gojimmypi Thanks for sending in the contributor agreement. I've started the CI tests.

**Pull request merged**
