### PR TITLE
Fix CMakeLists.txt file

### PR DESCRIPTION
**Pull request by topazus**
# Description

Please describe the scope of the fix or feature addition.

- fix the install destination of the library
- enable tests with CTest
- fix pkgconfig file

# Testing

How did you test?

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Comment by dgarske** [comment]
Hi Felix,

Thank you for this contribution. In order to accept this we need to have a signed contributor agreement on file. Please send an email to support @ wolfssl.com referencing this pull request. It would be wonderful to hear more about your project and where you are located.

Thanks,
David Garske, wolfSSL

**Comment by dgarske** [comment]
@topazus , thanks for the email and while the contributor agreement is in progress, I am asking @JacobBarthelmeh to review this.

**Comment by dgarske** [comment]
ZD 16480

**Comment by JacobBarthelmeh** [comment]
Closing this stale pull request. Contributor agreement status did not get resolved and unit tests have since been added to cmake.

**Pull request closed without merging**
