### PR TITLE
add stubs file for the new as-built fips sources

### PR DESCRIPTION
**Pull request by ejohnstown**

### CODE REVIEW

**Comment by dgarske** [comment]
Why not just fix the include.am to do an `if BUILD_FIPS` check here on the fips header files?
https://github.com/wolfSSL/wolfssl/blob/master/wolfssl/wolfcrypt/include.am#L23

Seems bad to require blank files in the repo when not required. If we were to include the blank files they should at least have a comment in them.

**Comment by ejohnstown** [comment]
I am following the existing pattern.

**Comment by dgarske** [comment]
John, the only pattern in place is for ctaocrypt fips files. If you look at the autogen.sh there are many files that we "touch" that don't exist. I urge you to discuss with others and make sure this is the best solution.

**Comment by ejohnstown** [comment]
Oh yeah. Oops.

**Pull request closed without merging**
