### PR TITLE
Anonymous cipher fix

### PR DESCRIPTION
**Pull request by dgarske**
Fix for possible seg fault with anonymous cipher mode enabled. Do not perform signature/verify when using anon_cipher. Only added "if (!ssl->options.usingAnon_cipher)" around the sign/verify. Went back to original SendServerKeyExchange to see this was missing after refactor for async.

### CODE REVIEW

**Comment by kaleb-himes** [comment]
Looks good to me so far chris, I've looped it and am no longer seeing the issue. OpenSSL test still fails because openSSL not configured for ADH but that can be addressed at a later date I believe. Over to you ->

**Comment by cconlon** [comment]
Initial review looks good.  Waiting for David to double check on one default pointer value for "ssl->sigKey".

**Comment by dgarske** [comment]
Debugged this for way too long and eventually traced it down to the output buffer being corrupted at the end because the length wasn't set right due to the "usingAnon_cipher" not being set right. There is no good way to add any additional checks. The proper fix is the one already here, which is to not do the signature stuff for anon cipher. @cconlon: Good as-is, green light to merge in.

**Comment by cconlon** [comment]
Thanks David!

**Pull request merged**
