### PR TITLE
Wrap JavaScript source on multiple lines to make it readable

### PR DESCRIPTION
**Pull request by ottok**
Closes: wolfSSL/wolfssl#2783

### CODE REVIEW

**Comment by kaleb-himes** [comment]
Hi @ottok,

Thank you for submitting this pull request. As wolfSSL is a commercial organization and licenses this software by default we can only accept non-wolfssl-employee contributions after we have a formal license agreement in place that allows for code contributions OR in lack of a license agreement we can send you an individual contributor agreement to review, sign, and return if you agree with the terms of the agreement.

Can you tell us if this was part of an effort involving a licensed wolfSSL product? If this was not for an already licensed product could you please send an email to "support [at] wolfssl [dot] com" with the subject "Attn @kaleb: Request for contributor agreement regarding PR 2783" and I'll be happy to get the review process started by first sending you a contributor agreement for review and signing.

Thank you and Regards,

K

**Comment by kaleb-himes** [comment]
This is an excellent format change, forwarding up the chain for further review.

- K

**Comment by kaleb** [comment]
> Hi @ottok,
> 
> Thank you for submitting this pull request. As wolfSSL is a commercial organization and licenses this software by default we can only accept non-wolfssl-employee contributions after we have a formal license agreement in place that allows for code contributions OR in lack of a license agreement we can send you an individual contributor agreement to review, sign, and return if you agree with the terms of the agreement.
> 
> Can you tell us if this was part of an effort involving a licensed wolfSSL product? If this was not for an already licensed product could you please send an email to "support [at] wolfssl [dot] com" with the subject "Attn @kaleb: Request for contributor agreement regarding PR 2783" and I'll be happy to get the review process started by first sending you a contributor agreement for review and signing.
> 
> Thank you and Regards,
> 
> K

It looks like this summoned me.

**Comment by ottok** [comment]
I sent the signed CLA yesterday

**Comment by cconlon** [comment]
Test this please Jenkins

**Comment by ottok** [comment]
@cconlon Jenkins has tested this and everything passed?
image

**Comment by cconlon** [comment]
Assigning to Todd for final review and merge.

**Pull request merged**
