### PR TITLE
Return error with AES-GCM and negotiated versions < TLSv1.2

### PR DESCRIPTION
**Pull request by cariepointer**
Fix for VerifyServerSuite() to return 0 in when a client running TLSv1.1 or TLSv1.0 attempts to use an AEAD cipher suite. Maintenance item from zendesk ticket #5717

### CODE REVIEW

**Comment by ejohnstown** [comment]
Assigning to Todd for final review.

**Comment by toddouska** [comment]
A client simply having an AEAD cipher in its list should not be an error.  The server negotiating one, on the other, can be though we need a way to override at build time to have old behavior.  Also, you're returning 0 not MATCH_SUITE_ERROR.  The commit comment has to be exact, as well as the code it describes.

**Comment by cariepointer** [comment]
Added define WOLFSSL_OLDTLS_AEAD_CIPHERSUITES to override check for AEAD cipher suites in TLSv1.1 and TLSv1.0.

**Comment by cariepointer** [comment]
I’ve verified with the wolfSSL example client and server that if a client presents an AEAD cipher suite in its list along with additional valid cipher suites, then the connection does not error out. When the server checks the suite validity, if it is an AEAD cipher suite, then VerifyServerSuite() returns 0 and the next cipher suite in the list is checked for validity.

**Comment by toddouska** [comment]
Add a test where the client presents an AEAD cipher suite with TLS 1.1 along with a non AEAD one to show and maintain your verification.

Also, add tests for cipher suites that are turned on by default.  ADH ones are not.

**Pull request merged**
