### PR TITLE
compiler warning about myStack use in unique environment

### PR DESCRIPTION
**Pull request by kaleb-himes**
changed ```memset``` to ```XMEMSET``` for portability and security purposes

produced in the following environment:

gcc version 4.9.3 (Ubuntu 4.9.3-8ubuntu2~14.04)
on a 32-bit Big Endian Platform running Ubuntu 14.04.3 LTS for powerPC

solution: initialize to NULL. Check after setting all memory blocks beyond the pointer to point at 0x01 instead of 0x0. Exit with err_sys if it is still NULL.

### CODE REVIEW

**Comment by kaleb-himes** [comment]
Assigning to Todd for now because of this commit: https://github.com/cyassl/cyassl/commit/ee0595f5437dbfaa08b84f3e2686c1d5047a39ec

Please feel free to re-assign if you are busy

**Comment by toddouska** [comment]
If the memalign function lies, i.e., returns success but doesn't alloc the pointer the changes proposed are wrong.  The memset will crash on a null pointer.  A better solution is

if (ret != 0 || myStack == NULL)

**Comment by kaleb-himes** [comment]
> If the memalign function lies, i.e., returns success but doesn't alloc the pointer the changes proposed > are wrong. The memset will crash on a null pointer. A better solution is
> 
> if (ret != 0 || myStack == NULL)

Implemented

**Comment by toddouska** [comment]
myStack should still be set to NULL for the later check against NULL.

**Comment by kaleb-himes** [comment]
> myStack should still be set to NULL for the later check against NULL.

Implemented

**Pull request merged**
