### PR TITLE
ARM Poly1305

### PR DESCRIPTION
**Pull request by julek-wolfssl**
This is an implementation of the Poly1305 algorithm for the ARM architecture using the SIMD NEON extension.

### CODE REVIEW

**Review by SparkiDev — CHANGES_REQUESTED** [review]
Poly1305 test isn't passing in testwolfcrypt.

**Comment by julek-wolfssl** [comment]
Could you check that you have the latest version of the branch? All of the tests work fine for me. If they still do not work for you then can you give me some more details?

**Comment by kaleb-himes** [comment]
Sean you can launch the automated tests with "OK to test" for future reference.

**Comment by julek-wolfssl** [comment]
Unfortunately I don't have access to Jenkins so you will have to relay to me the failure details.

**Comment by kaleb-himes** [comment]
Julek,

Please go to https://test.wolfssl.com/jenkins <https://test.wolfssl.com/jenkins> and sign up for an account. Once you are signed up please send me your user name and I will grant you read permissions on the site.

Warm Regards,


Kaleb Himes
Software Engineer
www.wolfssl.com

TLS1.3 IS AVAILABLE in wolfSSL!!
Find the latest from wolfSSL at https://github.com/wolfssl

**Comment by SparkiDev** [comment]
My bad.
I was going to make changes to the assembly code and I left it with some code #ifdefed out!

**Comment by julek-wolfssl** [comment]
Jenkins picked up some errors anway so I'll fix those first thing tomorrow.

**Comment by SparkiDev** [comment]
Rebase when #2279 is merged into master.
The issues are not related to this work.

**Comment by julek-wolfssl** [comment]
I fixed the bug that was causing the "fsanitize=address test" test to fail.

**Comment by julek-wolfssl** [comment]
Now just waiting for #2279 to be merged.

**Comment by julek-wolfssl** [comment]
All tests have passed.

**Review by SparkiDev — APPROVED** [review]

**Pull request merged**
