### PR TITLE
Enable X25519 for Key Exchange in TLS

### PR DESCRIPTION
**Pull request by SparkiDev**

### CODE REVIEW

**Comment by toddouska** [comment]
Thanks.  Looks like wolfSSL will now prefer X25519 over P256 by default with curve25519 enabled.  Is that intended?  I'm thinking we should still prefer P256 by default in that case unless the user uses supported curves APIs to prefer X25519 explicitly.  Thoughts?

**Comment by SparkiDev** [comment]
That was intended, yes. Explicitly compiling X25519 in to my mind means that you want to use it. So, by default, it should be used. If both parties have it then it should be used as it is faster.
I can remove it from being set on default and add it as an option to client and server if you want.

**Comment by toddouska** [comment]
By that logic what about when someone explicitly turns on brainpool and koblitz and X255?  I think we still need a default preference order.   Having X25519 be on by default as a supported curve is fine when enabled, having it on and preferred over P256 is different.  I'm not suggesting the user should have to turn it on when enabled, simply that when P256 and X25519 are both on that our server should by default prefer P256 for now.  Having a simple command line switch for the example server to demonstrate preferring X25519 would be great.

**Comment by SparkiDev** [comment]
OK. I will de-prioritize X25519 behind P256 and add option to client to use X25519 which will make it default.

**Comment by toddouska** [comment]
Thanks for changing this.  Can you also:

1) make sure the example client prints out the -t usage w/o TLS 1.3 compiled in

2) make sure the example client can still connect to the example server with ECC certs.

./examples/server/server -d -l ECDHE-ECDSA-AES128-GCM-SHA256 -c ./certs/server-ecc.pem -k ./certs/ecc-key.pem
./examples/client/client -t

server gets SSL_accept error -501, can't match cipher suite

because client is ONLY sending x25519 supported curves I'm guessing instead of x25519 and p256.

3) Have the example client use x25519 even in benchmark mode with ./scripts/benchmark

./scripts/benchmark.test 1 1 "-t" "-d -l ECDHE-ECDSA-AES128-GCM-SHA256 -c ./certs/server-ecc.pem -k ./certs/ecc-key.pem"

suggest setting supported curves on WOLFSSL_CTX after wolfSSL_CTX_new() since there's only one CTX_new vs the several wolfSSL_new()s.

**Comment by SparkiDev** [comment]
Changes made as requested.

**Pull request merged**
