### PR TITLE
Adjust DTLS retranmission logic

### PR DESCRIPTION
**Pull request by steweg**
This patch adjust DTLS retranmission logic
in order to avoid message floods between client
and server

### CODE REVIEW

**Comment by steweg** [comment]
You were right, this was a bug. This is needed to be done only before Flight-6, when server receives ChangeCipherSuite without some message from Flight-5 and request re-sending of Flight-5 by sending ServerHello from Flight-4. I adjusted the patch to reflect this.

**Comment by ejohnstown** [comment]
Jenkins, please test this.

**Comment by ejohnstown** [comment]
Jenkins, please test this.

**Comment by ejohnstown** [comment]
Jenkins, please test this.

**Comment by ejohnstown** [comment]
Thank you for the patch!

**Pull request merged**
