### PR TITLE
OCSP Free

### PR DESCRIPTION
**Pull request by ejohnstown**
Free the OCSP request when creating the response only if there is an error making the request.

### CODE REVIEW

**Comment by kaleb-himes** [comment]
Excellent work John, I approve. Would you like me to wait until Sean take a look before merging?

**Comment by ejohnstown** [comment]
David:

That was disabled while Kaleb and I were collaborating on this PR. The -X option is for the test utilities that include the client and server as code, like the unit test. It isn't meant for the client stand-alone tool. (If you include it, the client prints out that "external test can't be run in this mode". I'll add a note when I address the port number issue.

--John

**Comment by ejohnstown** [comment]
David:

I'm not going to address the port number issue at this time. I'm having some issues with TLSv1.3 and OCSP-Stapling using the port number change. I want to improve the test for both these cases, but I need to put them on the back burner for a little bit.

**Comment by dgarske** [comment]
@ejohnstown : We will have to revisit this OSCP port thing again soon. Seeing a lot of OCSP Stapling V2 failures on Jenkins such as:

```
Error setting up accept BIO
139678437263000:error:02006062:system library:bind:Address already in use:b_sock.c:783:port='22221'
139678437263000:error:20069075:BIO routines:BIO_get_accept_socket:unable to bind socket:b_sock.c:785:
```

**Pull request merged**
