### PR TITLE
Create APIs to expose IANA id array used in suite (wolfSSL_get_cipher…

### PR DESCRIPTION
**Pull request by mmann78**
…_iana_list, wolfSSL_CTX_get_cipher_iana_list).

Populate passed in array with data from Suites structure.  Also return number of suites found (based on array size passed in)

Also compressed cipher_names and cipher_name_idx into a single structure.

### CODE REVIEW

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by ejohnstown** [comment]
This looks like how I'd do it. Except that the array you return still isn't the IANA ID numbers for the suites, it is only the lower order byte of the IDs. For example, `TLS_RSA_WITH_AES_128_CBC_SHA ` is `{0x00, 0x2F}`, and `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` is `{0x0C, 0x2F}`. You'll end up with collisions.

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Comment by kaleb-himes** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
