### PR TITLE
sanity checks

### PR DESCRIPTION
**Pull request by JacobBarthelmeh**
Add sanity checks on input arguments and on idx increment.

### CODE REVIEW

**Comment by toddouska** [comment]
Thanks!  Should we also add sanity checks to usedLength, maxLength, and inSz for negative numbers in GetInputData() as well?  inSz is checked but it could probably be sooner, i.e., right after the calculation.

**Comment by JacobBarthelmeh** [comment]
Right, maxLength could use a check and it doesn't hurt to check all three at that point. That sounds good. Adding in the additional checks will help make it more robust.

**Comment by JacobBarthelmeh** [comment]
Killed the last large test to force update the branch and keep the commit history clean. Reason for force updating was to check inSz <= 0 (before my commit just had inSz < 0 ) and to have inSz be checked after the DTLS block in case inSz gets reset.

**Comment by toddouska** [comment]
Thanks for the changes.

**Pull request merged**
