### PR TITLE
fixes ocsp dependency check on asn during configure.

### PR DESCRIPTION
**Pull request by moisesguimaraes**

### CODE REVIEW

**Comment by moisesguimaraes** [comment]
@ejohnstown,

@JacobBarthelmeh reported that the following configure option wasn't working:
    ./configure --disable-asn --disable-rsa --enable-psk --disable-ecc --enable-ocspstapling
Since **ocspstapling** causes **ocsp** to be enabled so the following config didn't work also:
    ./configure --disable-asn --disable-rsa --enable-psk --disable-ecc --enable-ocsp

I put a check after enable-ocsp to detect disable-asn, but the check wasn't working when one of the staplings (v1 or v2) forces -DHAVE_OCSP, so I changed the order to enforce all the checks done when OCSP is enabled.

Can you show me an example where the item on the configure.ac refactor list was applied so I can fix this that way? I wasn't aware of that list.

**Comment by ejohnstown** [comment]
`AC_ARG_ENABLE([maxstrength]...` was the first, and only so far, to follow the pattern.

**Comment by moisesguimaraes** [comment]
@ejohnstown,
I added the check in the right session, and also added some #### lines no make the new sessions more visible.

**Comment by ejohnstown** [comment]
You backed out all the changes and broke "disable-asn" for PSK only builds.

    ./configure --disable-asn --disable-rsa --disable-ecc --enable-psk

tells me that I need to enable ASN when using OCSP, and I'm not using OCSP.

**Comment by moisesguimaraes** [comment]
fixed, I forgot the ENABLED_OCSP test.

**Comment by ejohnstown** [comment]
OCSP is also dependent on RSA or ECC being present.

    ./configure --disable-rsa --disable-ecc --enable-psk --enable-oscp

Also fails make check. If I delete the disable of RSA or ECC make check will work.

**Comment by moisesguimaraes** [comment]
ok, I'll add the an extra check.

**Pull request merged**
