### PR TITLE
SHA-3 Thumb2, ARM32 ASM: Add assembly implemention

### PR DESCRIPTION
**Pull request by SparkiDev**
# Description

Add SHA-3 assembly implementation for Thumb2 and ARM32.

# Testing

QEMU with hosts: armv7m, armv8

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Comment by bandi13** [comment]
retest this please

**Comment by SparkiDev** [comment]
Fixe inline assembly code.

**Comment by SparkiDev** [comment]
retest this please

**Review by dgarske — APPROVED** [review]
Nice work!

STM32H7A Cortex M7 at 240MHz:

```
SHA3-224                     1 MiB took 1.004 seconds,    1.410 MiB/s
SHA3-256                     1 MiB took 1.008 seconds,    1.332 MiB/s
SHA3-384                     1 MiB took 1.016 seconds,    1.033 MiB/s
SHA3-512                   750 KiB took 1.011 seconds,  741.840 KiB/s
SHAKE128                     2 MiB took 1.012 seconds,    1.616 MiB/s
SHAKE256                     1 MiB took 1.008 seconds,    1.332 MiB/s
ML-DSA    44  key gen        60 ops took 1.031 sec, avg 17.183 ms, 58.196 ops/sec
ML-DSA    44     sign        18 ops took 1.078 sec, avg 59.889 ms, 16.698 ops/sec
ML-DSA    44   verify        54 ops took 1.008 sec, avg 18.667 ms, 53.571 ops/sec
ML-DSA    65  key gen        36 ops took 1.051 sec, avg 29.194 ms, 34.253 ops/sec
ML-DSA    65     sign        12 ops took 1.094 sec, avg 91.167 ms, 10.969 ops/sec
ML-DSA    65   verify        34 ops took 1.035 sec, avg 30.441 ms, 32.850 ops/sec
ML-DSA    87  key gen        22 ops took 1.070 sec, avg 48.636 ms, 20.561 ops/sec
ML-DSA    87     sign         8 ops took 1.259 sec, avg 157.375 ms, 6.354 ops/sec
ML-DSA    87   verify        20 ops took 1.008 sec, avg 50.400 ms, 19.841 ops/sec
```

**Pull request merged**
