### PR TITLE
Dilithium: add option to precalc with small sign

### PR DESCRIPTION
**Pull request by SparkiDev**
# Description

WOLFSSL_DILITHIUM_SIGN_SMALL_MEM_PRECALC added.
It allocates memory for and pre-calculates s1, s2 and t0.
This saves decoding the vectors repeatedly in each signature trial.

# Testing

./configure 'CC=clang -fsanitize=address' '--disable-shared' '--enable-experimental' '--enable-intelasm' '--enable-dilithium' 'CFLAGS=-DWOLFSSL_DILITHIUM_SIGN_SMALL_MEM' '--enable-debug'
make test

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Comment by SparkiDev** [comment]
retest this please

**Comment by SparkiDev** [comment]
retest this please

**Comment by SparkiDev** [comment]
retest this please

**Comment by SparkiDev** [comment]
retest this please

**Comment by SparkiDev** [comment]
Please squash before committing.

**Review by dgarske — APPROVED** [review]

**Pull request merged**
