### PR TITLE
Support FASCN OID in wolfssl_dns_entry_othername_to_gn()

### PR DESCRIPTION
**Pull request by anhu**
Fixes ZD 16807

### CODE REVIEW

**Comment by anhu** [comment]
If tests, please merge. Customer has expressed some urgency on this ticket.

**Comment by anhu** [comment]
@wolfSSL-Bot 
Customer has confirmed the PR fixes the issue.  Please merge if you approve, 
Warm regards, Anthony

**Comment by anhu** [comment]
jenkins retest please 

oops...didn't notice the failed test.

**Comment by anhu** [comment]
retest this please

**Comment by anhu** [comment]
All tests passed.  Please merge at will.

**Review by JacobBarthelmeh — APPROVED** [review]

**Pull request merged**
