### PR TITLE
SP modinv: add non-constant time modinv

### PR DESCRIPTION
**Pull request by SparkiDev**
Can only be used in ECC verify - sign operation must be constant time.
Not used for small code.

### CODE REVIEW

**Comment by toddouska** [comment]
@JacobBarthelmeh please do a first pass review and assign to me after you approve.

**Review by JacobBarthelmeh — APPROVED** [review]
Looks good, confirmed only used with verify operation and it makes verifies faster. My only suggestion would be that a comment is added with the warning that the function sp_###_mod_inv_# is not constant time.

**Comment by SparkiDev** [comment]
Updated to include comment about non-constant time.

**Comment by toddouska** [comment]
Looks good, please resolve merge conflicts.

**Review by toddouska — APPROVED** [review]

**Pull request merged**
