### PR TITLE
Additional length check improvements in Base64_SkipNewline

### PR DESCRIPTION
**Pull request by guidovranken**

### CODE REVIEW

**Comment by dgarske** [comment]
OK to test

**Comment by kaleb-himes** [comment]
NOTE: @guidovranken, this is causing some failures. One such is easily reproduced with `./configure --disable-dependency-tracking --disable-shared --enable-alpn --enable-sni --enable-tls13 && make check`. Can you test it locally?

**Review by dgarske — APPROVED** [review]

**Comment by SparkiDev** [comment]
retest this please

**Comment by SparkiDev** [comment]
retest this please

**Comment by SparkiDev** [comment]
retest this please

**Comment by dgarske** [comment]
@guidovranken this seems to break something in our tests. Can you revisit this change?

**Comment by guidovranken** [comment]
I've pushed a fix.

**Review by SparkiDev — APPROVED** [review]

**Pull request merged**
