### PR TITLE
Added missing ATECC508A-pubkey_raw value for peerEccKey

### PR DESCRIPTION
**Pull request by WolfWalter**
As discussed in [issue 1793](https://github.com/wolfSSL/wolfssl/issues/1793) the `ssl->hsKey` `public_raw` value for `EccSharedSecret` was empty when using the WOLFSSL_ATECC508A define.

### CODE REVIEW

**Comment by dgarske** [comment]
Hi WolfWalter, we appreciate the contribution. To accept this we require a signed contributor agreement. Please send us an email at support@wolfssl.com referencing the pull request and we'll send over the agreement. Thanks!

**Comment by cconlon** [comment]
Update:  wolfSSL now has a signed Contributor Agreement on file from Wolf Walter.

**Comment by cconlon** [comment]
Test this please Jenkins.

**Comment by dgarske** [comment]
Replaced by PR #1815.

**Pull request closed without merging**
