### PR TITLE
DTLS Multicast

### PR DESCRIPTION
**Pull request by ejohnstown**
Add a simple addition for DTLS multicast. Group keys are handled out of band.

### CODE REVIEW

**Comment by kaleb-himes** [comment]
windows slave went down this will need re-tested but there is a merge conflict so not going to re-run the tests since another commit will be necessary anyway.

**Comment by ejohnstown** [comment]
I shall hold off on rebasing this until the next release is completed.

**Comment by kaleb-himes** [comment]
Just needs rebased with master and should be good to go. Windows testsuite issues have already been fixed in upstream.

**Comment by ejohnstown** [comment]
I'm close this. I have to add another API, and this needs rebasing.

**Pull request closed without merging**
