### PR TITLE
Kyber wolfSSL: don't configure 90s version

### PR DESCRIPTION
**Pull request by SparkiDev**
# Description

Kyber 90s isn't being standardized and is slower.

# Testing

Tested wolfSSL Kyber implementation still works.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

### CODE REVIEW

**Comment by SparkiDev** [comment]
https://github.com/wolfSSL/wolfssl/pull/5822

**Review by anhu — APPROVED** [review]

**Comment by anhu** [comment]
I will create a different PR that removes all calls to for kyber directory to liboqs and pqm4 in tls.c.

**Comment by anhu** [comment]
@SparkiDev , I'm almost done a change where I completely get rid of 90s and route all kyber calls to pqm4 and liboqs to wolfcrypt.  Why don't I just make this change in there? I propose we abandon this change, but I leave it up to you.

**Comment by SparkiDev** [comment]
No problems. Link your PR with this ticket and close this one when ready.

**Comment by anhu** [comment]
https://github.com/wolfSSL/wolfssl/pull/5836 does this.

**Pull request closed without merging**
