### PR TITLE
Expose serialization/deserialization methods separately from OpenSSL extra

### PR DESCRIPTION
**Pull request by vpetrigo**
Hello,

This is the intermediate version of WolfSSL 4.2.0c that we use in our FreeRTOS based application that exposes `WOLFSSL_SESSION` structure serialzation/deserialization methods without OpenSSL extra.
Let me know if it is required to update `configure.ac` to:
* introduce a flag for setting up the `WOLFSSL_SESSION_SER` macro
* update `user_settings.h` in `GCC_ARM` for example

Look forward to hearing from you.

### CODE REVIEW

**Comment by dgarske** [comment]
ZD 9545. Okay to test

**Comment by vpetrigo** [comment]
Hello, @dgarske. Would you tell if there is any new on that change and potential date when it may be expected in the mainline?

**Comment by dgarske** [comment]
Hi @vpetrigo, the changes look good to me. But in order to accept changes we need either a contributor agreement or license agreement in place. Our business rep Christin has been trying to work with you guys to get this in place. I'll send her a note to followup. Thanks.

**Comment by vpetrigo** [comment]
Hello, @dgarske. Would you tell if any updates available on that PR?

**Comment by dgarske** [comment]
Hi @vpetrigo , we cannot accept this due to contribution rules, however I have added it to our feature request list.

**Pull request closed without merging**
