### PR TITLE
Check the right size before freeing flatSignedAttribs in PKCS7_EncodeSigned

### PR DESCRIPTION
**Pull request by guidovranken**
ZD 11012

### CODE REVIEW

**Comment by kaleb-himes** [comment]
Jenkins, @guidovranken is an approved contributor. It is ok to test this pull request.

**Comment by kaleb-himes** [comment]
@ejohnstown, please assign a reviewer.

- KH

**Comment by dgarske** [comment]
@guidovranken , can you resolve the merge conflict? I will review this PR.

**Review by dgarske — APPROVED** [review]

**Comment by dgarske** [comment]
I resolved the conflicts and force pushed. This is ready for a final review once Jenkins is done.

**Review by cconlon — APPROVED** [review]

**Pull request merged**
